### ISSUE TITLE
SMAPI Support for v3.13.0+

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#10316]
Due to change in the way SMAPI is packed for v3.13.0+ @pathoschild has advised us that the installer needs updating.

> Yep, Stardew Valley 1.5.5-beta migrates from .NET Framework 4.5.2 to .NET 5, which requires some changes in the SMAPI installer structure. That's the format it'll use going forward after 3.13.0.

**Changes Required**
- [ ] Vortex needs to support detection of SMAPI when `windows-install.dat` is not present, but `windows\install.dat` is. 
- [ ] Upon installing SMAPI, Vortex will need to copy the file `Stardew Valley.deps.json` located in the root game folder and rename the copy `StardewModdingAPI.deps.json`. This file cannot be bundled with the mod because the two files must match exactly. An alternative way to do this would be on a `did-deploy` event or part of the game setup function. 
- [ ] Vortex needs to retain support for the older version installs in case the user has locked their game at an older version.

**Comment by TanninOne** [comment]
There appear to be more changes. The game exe is now named "Stardew Valley.exe" instead of "StardewValley.exe".

**Comment by FayneAldan** [comment]
For the second required change, I would personally say that should be part of deploying so that SMAPI versions can be installed without needing the correct version of SDV installed at the time of SMAPI install, which could happen accidentally if the user goes in or out of beta branches. It also might make more sense to, instead of copying the dep.json to the mod staging folder, just create a direct symlink from `Stardew Valley.deps.json` to `StardewModdingAPI.deps.json`. Any feedback on this?

**Comment by Pathoschild** [comment]
[Stardew Valley 1.5.5 just released](https://www.stardewvalley.net/stardew-valley-1-5-5-released-on-pc/), so SMAPI 3.13.0 is now live for all players. I'll add a note on the SMAPI page that Vortex isn't updated yet, which should hopefully reduce the influx of bug reports a bit.

**Comment by IDCs** [comment]
Vortex has been updated a while back to support the new installer.
