### ISSUE TITLE
Extension development question: How to get the user-defined mod name?

### ISSUE THREAD

**Issue by Mistralys** [Nexus-Mods/Vortex#10570]
I am currently trying to create a Vortex extension, in which I need access to the user's custom mod name, not the original name. The Mod interface `IMod` exposes the `attributes` property, but I could not find any reference on which attributes are actually available.

This extension, for example, uses the `modName` attribute, which I know to contain the original mod name:

https://github.com/Garethp/Vortex-Modlist-Backup/blob/3353f3c8c66b263992e847d728c5f0e4bf490ab9/src/index.ts#L32

Assuming I would like to get the user's custom mod name in the `transformModFormat` function, how would I go about it? After searching for a couple of hours, I suspect it may be related to `renderModName()`, but I'm not sure. I don't quite know where to look.

**Comment by TanninOne** [comment]
Hi @Mistralys
yeah, there is no fixed list of attributes because attributes can be arbitrarily extended by extensions needing to store information with a mod and also, depending on how/where from the mod was acquired, different information may be available.

There are potentially multiple attributes containing a name for the mod, the renderModName picks the "most readable", my suggestion would be to just use that if you can.

If that's not an option, here's the attributes it considers:
attributes.customFileName > attributes.logicalFileName > attributes.fileName > attributes.name

_customFileName_ is the name user gave the mod, if they ever renamed it inside Vortex so that should always be the first pick. However if the user has _not_ manually set a name, this attribute is unset.

_fileName_ is the file name as specified by the web server, so it might be something like "Alternate Start - Live Another Life-272-4-1-4-1608766947.7z", but if the file was imported or came from a server without api (atm anything other than Nexus Mods) this may be unset.

_name_ is also a file name, but it's derived from the file on disk it was installed from so this should always be set, but if it was renamed by the user or their download manager (including Vortex itself) this might be pretty useless as a name (worst case a download manager may set this as just a bunch of numbers).

_logicalFileName_ is Vortex's best effort to deduce a readable name from the info it was given, usually it will be fileName with the modid, version and timestamp cut off.

All these attributes except customFileName are immutable once a mod is installed and they may server other purposes apart from displaying them to the user so please never _change_ them.


Now _modName_ is similar to _fileName_ (or logicalFileName) as it's provided by the server _if_ the file was downloaded or found on Nexus Mods but it's the name of the mod page rather than the specific file.
If you look at a mod like this: https://www.nexusmods.com/skyrimspecialedition/mods/5804
It contains multiple variants that are effectively separate mods as far as Vortex is concerned (each file is distinct).
modName would be "A Quality World Map", whereas logicalFileName might be something like "A Quality World Map - Paper"

Vortex will always use the "file" name, preferring to be overly specific rather than too loose, otherwise a mod and its patches would all show with the same name.

**Comment by Mistralys** [comment]
Hi @TanninOne, thanks a bundle for the detailed response, that's exactly what I needed  :grinning:
