### ISSUE TITLE
Official Lutris Installer (for Linux)

### ISSUE THREAD

**Issue by Mumrik93** [Nexus-Mods/Vortex#10686]
So this is an alternative to [This Request](https://github.com/Nexus-Mods/Vortex/issues/2862).
I've been a proponent for a Linux Version of Vortex for quite a while but I've also had to described to me why it's a much better idea to run Vortex through Wine instead, since most of the games Vortex mods also has to be run through Wine (and/or Proton).
I've installed Vortex using a Lutris-install script before, but it was an older version and I had to turn off the auto-updates. 

When I attempted to install Vortex recently however, it just didn't work, Wine pretty much froze when I tried to start Vortex after the install. I attempted to install the official (and most recent) version of Vortex straight from Nexus, same problem. Lastly I attempted to switch computer that ran a different distro, but still same problem with both versions of Vortex.

So I pretty much request that a Official Lutris Install Script to be made available, so that Linux users can utilize the Vortex Mod manager, without having to make a native Linux version of the manager.

**Comment by Continous** [comment]
I think the ideal situation is Linux support, but the far easier and still perfectly fine solution is to simply support WINE. Targeting WINE as opposed to simply targeting Windows theoretically would help with any future platform switches as WINE is far more likely to be ported than the Windows-specific APIs themselves. IE, if we target .Net 6 we _need_ .Net 6. If we target WINE's implementation of .Net/Mono, we only need the user to have a relatively recent WINE version.

Of course, targeting WINE introduces a new plethora of issues. To make an off-hand list;

1. WINE is a moving target. If Vortex had targeted WINE from the start, Vortex would be multiple major versions behind by now.
2. WINE is technically not officially supported by anyone. This means that theoretically, WINE could become a dead end that Vortex is stuck in.
3. WINE supports a lot of platforms, but not all of them, and is not some silver bullet to fix cross-platform functionality.
4. Third party programs will still be outside of Vortex's control, and there's no way to easily distinguish between Vortex being incompatible with the tool, or WINE being incompatible with it, without user investigation.
5. While there may be a very few number of changes necessary to support WINE, there could very well be massive changes necessary.
6. WINE should work fine on Windows, but that does not mean that there will not be platform-specific issues anymore.

I think the best plan is still to just make Vortex's codebase entirely platform agnostic, if possible. It's not entirely impossible that in the next decade or so that Linux gains a significant market share.

**Comment by nicman23** [comment]
you can always target proton instead but that makes you rely on Valve.. You can also not support all releases and target specific versions.

**Comment by IsraPerez98** [comment]
> 

You could consider bundling a specific version of Wine with Flatpak/Snap , that way it's not a "moving target" anymore, something like Winepak applications, this would also make it compatible with every linux distro, including the Steam Deck

**Comment by Auravendill** [comment]
Correct me, if I am wrong, but wouldn't it be possible to upload Vortex to Steam, target a specific Proton version and have Steam download that one by default? 

Since even small Indie developers get their games on Steam, getting Vortex on there shouldn't be impossible, right?

This way the first two concerns would be solved:

- 1. No longer a moving target, but one specific version of Proton (users can experiment with others on their own risk; Steam allows users to overwrite the default with their own choice for each game).
- 2. Proton is supported by Valve

It would also help to get Nexus Mods faster on all those shiny new Steamdecks, before someone else fills that gap.

**Comment by Yu-457** [comment]
@NicBOMB  hey, thanks a lot for this installer. Ive been trying it today. 
So my experience so far is that the installation went quite smooth, i tried the proton one, everything went trough. i managed to install vortex and it runs. 
So thanks a lot for this, nice work!! :) 
Sadly it doesnt work with the game i wanted to manage yet. Thats more a vortex issue i fear after reading your article. Ive been trying to manage my already modded stardew valley installation. Its not found though and keeps forcing me to select a *.exe file. 
I didnt do much further testing there yet, but so far i didnt manage to load it up. 
Might be a game specific issue though. I noticed that darkest dungeon was found and and is shown as managable game. So that seems to work (didnt try modding it though)
Ill update this post if i find anything noteworthy.

Thanks a lot!

**Comment by Yu-457** [comment]
@NicBOMB  hey, thanks for the quick reply :) i didnt even expect more help. 
Thats really nice of you! 
I will try your ideas and report back :)

**Comment by Yu-457** [comment]
@NicBOMB  okay,  soo ive been doing some testing. sadly not very successfully. The install of the 64 bit extension did the trick. now the game is recognized (twice). thanks for this!

Ive encountered an issue with vortex itself tho which i didnt manage to work around. I cant open links in vortex. 

First issue i had, in case anyone else needs this ever, was that steam set the default browser to chrome. which led to vortex not being able to open links. Ive set the default to firefox. so now vortex can open external links in firefox. 

Second issue, i didnt figure out yet is that i cant open links from vortex. Once i go to a mod and click the downlod in vortex mod (tested with stardew and darkest dungeon) the link doesnt get passed trough. 
firefox gives me the option to select vortex and vortex-proton. Neither works. 
I went and selected the vortex *exe manually from the c drive installation path. neither option manages to pass the link trough. 
Do you have any idea what could cause this?

I tested with the vortex open and closed. it doesnt trigger anything
 
Do you have any idea what could cause this?

**Comment by Yu-457** [comment]
@NicBOMB  hey, 
thanks a lot again for this really great and detailed answer! I really appreciate it

I did try all the steps, including restarts, logoffs and running the proton symlink manually. 
Still the same behaviour though. I double checked the firefox links too. it looked like on your screenshot
I did try to open the download link with the desktop link too, this one doesnt work neither. 

Is there any log that could give us further insights? 
Could the desktop entry be faulty? Ive been only using the proton scripts.

![image](https://user-images.githubusercontent.com/47786587/175826318-ead7b409-9e72-4a90-8bcc-c3a0688b2c3d.png)

I hope im not causing too much work for you, I dont want to cause too much of a hassle. 😅
I managed to get all the mods i wanted up and running for now without vortex. For now at least

**Comment by Yu-457** [comment]
@NicBOMB  thanks a lot! Its really cool youre creating this for the community! 

Good to hear that you were able to reproduce it.
I think ill wait till you got the new installers and then test with those :) Im not too familiar with linux commands (yet) so its really great youre adding those to the installer. 

Thanks a lot

**Comment by MPritsch** [comment]
@NicBOMB Thank you for all the effort! I was able to install Vortex via your Lutris yaml on the steam deck and use it for modding. I'm not sure if this is an separate issue or part of the installation/setup:
The game I mod is installed on the sd card. Vortex modifies the compdata folder of the steam on the sd card to write the plugins.txt. However the game launches with the compdata folder located on the base drive. This effectively means that any mods that Vortex tries to activate aren't, because the wrong plugins.txt is used. I worked around this by symlinking the folder which contains the plugins.txt on the sd card.
This might just be a limitation with proton, but I'm not sure. What do you think?

**Comment by MPritsch** [comment]
> So, I would like you to move or delete all Oblivion content and reinstall if that's okay. I concur with your assessment; it was probably MO2 doing the reasonable thing and creating files in the most likely valid prefix necessary for Oblivion in a regular environment.

I just transfered a different game from the base storage to sd-card. The compdata folder was copied to the sd-card, but still exists on the base storage. When I manually delete the one on the base-drive, it creates a new one on the base-drive. There is also no symlink to the sd-card. Which means the one on the sd-card is completely pointless as steam does not use it -> this looks like a bug.
With another game which was solely installed on the sd-card, the compdata folder was created on the base storage. I don't think ModOrganizer 2 was the problem here, just happens to find the same folder as vortex.

> Don't worry about that, I have already thought of the solution for this situation exactly. I'm going to check the primary location, which should fail on a Steam Deck, then also check the default Steam Library's compatdata folder since that cannot be removed. My best guess is that Valve keeps the compatdata folder on the Steam Deck's main drive to allow your game saves to be backed up to the Steam Cloud even if the sd card is ejected. Entirely reasonable IMO. The actual size of the compatdata necessary for your games should also be very small anyways.

Looking forward to an easy working solution :)

> Try the following symlinker Lutris extension corresponding to the installer you used AFTER cleaning Oblivion's files. If this works, it may also enable Vortex to detect the other games you have already installed, played once, and which I indicated are listed in the Supported or Untested categories above, like The Witcher 3.

Will do tomorrow

**Comment by MPritsch** [comment]
> So, I would like you to move or delete all Oblivion content and reinstall if that's okay.

> Try the following symlinker Lutris extension corresponding to the installer you used AFTER cleaning Oblivion's files. If this works, it may also enable Vortex to detect the other games you have already installed, played once, and which I indicated are listed in the Supported or Untested categories above, like The Witcher 3.

@NicBOMB Instead of deleting I just renamed the common folder and the compdata folder on both internal storage and sd-card. After that I uninstalled Oblivion via Steam and reinstalled it. After the download I ran the symlinker and looked at the install.log:

```INFO: CURRENT_APPID="22330" CURRENT_GAME="The Elder Scrolls IV: Oblivion " CURRENT_INSTALLDIR="Oblivion"
GOOD: Found The Elder Scrolls IV: Oblivion  installation at /run/media/mmcblk0p1/steamapps/common/Oblivion
INFO: platform_override_dest: "linux" platform_override_source: "windows"
INFO: Proton Prefix for The Elder Scrolls IV: Oblivion  not found at /run/media/mmcblk0p1/steamapps/compatdata/22330/pfx
INFO: Trying /home/deck/.local/share/Steam/steamapps/compatdata/22330/pfx/ instead!
GOOD: Found The Elder Scrolls IV: Oblivion  Proton Prefix in default Steam Library at /home/deck/.local/share/Steam/steamapps/compatdata/22330/pfx/
```

Looks like the correct folder was found after first searching on the sd-card.

I made a mistake because I then launched vortex. It complained about not being able to find the correct loot path. Also it shows all plugins as disabled, probably because the plugins.txt is missing in the default compdata configuration. So I moved the compdata folder and relaunched vortex but the error persisted.

Rerunning the symlinker again fixed it though.

**Comment by MPritsch** [comment]
> Where exactly did you move Oblivion's compatdata folder to? It should remain in the default `/home/deck/.local/share/Steam/steamapps/compatdata/22330/` now. If it was still in the SD Card, then moving it to the compatdata folder alone would have resolved the issue. The links were already pointing there, although running the linker multiple times won't break anything.

I copied them to the internal storage. The sd-card now has no compdata folder for the game.

**Comment by Yu-457** [comment]
@NicBOMB  Hey, not yet. I had a busy week and no time to try it yet. I will do this week(end) and give you a headsup

**Comment by Yu-457** [comment]
> > Ive been trying to manage my already modded stardew valley installation.
> 
> @Yu-457 were you able to manage mods (download, install, deploy, remove, and uninstall) with Vortex in both Stardew Valley NATIVE and PROTON?

Hey, 
so i managed to do some testing. and its been only partly succesfull. I did a reinstall of the whole proton setup. (i didnt uninstall anything before tho, idk how to do that under linux ^^°)
after the reinstall the config file contained the new commands you mentioned as well. 
I did not manage to get it consistently to work. 
Overall the whole behaviour seemed to be weirdly inconsitent. 
thats what i tried ->

I tried to get the first mod from nexus, nothing happend. I changed firefox back to "always ask" and tried to figure out which proton link was the working one. After some clicking i got it to download once. 
I saved that option so firefox would not ask anymore. tried with a mod collection - nothing. 
Tried with a normal  mod - nothing. 
set it back to always ask and tried again - worked. 
tried it again with another mod - stopped working again. 

so in the end i managed to download and depoy smapi, but nothing else apart. 
sorry

im kinda done with stardew and might start the witcher 3 soonish. i can do some fresh testing with an unmodded game there. Maybe its the stardew installation thats kinda botched too already.

**Comment by FederAndInk** [comment]
Is this ready to be published on lutris.net yet? It could be great if it could be published.

**Comment by FederAndInk** [comment]
I get this when trying your script

![Screenshot_20220720_135355](https://user-images.githubusercontent.com/24270152/179975622-1c1b9fa5-f7e7-481a-bc97-fa6df66e3641.png)

**Comment by FederAndInk** [comment]
> > I get this when trying your script
> > ![Screenshot_20220720_135355](https://user-images.githubusercontent.com/24270152/179975622-1c1b9fa5-f7e7-481a-bc97-fa6df66e3641.png)
> 
> That should be included with the Lutris runtime AFAIK. Make sure to add the runner from the list in your wine runner settings for Lutris if it's not being downloaded automatically. I will make a version ready to publish rn. My script is already Steam Deck tested and is ready for general testing. Hopefully publishing a beta build will get more replies about mod deployment.

The runner is installed, but this version isn't available, it worked with lutris-GE-Proton7-22 though

**Comment by GlitchWalker** [comment]
Hi there, I'm really looking forward to getting this working!

Unfortunately I wasn't able to... Trying to install the Wine version kept giving this error:

![Screenshot_20220722_185930](https://user-images.githubusercontent.com/26338453/180497893-ac921690-9ace-4d58-a020-49853c714a56.png)

I also tried the proton version, but that threw up the same "Failed to retrieve wine" error that was mentioned above, even when I tried running it with lutris-GE-Proton7-22.

I look forward to trying out a newer version whenever it's available!

**Comment by FederAndInk** [comment]
> I also tried the proton version, but that threw up the same "Failed to retrieve wine" error that was mentioned above, even when I tried running it with lutris-GE-Proton7-22.

Look at the wine runner available versions, download a proton one and specify it in the .yaml

**Comment by FederAndInk** [comment]
btw, @NicBOMB, why not make a repository so the changes can be tracked, people can open issues and PRs and all? :)

**Comment by FederAndInk** [comment]
Right, yeah it could be really cool if it were under Nexus-Mods/Vortex-Lutris, you could have right to push to the repo too maybe?

**Comment by dglavimans** [comment]
Thanks for the time on this @NicBOMB, I am trying to run your installer but when I run the script from Lutris it returns the following: this installer requires steam on your system. Lutris does find my Steam games already 

I am trying this script on a Steam Deck also

**Comment by dglavimans** [comment]
Hi @NicBOMB so I am on the Steam Deck, with his native distro on desktop mode. I didn't really tinker with it. I do have an SD card for the games but Steam should still be located on the main memory 

Lutris is installed through the Discovery store

**Comment by FederAndInk** [comment]
I would say, try flatseal? maybe Lutris can't access steam without giving it the rights

**Comment by dglavimans** [comment]
hi @FederAndInk I installed flatseal and gave Lutris all the directory permissions but still the same error

**Comment by dglavimans** [comment]
@NicBOMB the which steam command does return /usr/bin/steam

but the stat /usr/bin/steam returns: 

File: /usr/bin/steam -> /usr/bin/steam-jupiter 

I also installed Lutris with the link you provided (and needed to do a few steps of the flatpak instructions beneath it to get it discovered in the discovery store)

**Comment by dglavimans** [comment]
@NicBOMB so I deleted the steam entry from required-binaries. Throws the following: This installer requires xdc-mime on your system

**Comment by FederAndInk** [comment]
Maybe it could be worth to try on holoiso to adjust the script?

**Comment by dglavimans** [comment]
Will give it a try in a few days.. I do think I need to look a bit into why Lutris cannot see my path instead of just deleting the whole required-binaries section in the script. Did other Steam Deck users actually successfully install it with the provided script? 

Thanks both for the help so far!

**Comment by NightHammer1000** [comment]
Maybe I am understanding flatpak wrong.
But installing these Packages on the System itself won't make them Available in Flatpak as far as I know.
The Lutris Flatpak itself would have to ship them, or not?

I had Issues with Install Scripts before with missing tools and Installing the missing things in SteamOS itself did not fix them.

**Comment by NightHammer1000** [comment]
Anything other than Flatpak is not viable on Steam Deck because every package has its Dev Libraries stripped, nothing will build without Issue, and Installed Packages get wiped on every minor update.

**Comment by dglavimans** [comment]
Hi @NicBOMB I used the steam deck variant of the scripts after the console returned correct all the libraries 

It’s been installing for a long time now and it seems the program opens. It still is on installing game data though, let it sit here or? 
![image](https://user-images.githubusercontent.com/110782207/183474037-c0fe0fde-b3d0-4e6f-8bca-cf9775f19283.jpg)

**Comment by dglavimans** [comment]
It opened the FAQ as a pop up but didn’t show the whole text sadly I couldn’t scroll it seemed

I ran into some other issues with the browser not opening in Vortex so for now I kinda shelved it for modorganizer2 which seems to does the trick for me

**Comment by purpleshadows** [comment]
I'm having trouble with Vortex when installing collections. It freezes.

**Comment by frostworx** [comment]
no need to ping me: https://www.reddit.com/r/SteamTinkerLaunch/comments/wiaj1b/we_have_just_lost_cabin_pressure/
send a PR instead @NicBOMB

**Comment by dglavimans** [comment]
I actually installed the STL and it worked fine with the Steam Deck. It picked up Skyrim SE and it wasn’t that much of a hassle.

only thing I cannot get to work is in gamemode it doesn’t launch the STL with the command on an absolute path to the STL also the compat sees STL but when I use that instead of Proton it just crashes

for now though it is deemed for me as the easiest as it kinda just worked (but not on gamemode, will see if I can do anything about that tonight)

**Comment by Continous** [comment]
With the move to Dotnet .6 Vortex is very broken through WINE. The general issue is that DotNet is largely unsupported _through_ WINE, and Vortex doesn't work through Mono, nor will/can it use the Linux libraries.

**Comment by purpleshadows** [comment]
Sorry @NicBOMB for writing from documentation thus making a larger post about STL. I thought it would be a good idea to make it less confusing for those who want to try this option since when I tried it, there were some things I had to research and were not so obvious.

The only problem with your installer are collections, it just freezes while downloading and then I have to quit vortex from tray. 
The problem is that when I launch vortex again and continue the collection install, some of the mods are not installed properly and according to the creator. 

It's an odd bug, Vortex doesn't seem to like constant downloads or large amounts of data being downloaded.

**Comment by purpleshadows** [comment]
One with many mods, @NicBOMB like this one:

https://next.nexusmods.com/skyrimspecialedition/collections/gqoewd

**Comment by purpleshadows** [comment]
If yours doesn't freeze it might be a problem with my setup. I will probably reinstall with your installer. 

I know I shouldn't close vortex but it just becomes unusable. The only way to reproduce this is to just downloads huge amounts of data.

**Comment by Continous** [comment]
> > With the move to Dotnet .6 Vortex is very broken through WINE. The general issue is that DotNet is largely unsupported _through_ WINE, and Vortex doesn't work through Mono, nor will/can it use the Linux libraries.
> 
> Is this about Vortex 1.6 prereleases? I haven't encountered DotNet issues with Vortex at any point.

Yes, and the problem is generalized to my understanding. DotNet 6 is just entirely unworkable under WINE.

**Comment by Continous** [comment]
> @Continous Did you need to make any changes when updating from 1.5 to 1.6?

@NicBOMB I had to reinstall my system dotnet files. It is likely that WINE/Vortex is actually attempting to use native system Dotnet initially.

**Comment by TanninOne** [comment]
@NicBOMB That isn't actually related to Vortex at all, the exe of the .NET application decides where it looks for the runtime and verifies the installation. Vortex runs a dummy exe and parses the error message to determine if it runs correctly or what's missing if it didn't.
There is an environment variable DOTNET_ROOT that should allow you to specify where it looks for .NET, maybe that helps.

**Comment by tommy87** [comment]
@NicBOMB 
when i try to run your latest install script at my steam deck i run into an problem. The installation process works fine and in the end of the installation the vortex GUI opens succesfully. But after the installation has finished it will not open again. I think it could have something to do that vortex is instantly trying to updating itself, but its only an assumption.

When i enable error messages it only say something about a critical error, but without usefull details. Im also not very familar whith wine. Do you have any ideas what i could try?

**Comment by FederAndInk** [comment]
> @NicBOMB when i try to run your latest install script at my steam deck i run into an problem. The installation process works fine and in the end of the installation the vortex GUI opens succesfully. But after the installation has finished it will not open again. I think it could have something to do that vortex is instantly trying to updating itself, but its only an assumption.
> 
> When i enable error messages it only say something about a critical error, but without usefull details. Im also not very familar whith wine. Do you have any ideas what i could try?

yeah, I made it work by disconnecting from internet just before lutris launch Vortex then you need to disable auto updates in Vortex

**Comment by tommy87** [comment]
You are great, the solution is so simple that i havent even thought about it. But now it works, thank you

**Comment by DrLegitamate** [comment]
i seem to be having a problem with the install script recognising steam as when i try to install i get a popup saying ''this installer requires steam on you system none''

**Comment by palexdev** [comment]
I was experiencing the same issue many people encountered with the official Lutris script
Vortex installs correctly and opens just fine the first time, then it won't open again for some reason

I read somewhere that Vortex could be opened by using the terminal/prompt I tried both with CMD and Bash shell (from Lutris) and yes, it was opening.
Then I tried to tinker with the configuration and I noticed Vortex is run with the `-d` argument (which is undocumented, or at least I could not find anything that explains what is it for). Turns out that removing that argument will make Vortex always open, duh. Watch out, for some reason sometimes the argument is restored, if Vortex is not opening again, check if it has been restored and delete it again. Enjoy

**Comment by BloodyIron** [comment]
LOL the above response is already indexed and searchable by Google, wow that's fast.

I cannot find where "vortex-prefix-updater.sh" is being downloaded from, let alone the contents of it. I can't yet find it on github or elsewhere so far... :/ that's concerning.

**Comment by BloodyIron** [comment]
So my "solution" was...

`sudo ln -s /bin/sh /usr/bin/sh`

Not 100% sure if that's "best practices" so READERS CONSIDER THAT. But... as a seasoned Linux vet (15+ years) I am not really seeing any cursory problems with such a practice. I hope it doesn't bite me in the bum in the future though lol XD

**Comment by BloodyIron** [comment]
> > LOL the above response is already indexed and searchable by Google, wow that's fast.
> > I cannot find where "vortex-prefix-updater.sh" is being downloaded from, let alone the contents of it. I can't yet find it on github or elsewhere so far... :/ that's concerning.
> 
> @BloodyIron Don't be too concerned, it is open source ;). That file is generated by the Lutris installer script I wrote. You can read exactly what files are generated by it in the script preview or the updated version in my repo: https://github.com/NicBOMB/Vortex/blob/deb6fbdaf64a18d9a9303394325be80307a7b946/vortex-lutris-installer.yml#L1023-L1065
> 
> My script specifically **DOES NOT** download scripts randomly from the internet, as the previous installer did. My script instead unpacks (using write-file) executable helper files.

Well the fact I expected it to be open source is why I wanted to read the contents in the first place! ;PPP I'm not exactly concerned, as this comes from a trusted source, but I wanted to understand the nature of how it was executing, since it seems odd it cared about _where_ sh is as opposed to _can I use sh in my scope_.

Thanks for clarifying that Lutris literally writes the file on-spot! I didn't pick up on that. I expected a wget or something like that hehe ;D And I do appreciate the value of writing them clearly vs downloading scripts, thanks for that planning! Yay!

As for why it cares about _where_ sh is... I can't really see from the script why that mattered to it... but getting that symlink up has enabled me to get further. How odd...

**Comment by BloodyIron** [comment]
> > As for why it cares about _where_ sh is... I can't really see from the script why that mattered to it... but getting that symlink up has enabled me to get further. How odd...
> 
> @BloodyIron It has to do with the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) I used. It expects `bash` to exist at [`#!/usr/bin/bash`](https://github.com/NicBOMB/Vortex/blob/deb6fbdaf64a18d9a9303394325be80307a7b946/vortex-lutris-installer.yml#L1024) (common for many distros like Arch). I'll update the location to use the generic `/bin/sh` location instead, which should improve compatibility across distros.
> 
> You can simply change the shebang in each script to use the other location instead, though creating a symlink should be fine too.

Curious then that the symlink for sh "fixed" it for me, instead of for bash... but yeah I don't have /usr/bin/bash either (even though bash is available in the environment). How odd!

Thanks for your work, and help! :)

**Comment by BloodyIron** [comment]
@NicBOMB unsure if off-topic for this thread, but I'm getting the Vortex client configured etc. Namely for Fallout New Vegas, which is installed via STEAM via Proton. Naturally that creates a prefix elsewhere for fallout.ini and such, and Vortex is complaining it's not where it expects it (C:\...).

Any recommendations? I'm not sure if this will be problematic as I'm only now starting to get into FO:NV modding and I genuinely don't know if I should care about Vortex complaining about this or... not.

**Comment by BloodyIron** [comment]
Ugh Vortex won't respond to XDG pop-ups from nexusmods' website... any advice on what I might need to do for that to be bridged?

**Comment by Continous** [comment]
> Ugh Vortex won't respond to XDG pop-ups from nexusmods' website... any advice on what I might need to do for that to be bridged?

You could manually set it up. If that doesn't work you're SOL.

**Comment by wbehrens-on-gh** [comment]
Installing on fedora 37 causes the installer hang when opened during the install. Are there any logs I could provide that would help?

**Comment by wbehrens-on-gh** [comment]
Also, is a specific reason to choose lutris for this package instead of packaging the wine app as a flatpak/appimage?

**Comment by HawthorneK456** [comment]
Hi all,

As per my last update in the linked issue; https://github.com/Nexus-Mods/Vortex/issues/2862, this issue will be closed as it will be part of the considerations for the design and development of the Nexus Web App. 

To give some context, you may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management. As a result we are undertaking an audit of all outstanding Vortex issues/requests to determine their validity. 

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874

**Comment by Luiz-AVcruz** [comment]
Well, and now? still not planned?
