### ISSUE TITLE
Compilation/Starting error "DLL initialisation routine failed"

### ISSUE THREAD

**Issue by M4lik** [Nexus-Mods/Vortex#107]
Hey There!
Great work so far with Vortex!

Sadly I get an error as soon as I try to `yarn build && yarn start`

![My Error](https://user-images.githubusercontent.com/3097625/37844503-462a271e-2ec8-11e8-9950-e99642b5876b.PNG)

Tried for quite a while now to fix it, but I'm still not sure whats causing it.

Greets
Malik

PS: Sorry for the German in the error message 😅

**Comment by simsrw73** [comment]
Try deleting the contents of: %LOCALAPPDATA%\Temp\native_cache\win32-x64-57 (ish?)

Not sure about the German. It's a different error than the one I got, but it's in the same place. Try clearing that directory and 'run start' again.

**Comment by M4lik** [comment]
That, sadly, didn't fixed it. :/ (The directory was empty anyway).

I've been trying around and noticed when I remove the `condition` tag from the `BuildSubprojects.json` file Vortext starts. I instantly freezes, because leveldown.node now throws an error. I think it might has somthing todo with the windows build tools, but I'm still quite not shure how, because I've installed everything needed (at least the things from the list in the `readme.md`)

**Comment by simsrw73** [comment]
Yeah, I wasn't sure that was it. I had also got an exception related to crash-dump, but it was about a file in the directory I mentioned. I can build and run Vortex on my system. The only difference on my system from the Tannin's instructions is that I've downgraded node to 7.10.1 and Yarn to 1.0.0*. I just now cloned Vortex to a new directory and built and run it with that configuration and had no problems. But I don't think that's it because I've built successfully with later versions at an earlier point, although not since his most recent commits. Do check task manager: after both successful and halted builds I VERY often find stray processes (MSBuild, Node) still running and sometimes locking files. What other error message are you seeing?

* (I downgraded because any version of Node later than 7.x generates an exception in fomod-installer/edge when I 'Install' any FO4 mod about version mismatch, but downgrading only changes that exception to a different one that I haven't had time to figure out. Yarn version probably doesn't matter; I just downgraded it to get rid of a warning that Yarn doesn't support Node versions xxx.)

**Comment by M4lik** [comment]
Update: I've just created a fresh VM and installed everything as said. Still the same error.

**Comment by TanninOne** [comment]
Vortex uses a couple of native libraries. These libs have to be recompiled for the exact node-version being used. This version is "electron 1.8.2" at the moment. Electron uses a patched version of node that will almost never be compatible with the node version you have installed.

This is why the build process has to rebuild those modules. When we create a distribution (yarn dist) the modules are all recompiled during the build process by the "BuildSubprojects.js" script.
For development builds this would be too tedious because of an annoying yarn behaviour (*) which is why in development we use a require-hook to rebuild the modules on-the-fly.

**If you read nothing else, read this!**
This require hook (in src/util/requireRebuild.ts) works by catching load errors, parsing the error message and if the message indicates the problem was with loading the dll, it rebuilds it and tries loading again.
It may be that with your error messages being localised they aren't recognised. You could try adding your german error messages or preferrably see if you can force the process locale to be english. Preferrably because it's impractical to add recognition for all possible languages.

(*) A related problem is that yarn will unfortunately recompile native modules for the global node version on install/update operations meaning that even when you have built the modules for the correct electron version, yarn may replace them with the wrong version again and I haven't found a way to prevent yarn from doing that.

**Comment by M4lik** [comment]
Ive changed my system language to English (US) now and it still doesn't work. 

Sorry to bother you with this sh*** but I think this project is too good to don't invest a little bit of time to help you :)

**Comment by M4lik** [comment]
Ok, so changing my system Language to English DID help. Many Thanks. :)

But I think there has to be a better way than that. Now I got a load of other errors. Let's see if I can fix them :D

Will close this Issue for now :)

**Comment by TanninOne** [comment]
I would be very happy if we found a better solution, unfortunately it may not be simple as there are several different error message we might get and there isn't really a way to identify the error apart from parsing the message.
The alternative would be to rewrite requireRebuild to use a hard-coded list of native modules and then just go "this module is on the list so it should load fine If it fails, rebuild on the assumption that that is the problem."
Should work in practice, only real disadvantage is that we then have to maintain a hard-coded list of the native modules.

I'll reopen this so I don't forget about it and in case others come across the same problem.
