### ISSUE TITLE
Fallout 4: Failure to update masterlist and failed to load master-/userlist

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [Nexus-Mods/Vortex#10837]
**Describe the bug**
For some (inexplicable) reasons, Vortex keeps giving me messages like "Failed to update masterlist" or "Failed to load master-/userlist", but provides no explaination of why this error shows up.

**To Reproduce**
1.  I have installed Vortex with the custom installation directory to be sure was installed under C:\Games\ and not somewhere strange.
2. I have tried to install the Fallout 4 Script Extender but, for some reason, it'd not setup properly, so I have downloaded, setup manually and configured manually.
3.  I have added Fallout 4, but it failed to set properly the mod download and mod stage setup directories, so I ended up creating two ad hoc directories "C:\Games\Mods\Download\Fallout 4" and "C:\Games\Mods\Staging\Fallout 4" but Vortex didn't seem to like it for some reason.
4. I have proceeded to download "Mod Configuration Menu", "Horizon", "Crossbows of the Commonwealth" and "Homemaker" and after each and every installation the same issue with the lists showed up.

**Expected behavior**
Frankly I thought Vortex was supposed to be extremely easy to use and almost dumb-proof (and it was a few years back when I originally installed it), so how is it possible that this software could give so many error messages with so little information to understand what is the problem?

I've simply done a custom install to be sure Vortex was installed in the Games directory and not in Programs or in some strange directory I'll never find again...could be really **just that** who messed up everything??

I have tried to look for a log file, but the the vortex.log file seems to be generated only to be attached from the in-app feedback, so I have no idea where to look to attach it here... 

P.S.: If you tell me where to look for I'd gladly provide you the log file, however, but I'd like to understand what is happening...

**Screenshots**

See in the attachments...

**Platform (please complete the following information):**
 - OS: Windows 10 (10.0.19042)
 - Vortex Version 1.4.16
 - Memory: 11.90 GB

**Additional context**
![Vortex Error](https://user-images.githubusercontent.com/83535483/150814256-f7a9dce4-b9e1-4fcf-ae7f-f65da540c869.jpg)
![Vortex Error 2](https://user-images.githubusercontent.com/83535483/150814260-513fb4df-2f59-4883-814d-5c1514f05ea8.jpg)

**Comment by TanninOne** [comment]
a) Have you not seen the "More" button on these error messages?
b) If you know that log files can be attached via in-app feedback, why didn't you report this through in-app feedback?

The log files are in %appdata%\vortex but I generally advice against attaching them to a public issue tracker like this because it's hard to predict whether any extensions/foreign code logs something confidential. If you use the feedback system your log is only accessible to us vortex devs.

Finally: The "Failed to update masterlist" error message is a network error from github where loot hosts its masterlist. That's temporary and out of our control.
The other error messages are probably caused by the first, probably it got a corrupted/partial download for the masterlist that it can then not parse.

The only alternative we have here would be to not report the issue and leave you scratching your head over why it's not working, would that be more user friendly?

**Comment by Skarm-Ghelmaad** [comment]
Obviously I have seen that "More", but it doesn't provide any better information.

Well...apparently it is solved, but if the message had referred to the repository instead of generically referring to a "network problem", I'd have assume it'd have solved over time...

**Comment by KAVIVENDHAN** [comment]
1.Close vortex 
2.Install turbo vpn free
3.turn on turbo vpn 
4 .Open vortex

It helped for me
