### ISSUE TITLE
Run commands are a bit messed up. (and other project related things)

### ISSUE THREAD

**Issue by M4lik** [Nexus-Mods/Vortex#111]
To develop with the current environment is a little bit uncomfortable.

The main point I have at the moment is that some things a just plainly copied form left to right and some things need to be compiled. This is fine, but kind of annoying if you are not developing the core application but things like the game extensions or some of the other assets. If you do something with the typescript files, we have the nice advantage of `tsc -p . -w` (alias `buildwatch`) so you don't have to build over and over again.

Additionally I don't really like the project structure itself (`extensions` althoug these are plugins, the `app` dir and a few other things)

**How to fix?**

The first point can be fixed with a little bit of `package.json`-magic (like a `refresh_start` command or putting it in `start` directly (I think this was the case at some point in time, was it?))

The second point is mainly a case of "get used to it", so I will stop whining in a moment, but there is one thing that is REALLY bothering me: Why don't we have a stable master _at all times_? I really encourage you to look into [git flow](https://danielkummer.github.io/git-flow-cheatsheet/)

Just wanted to get this off my chest.
Sorry.

**Comment by M4lik** [comment]
Oh, and I will create an config for Jetbrains' WebStrom. :)

**Comment by TanninOne** [comment]
Your main point is a bit hand-wavy tbh.
source files (ts) are compiled, assets just get copied, yes. What's the problem?
extensions are treated as separate projects, they are only integrated into the main repo for the time being because Vortex doesn't have a simple way to get extensions from an online source and this way it's easier to create the releases with bundled extensions.

If you work on an extension you don't need the main vortex repo at all, you just need the individual extension and that has it's own package.json which you can set up for easier development if you like (like it's own tsc -w script).

Regarding your second complaint: Is this really about the word "extension" instead of "plugin"??? This is a problem how?

**Comment by M4lik** [comment]
I see that my explanation was not good enough and my point was not clear. The problem is not the past is copied, part is build (that lies in the nature of electron, typescript and javascript), but the procedure how to build and test-run the project. If it's wanted that plugins can be later just installed on the user's machine I get the concept now. Sorry for the complaint.
Although I'm curious why it's getting copied in the first place. tsc does exactly that with `.js` files if I'm not mistaken...

> The second point is mainly a case of "get used to it", so I will stop whining in a moment, but there is one thing that is REALLY bothering me: Why don't we have a stable master at all times? I really encourage you to look into git flow

The thing with the "wrong" name is that for somebody who is new to the project and doesn't know how some things are structured (yes I know there is a `structure.md`) it can be quite irritating. I also don't get why there is the `app` directory.

> **app/**: staging directory for production build

I interpret this as the source dir for `yarn dist`, right? Why? We don't have to ship the whole project twice if somebody wants to build from source. So when we have a stable `master` `yarn dist` can simply be run from the same source as the everybody else. To be precise it could be a combination of `yarn build` to the `out` dir and then a `yarn dist` from this.

**Comment by TanninOne** [comment]
It's **not** the wrong name though! In Webbrowsers (Chrome, Firefox, Edge, ...) a third party "thing" extending its functionality is an extension whereas a plugin is something else.
Visual Studio (both the regular editions as well as code) have extensions, not plugins.

The term plugins in the context of modding is already used (remember esps?) so "extension" is the more fitting term and the one with less potential of confusion in this domain.

Regarding "app": This is confusing you because you probably haven't worked with electron yet.
It's common practice to use a two-package structure with electron-builder because it makes the distinction clearer between what package are required at runtime and which are used during development only.
It's not _required_ but a fairly well established convention.

Regarding harsh tone: Don't worry about it, I'm german as well. ;) No offense taken.

**Comment by M4lik** [comment]
I never said that "extension" is wrong, it just CAN be confusing if your new to this topic (like me :sweat_smile: ) but if it's a common naming convention than I am fine with it :)

And the same applies to "app": If it's commonly used that way in electron, than I will shut up right now.
Feel free to close this issue now.

Danke und dir noch einen schönen Tag ;)

**Comment by TanninOne** [comment]
I guess this can be closed, right?
