### ISSUE TITLE
Bug Report - Vortex keeps recognising offline mods as other mods hosted on Nexus

### ISSUE THREAD

**Issue by Arkadious** [Nexus-Mods/Vortex#11217]
**Describe the bug**
When you are downloading and installing mods which aren't hosted on Nexus, there is a chance that Vortex will recognise the mod as a different one hosted on Nexus. Furthermore, any mod data information revisions (author, version, source etc.) will be reset upon disabling and uninstalling it a game.

**To Reproduce**
Steps to reproduce the behaviour (using an example I have had happen):
1. Go to https://www.afkmods.com/index.php?/files/file/2295-quest-conflict-fixes/
2. Click on download
3. Open nexus and select Skyrim SSE as your active game
4. Drag the downloaded mod into the Drop File(s) section
5. Disable and/or install the downloaded mod and make some changes to its mod description and info
6. Uninstall the mod

**Expected behaviour**
Upon adding the mod to Vortex, it will detect it as an existing mod hosted on Nexus and add that mods info the downloaded mod. After you gain the ability to alter the mod information by disabling and/or installing the mod, and then uninstalling it, the information will revert to what Vortex detects from Nexus.

**Screenshots**
None

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version: 1.5.5

**Additional context**
None

**Comment by TanninOne** [comment]
Vortex is correct in that that mod page at one point hosted that file and since nexusmods.com doesn't permanently delete files any more, it can still be downloaded from there.

For Vortex it makes sense to use the available meta information rather than not have anything at all about a mod.

It's unfortunate that the description and such on nexus mods doesn't actually have anything to do with the mod in question but Vortex can't know that, all Vortex knows is that this exact file exists on the server on that page, it has to assume the meta information is for that file.

This problem is between the the uploader, the copyright holder of the file and nexusmods.com support, it's beyond my power to fix anything here.
