### ISSUE TITLE
All mods and downloads deleted after update

### ISSUE THREAD

**Issue by BeefNugget** [Nexus-Mods/Vortex#113]
I just updated through the program to 0.13.6 and now my Mods folder and my Downloads folder are both empty. It says I have no mods installed the plugins and stuff are still there and when I look at the game it says I have 65 active mods, but no way to manage them as both folders are completely empty. I was part way through modding my game and I guess will have to start from scratch.

**Comment by TanninOne** [comment]
Did you change your mods/downloads directories to be inside the vortex application directory? Something like "C:\Program Files\Black Tree Gaming Ltd\Vortex\mods\skyrim" ?

**Comment by BeefNugget** [comment]
Yeah the mods were installed in E:\Mods\Vortex\Mods which is where Vortex is installed. I am just starting over reinstalling just thought I would post this here to let people know it could happen to them no idea why it happened. I looked everywhere to see if the mods were moved due to directory change during update or something, but they are nowhere to be found completely removed due  to update. I am just now scared to ever update the program again.

**Comment by TanninOne** [comment]
Then this is a known non-issue: https://forums.nexusmods.com/index.php?/topic/6454716-do-not-put-modsdownloads-into-your-vortex-install-directory/

Do not put your own files into the application directory. Actually you shouldn't do that for any application because a lot of applications will do the same when you reinstall/uninstall/update them.
