### ISSUE TITLE
Uninstalling Vortex will delete everyting in the app folder, being part of Vortex or not

### ISSUE THREAD

**Issue by LeoBeliik** [Nexus-Mods/Vortex#11503]
**Describe the bug**
As I installed Vortex with Winget I did give a wrong path for the installation (I assumed the installer will create a folder for the app and not dump everything in said path), once I noticed this I went to the folder (in this case D:/Programs) and use the uninstaller executable the app have, and it deleted everything in the Programs folder.

**To Reproduce**
1. Install Vortex
2. Create some folders and archives
3. open the uninstall vortex exe
4. everything is gone

**Expected behavior**
Only what belongs to the program should be deleted

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.5.7

**Comment by TanninOne** [comment]
We do not provide or maintain the Vortex installer on winget. Our uninstaller is intended to revert an installation from _our_ installer.
Your complaint is with winget or whoever maintains that package

**Comment by LeoBeliik** [comment]
This still happens with *your installer*, the problem here is not the installation is the *uninstalling*, as you can see in the title.

**Comment by TanninOne** [comment]
No it doesn't because our installer(s) always install Vortex into its own directory.
Even if you use the custom installer and specify d:\foobar as the target directory, it will actually install to d:\foobar\Vortex
And _that_ directory, which contains only Vortex, is then fully removed by the uninstaller.

I don't see how you could use our installers to install Vortex into a directory that is already occupied by other files.
And if you add files to the Vortex directory (or the directory of any application that isn't explicitly "portable" or written for windows 95), that's your own fault.
Our recommended installer installs to c:\program files where it will be read-only for regular accounts exactly because putting additional files into the application directory is not supported.
