### ISSUE TITLE
Suggestion - Read More Data From Info.xml

### ISSUE THREAD

**Issue by BellCubeDev** [Nexus-Mods/Vortex#11776]
### **Is your feature request related to a problem? Please describe.**
Vortex shows many error-like warnings to users when certain mod attributes, such as mod version, source, or website are not filled. The following may help reduce the frequency of such warnings.

---

### **Describe the solution you'd like**
I'm working on a FOMOD builder webpage and, as part of doing so, I noticed that Vortex only appears to read one value from `Info.xml`, the mod's name (and, according to #4420, it doesn't do what you'd expect). As part of my research, I also looked into Mod Organizer 2, which appears to read the `Author`, `Website`, `ID` (which MO2 does not appear to actually use, but shares a variable name with the Nexus Mods ID used elsewhere), and `Version` tags as well. Since Vortex stores this metadata, it might help to pull this information from the FOMOD if need be—for instance, when installing mods from not-Nexus. 

After doing some more ~~digging~~ `Ctrl` + `F`ing into Vortex's code, I also found that, in [`extensions/nmm-import-tool/src/views/ImportDialog.tsx`](https://github.com/Nexus-Mods/extension-nmm-import/blob/master/src/views/ImportDialog.tsx), Vortex reads the `Version`, `Id`, and `DownloadId` and, interestingly, Vortex reads `CustomCategoryId` and `CategoryId` in [`extensions/nmm-import-tool/src/util/import.ts`](https://github.com/Nexus-Mods/extension-nmm-import/blob/master/src/util/import.ts). It would seem that part of the tech is already there.

<details>
<summary>Here's a list of tags I would personally like to see properly implemented (I will be making a similar issue over at the MO2 repo):</summary>

Tag | Usage | Attributes
:-: | --- | :-:
`Name` | Can be used as a fallback for the mod's Name, should metadata fetching fail
`Author` | Can be used as a fallback for the mod's Author, should metadata fetching fail
`Uploader` | Can be used as a fallback for the mod's Uploader, should metadata fetching fail. The attribute `website` can be used as the uploader's URL | `website` = *URL*
`ID` | Can be used as the mod's Nexus Mods ID, which can at least help fetch some metadata
`Website` | Can be used as the mod's website. If `ID` is not specified, a Nexus Mods URL could also provide the Mod ID
`Version` | Can be used as  the mod's Version, should metadata fetching fail
`Description` | Can be used as the mod description, should metadata fetching fail | `short` = *STRING*
`Image` | Path to an image (similar to `ModuleConfig.xml`) that can be used as the mod's image, should metadata fetching fail
`FileType` | The File Type, as would be displayed on Nexus Mods. Accepted values would be `MAIN`, `ARCHIVED`, `UPDATE`, `MISCELLANEOUS` and `OPTIONAL`, matching how Vortex stores these values internally.
`CategoryID` | Category ID, matching both how Vortex stores the value internally and how Nexus Mods handles the links
`GameID` | Game ID, as found in file download URLs

<details><summary>Example <code>Info.xml</code> file using these tags:</summary>

```xml
<fomod>
  <Name>Additional Clockwork</Name>
  <Author>BellCube Dev</Author>
  <Uploader website="https://nexusmods.com/users/98340728">BellCubeDev</Uploader>
  <ID>47087</ID>
  <Website>https://www.nexusmods.com/skyrimspecialedition/mods/47087</Website>
  <Version>3.0.0</Version>
  <Description short="Additional Clockwork is a [...] sorting, too)">ommited because it's long...</Description>
  <Image>fomod\images\AdditionalClockwork.png</Image>
  <FileType>UPDATE</FileType>
  <CatrgoryID>78</CatrgoryID> <!-- Immersion  -->
  <GameID>1704</Game> <!-- Skyrim SE -->
</fomod>
```

</details>
</details>

---

### **Describe alternatives you've considered**
This is not strictly necessary. This is more of a convenience for users than anything else (and an excuse for me to spread the Vortex logo over more of my FOMOD builder).

---

### ~~**Additional context**~~

---

If you do end up implementing the above, please let me know (and, if possible, please tell me which tags Vortex reads and how it uses them). I'd love to be able to spread the Vortex name & logo over more of my FOMOD builder.

**Comment by BellCubeDev** [comment]
### Update:
The discussion in the Mod Organizer 2 repository (ModOrganizer2/modorganizer#1695) is possibly trending towards changing the `CategoryID` (and, for consistency, the `GameID`) tags to human-readable strings instead of using the Nexus IDs.

**Comment by TanninOne** [comment]
Tbh I don't think the info.xml file is particularly useful, which is why Vortex barely uses it.
It's just an additional step of work for the author they may miss. E.g. if they release a new version they have to enter the name and version on the site (on Nexus Mods) anyway, having them do it in the info.xml is redundant.

The category or author info they can update at any time on the site without updating+reuploading the fomod.
This means most of the info in the fomod is potentially outdated by the time users download it and if authors wanted to keep it up to date that would just cause a lot of additional traffic for the users and sites, Imagine people redownloading a 3GB mod because the author wanted to change the category...

Vortex identifies mods by their md5 hash and can then request info about the file through an open api. This is not tied to nexusmods.com, anyone can host such a "meta server" and users can put that url into Vortex to make use of that server. If there was demand, we could make this process easier and it could be added into other mod managers, it's not a complex system.
Having a website host meta information is much much more flexible than the info.xml format.

So that would be my suggestion: Forget about info.xml, it may have made sense in time where people downloaded mods on a library pc and then took it home to their not-internet-connected gaming pc on a usb stick.
Instead, help set up an independent server-based archive for mod meta information that can then work for any mod, fomod or not, that doesn't already have its info available through an api (nexusmods.com).

**Comment by BellCubeDev** [comment]
I realize now (for a second time now in this set of issues) that I didn't make it clear that, in all scenarios, the API metadata should override any data from Info.xml. But, you're right. Setting up a meta server would be a much better idea! Now to come up with a good way of doing that...

**Comment by TanninOne** [comment]
@BellCubeDev you can start here: https://github.com/Nexus-Mods/modmeta-db
That repo contains the code that Vortex uses including caching of results and sample code that host the content of the "cache" in a website
