### ISSUE TITLE
proof for TanningOne that Nexus "File Redundancy" is targeting master files.

### ISSUE THREAD

**Issue by TirsiakIngolf** [Nexus-Mods/Vortex#12105]
Imma bout to ruin this dudes entire argument that there ain't no proof that the
"Some mods are redundant" notification doesn't target master files with one image bomb. 
If there doesn't exist an option to suppress "Some mods are redundant" in the near future I honestly think TanningOne should be demoted. 
https://i.imgur.com/T9yIWFn.png 
For fucks sake, give users the option to get rid of the notification permanently if they don't want it. I can even read an excerpt from the mod page: 
*Ahem*
"An Update Of JDegenerate's Color Mod For Vivanto's Flashlight NVSE" 
"Requires: FlashlightNVSE by vivanto" 
Hear that? Requires... Looks like TanningOne should read a book on false positives and false negatives.

**Comment by TirsiakIngolf** [comment]
TanningOne, here's something for you to do your homework on.
1. Research false positives. 
2. research false negatives.
3. Download these:
4. https://www.nexusmods.com/newvegas/mods/39968 
5. ttps://www.nexusmods.com/newvegas/mods/66212 
6. Try to argue with me that these are redundant, go ahead and do what Vortex suggests, I'm sure that'll have FLYING results.

**Comment by Pickysaurus** [comment]
This ticket lacks the context of what you previously discussed, but I've just taken a crack at it. The two mods you installed do indeed have a mod conflicts. I think I can see what you've done. 

Both mods contain `FlashlightNVSE.esp`. This is also the only file in the "LED Edition" update.

If you set the "LED edition" to load before the original mod, that means the `FlashlightNVSE.esp` from the original mod is used instead of the one from the update. As this is the only file from the "LED Edition", it means that there are no files from that mod that actually make it to the data folder as it is fully overwritten by another mod. This triggers the redundant message as it's having no effect on your game and is basically working the same as being disabled.

I believe the desired outcome is for the "LED edition" to overwrite the original, you can do this by changing the rules between the mods so that it loads _after_ the original, rather than before. 

Vortex recommends setting the rule the wrong way around because there's no way to know that this is a replacer ESP from the data the application has, instead it uses a bunch of other factors (such as last edit time) to attempt to give a suggestion on which rule to set.

**Comment by TanninOne** [comment]
Some homework for you:
- learn to read
- don't insult people who can ban you
