### ISSUE TITLE
Vortex stuck on "Preparing Game Settings"

### ISSUE THREAD

**Issue by BorgiaMkUltra** [Nexus-Mods/Vortex#125]
Hello, so I am using version 0.14.1

Vortex freezes whenever I try to activate Skyrim VR. It is stuck on the "Preparing Game Settings" progress bar. I had been using Vortex for the past couple of days with Skyrim VR with no problems. Then I activated Fallout 4 VR and started installing some mods on that game, and when I tried to switch back and activate Skyrim VR, Vortex freezes on the "Preparing Game Settings" progress bar.

**Comment by TanninOne** [comment]
could you attach your vortex.log?

**Comment by BorgiaMkUltra** [comment]
Sure, unfortunately I don't know where that is located lol. What is the file path?

**Comment by BorgiaMkUltra** [comment]
Ah here they are.
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/1893184/vortex.log)
[vortex1.log](https://github.com/Nexus-Mods/Vortex/files/1893185/vortex1.log)
[vortex2.log](https://github.com/Nexus-Mods/Vortex/files/1893186/vortex2.log)
[vortex3.log](https://github.com/Nexus-Mods/Vortex/files/1893187/vortex3.log)
[vortex4.log](https://github.com/Nexus-Mods/Vortex/files/1893188/vortex4.log)

**Comment by BorgiaMkUltra** [comment]
I have also tried uninstalling and reinstalling, and still same thing.

**Comment by TanninOne** [comment]
I believe OneDrive/SkyDrive may be what's causing the issue. The current electron versions (all of them, even the betas) use a node.js version that seems to have some issues with OneDrive.
Basically commands that should work produce error messages even when the parameters are fine, like "EINVAL: invalid argument, stat 'C:\Users\Mk Ultra\SkyDrive\Documents\My Games\Fallout4VR\Fallout4Custom.ini'", I'll go on a limb and assume that path is perfectly valid.

Unfortunately there is little I can do atm since the error is not in our own code, so we have to wait for the fix to be integrated in electron. I can try to work around these issues, which I did in 0.14.0 but as soon as I fix one case, it goes a bit further and then something else breaks.

**Comment by BorgiaMkUltra** [comment]
Oh I see, yeah that's frustrating. I'll try turning off the onedrive backup and see if that solves it.

**Comment by BorgiaMkUltra** [comment]
So I turned off the Onedrive backup and the program is working fine again. That's unfortunate that Onedrive is causing these problems, because it is on by default in windows for the Documents folder. Here's hoping they work this out. And thank you so much for your help, I really appreciate it. I'm really enjoying the program so far.

**Comment by TanninOne** [comment]
It's possible this happens only if the new "onedrive files on-demand" feature (added in the fall creators update) is active, so if you re-enable onedrive but go to settings->files on demand and remove the checkbox, that too may fix the problem.

**Comment by BorgiaMkUltra** [comment]
Ok cool, I'll try that and let you know.

**Comment by TanninOne** [comment]
This _may_ be already fixed since the last update of electron or it will be with the next update. Since we can't do anything about it directly there's no point keeping this issue open.
