### ISSUE TITLE
Blade and sorcery wont open 

### ISSUE THREAD

**Issue by Cyth6870** [Nexus-Mods/Vortex#12649]
**Describe the bug**
When i try to start Blade and Sorcery on my Oculus using Airlink/Link Cable, the game gets stuck on the loading menu, then i opened vortex to see if their was any issues, and then it says "vortex tried to access C:\Users\Riley\Appdats\Roaming\Vortex\plugins\Vortex Extension Update - Blade and Sorcery v0.2.13\info.json but it doesn't exist" and after messing around with managing the game it shows a new error message that says "game version JSON element is missing"

**To Reproduce**
1. Open Vortex for nexus mods
2. If an error message shows at the top, click more
3. click off of it and click on manage for Blade and sorcery when its not working
4. click the new error message and click "more" and then you will see the last part

**Expected behavior**
i thought if i deleted and redownloaded vortex it would allow me to actually open Blade and sorcery but it didn't, now im here

**Screenshots**
![image](https://user-images.githubusercontent.com/110890335/183589916-d753deba-3c08-43f2-923c-8223e2b022a1.png)
![image](https://user-images.githubusercontent.com/110890335/183589979-3b38f200-084f-4bc0-ab4b-59e918cbe500.png)
![image](https://user-images.githubusercontent.com/110890335/183590032-03804661-85e5-4eed-8d70-13dea5561fa5.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.5.13

**Additional context**
Only started happening since the latest version of the U11 update

**Comment by IDCs** [comment]
Hi - first of all the blade and sorcery extension located in your `%appdata%/vortex/plugins` folder is corrupted - close Vortex and browse to that folder I mentioned and delete the Blade and Sorcery extension - start Vortex again and the extension will update to the latest version 0.2.15.

Secondly, any in-game issues (or it failing to load) will be caused by the mods you have installed - not Vortex. Purge your mods and ensure that the game starts up as expected in its vanilla state; if it doesn't re-install the game; if it does, add your mods in batches and try to pinpoint the problematic mod that's causing the game to crash.

Make sure all your mods are targetting the U11 version - as far as I understand it, all mods developed for the older versions of the game will indeed end up crashing your game.

**Comment by Cyth6870** [comment]
Thanks, vortex works now, but now my game is saying sum about mod might be corrupting the game, so i disabled them all and tried again and still wont load and stops me at a loading screen about mod corruption or sum
