### ISSUE TITLE
Dragging files into mod list stopped working in 0.14.1

### ISSUE THREAD

**Issue by Nordomus** [Nexus-Mods/Vortex#127]
Worked fine in 0.14

**Comment by skeezerbean** [comment]
I dragged multiple zip files into my modlist in 0.14.1 by dropping them down to the bottom area where it says "Drop File" and it seemed to work ok here. Just an FYI anyways. This was for Skyrim VR if that makes any difference. It imported and asked to install/enable.

**Comment by Nordomus** [comment]
My luck then, doesn't work for me, even after reinstall.

**Comment by TanninOne** [comment]
I can't think of a reason this would break between 0.14.0 and 0.14.1.
Could you check in the log file if there's anything there?
How doesn't it work? Do you get an error message? Does the border of the dropzone turn green but nothing happens when you release? Or does the dropzone not react at all?

Also, what tool are you dragging from? Windows Explorer? Are you running Vortex and that tool as the same windows user? Not running Vortex as Administrator I hope?
Because you can't drag&drop between tools running as different users.

**Comment by Nordomus** [comment]
Yep you are right, it's because of administrator mode, thanks. I had to turn it on to get rid of errors I was getting constantly afeter I updated Vortex:
![error](https://user-images.githubusercontent.com/25961180/38725743-960225e8-3f08-11e8-83a5-9322ef496d8f.JPG)
Any idea how to get rid of that without running in administrator mode?

**Comment by M4lik** [comment]
You get this error because you've set your mods directory inside of the vortex installation folder. This is the wrong place because of two reasons: you would always have to start vortex as an admin, because otherwise vortex cant write into that directory, and secondly with every update all your mods will be deleted. The current update progress is that vortex completly removes the old installation and installs the new one. So just move your `mods` directory somwhere else (e.g. Documents/VortexMods) and you should be fine :)

**Comment by Nordomus** [comment]
I've changed folder to C:\games\.... and when I try to install mod I still get error about program files...
Also I got this error at startup of Vortex:
![error2](https://user-images.githubusercontent.com/25961180/38731301-0d619860-3f1a-11e8-95ba-fab0085a939e.JPG)

**Comment by TanninOne** [comment]
You managed to encounter a second independent bug. Unfortunately the framework we rely on (Node.js) can't currently deal with a new feature microsoft reacently added to OneDrive called "Files on demand".
The only solution I can offer you for _that_ is to disable files on demand or onedrive entirely or at least not store any game-related files (in this case the game ini files) in the onedrive directory.
I'm not sure when this will be fixed because we're dependent on the node.js people fixing that and then the electron people to integrate the fix.

**Comment by Brenden00777** [comment]
I found a work around for it saying file doesn't exist. Just drag the file from the extractor to desktop when its on desktop then drag in to the file spot on vortex. IDK why it works but worked for me
