### ISSUE TITLE
Vortex 1.6.x crashes on install, incorrectly identifies .Net runtime as problem

### ISSUE THREAD

**Issue by bbrummer** [Nexus-Mods/Vortex#13027]
**Describe the bug**
Vortex crashes and burns on install of any 1.6 version and throws up the new .Net 6.0 exception/install error shown below.

This machine has a clean install of .Net 6.0.8 runtime, the latest available.  I've also downgraded to the older 6.0.6 runtime that Vortex tries to "fix" the problem with, with the same error.

This is _NOT_ a .Net dependency error.  Whatever the "Failure processing application bundle" error is, Vortex is mis-identifying the exception as a .Net library problem.  Using the "Fix" button does nothing of course, because there's no issues with the .Net install to fix.

**To Reproduce**
1. Download Vortex 1.6.x installer
2. Try installing it

**Expected behavior**
Vortex both runs w/o exception and if/when it has an exception, doesn't take the lazy path of trying to blame .Net runtime install issues for its own bugs.

**Screenshots**
![image](https://user-images.githubusercontent.com/7636070/188498521-3602ebb0-574c-4194-b059-1db525c504c7.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.6.* -The entire 1.6 line is affected, tried them all

**Additional context**
This is probably a corrupted configuration in Vortex somewhere actually causing the issue.  But because (see my other bug) Vortex's Uninstall isn't actually capable of cleaning the config out during uninstall, as a user I'm left with no workarounds (short of a complete Windows reinstall to a blank hard drive) and effectively Vortex is now DOA because of it.

**Comment by Pickysaurus** [comment]
Please see the troubleshooting steps in our forum thread here: https://forums.nexusmods.com/index.php?/topic/11865088-microsoft-net-check-failed-vortex-167/

This error appearing is almost always down some kind of weird custom setup.

**Comment by TanninOne** [comment]
@bbrummer Vortex isn't doing its own check whether .NET is installed that could go wrong, it runs a minimal .NET application and then we analyze the error message (if any) we got' The error message you're getting "Failure processing application bundle ..." is atypical, it doesn't say you have no .NET installed, it says the .NET installation is somehow broken or incomplete or quite outdated.

So just to repeat: Your getting this error because your system is not capable of running the most minimal .NET application, you're literally getting an error message **from .NET**.
There is no doubt that your .NET runtime is in fact the problem.

Unfortunately I've not seen this error before and google doesn't have much on it either (except for others also scratching their heads, e.g.: https://techcommunity.microsoft.com/t5/net-runtime/applications-are-not-correctly-detecting-net-desktop-runtime-6-0/m-p/3062143)

One explanation I've seen is that only the 32bit version of the runtime is installed but I'd be surprised if that lead to such an error message. Another possible explanation is that you might have another .NET application installed that is listed in your PATH environment variable that ships with a stripped down/modified/outdated or simply broken .NET runtime.

**Comment by TanninOne** [comment]
closed due to lack of feedback

**Comment by GunMetalBlack** [comment]
I also have the same issue...
