### ISSUE TITLE
Vortex Offers to "Update" Mods by Downgrading

### ISSUE THREAD

**Issue by naqaden** [Nexus-Mods/Vortex#13070]
**Describe the bug**
If a mod in your mods list has a higher version number than what's available on Nexus, Vortex claims an "update" is available.

**To Reproduce**
1. Open a Nexus mod on your mods list.
2. Open its details panel to modify its version number.
3. Increase any number.
4. If Vortex doesn't immediately claim there is an "update," check for updates.

**Expected behavior**
Nothing should happen, since the version number is higher than anything on Nexus. SemVer specs make it easy to determine when a version is higher.

I could understand exceptions for mods failing to follow SemVer, though that's usually a matter of missing missing a patch number. Quick fix: if it fails a SemVer check, add ".0" and check again. If it still fails, give up and assume the mod should match whatever's newest on Nexus (like now).

While an edge case, a real use case is mod authors and beta testers with access to higher version mods. More specifically in this test case though, the mod's file ID still matches what's current on Nexus, so on that account alone, Vortex should know there's no update.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex v1.6.8

**Comment by TanninOne** [comment]
Vortex doesn't exist in isolation, it is built to work with nexusmods.com which doesn't enforce any specific versioning scheme.
Depending on mod author, a version of 1.1 could be newer or older than 1.02, 1.1 could be newer or older than 1.1a. The old version could be named "1.1.2" and the new one "Final".
If Vortex could rely on version numbers to be in a consistent scheme then yes, we could determine if one mod is newer or older than another but the way it is we usually have to assume that the current main file on a mod page is the newest version and whatever you have on disk, if it has a different file id, must be older **OR** the installed version is newer but was redacted because of a bug for example.

**Comment by naqaden** [comment]
Fair enough about relying on authors' version numbers.

> whatever you have on disk, if it has a different file id, must be older

The steps to reproduce result in a mod with the same file ID, yet Vortex claims there is an update solely because of the version mismatch, even if the versions follow SemVer. Granted this would not happen with the mod authors & beta testers scenario.

Now I'm wondering why Vortex bothers validating SemVer for the user. I figured if a mod adheres to SemVer, that'd allow Vortex to be smarter with it, which is valuable for the user to know. But you're right, one version of a mod adhering to SemVer doesn't mean any previous or later version do. I guess it's just a nice educational highlight.

**Comment by TanninOne** [comment]
> The steps to reproduce result in a mod with the same file ID, yet Vortex claims there is an update solely because of the version mismatch, even if the versions follow SemVer. 

Again: We can't know if the mod author follows semantic versioning, we can't assume that if a version number consists of 3 numbers separated by dots that it's semantic versioning.

> Now I'm wondering why Vortex bothers validating SemVer for the user.

Because we _want_ to push users to use a consistent versioning scheme. The site is/was supposed to also incentivize mod authors to use it (and then be locked into that versioning scheme) but on that end other projects had priority.
If the api had a flag to say "this mod uses semantic versioning" and then the site doesn't let the author put in anything invalid then Vortex could provide more robust update checks for that mod.
