### ISSUE TITLE
1-byte binary patch is "too large" to be patched for small files.

### ISSUE THREAD

**Issue by Rattledagger** [Nexus-Mods/Vortex#13081]
From #13069 (number 3)

The ESL-flagging of plugins in Skyrim Special Edition is a 1-byte binary difference. With the 20% size of binary patch this means any esp larger than 5 bytes should be possible to ESL-flag, but for small esp you'll often get "We don't allow edits that exceeds a certain percentage of the original file size."

Just because patch itself uses around 140 bytes to indicate the location of the 1-byte difference shouldn't block creating the 1-byte patch.

Work-around, if original file smaller than example 10 KB allow binary patch regardless of % patched. It's possible the cut-off limit should be larger than 10 KB to also handle other types of small files.

**Comment by TanninOne** [comment]
"20%" means the patch file can't be larger than 20% of the original file, we have no way of reliably knowing how large the "payload" of a binary patch is.

10kb of data could still be copyrighted content, there is no size limit under which we can go "no, this can't be copyrighted so we don't have to protect against curators stealing stuff".

1.6.9 does however subtract a hard-coded size (130 bytes) that is roughly the overhead of a single binary sequence of changes. That should allow for these 1-byte flag changes on even the smallest esps (since esps too have overhead).
