### ISSUE TITLE
Fallout 4 extension error

### ISSUE THREAD

**Issue by ShreddedNinja** [Nexus-Mods/Vortex#13322]
Failed to load: Cannot find module 'bluebird'
Require stack:
- F:\ampa_migra\C\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-fallout4\index.js
- F:\ampa_migra\C\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- F:\ampa_migra\C\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html

I don't have any Black Tree Gaming Ltd folders and don't know what to download to get all this stuff. I haven't had this problem with any other game I've modded.

**Comment by TanninOne** [comment]
@ShreddedNinja bluebird is a core library we use everywhere, it can't be missing, nor can the fallout4 extension be incapable of importing it with only you noticing.

Based on how that stack looks I assume you moved your program files directory to drive F and instead of reconfiguring windows to correctly use that new location you used a junction point (aka directory soft link) to make software think program files is still on C.
The backend we use (node.js) doesn't work like that, we've encountered this problem in the past. It's a known issue with node.js but it hasn't been fixed in years so I wouldn't hold my breath.

Reinstall Vortex with the "custom install location" installer and install it to a normal directory.

**Comment by ShreddedNinja** [comment]
> 

I have Program Files in both C and F, the one in F only has a single empty folder but the one in C still has everything you would expect to be in the folder. I also don't speak computer well and have no idea what a normal directory would be. I still don't know what to do about bluebird though I appreciate you being the only one that has tried to help me in the last two days.

**Comment by TanninOne** [comment]
look at the stack you posted:
> F:\ampa_migra\C\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
> C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html

it's taking two files, both part of Vortex, from two different locations. There is definitively something up with your setup, if you didn't do that, someone else or some tool did it for you.

When I said "install to a normal directory" I meant "a directory that is not getting redirected". Why not use "f:\vortex" for example.
