### ISSUE TITLE
Option to mirror Deploy Order and Load Order

### ISSUE THREAD

**Issue by SatanicGeek** [Nexus-Mods/Vortex#13513]
Hello,

I just installed Skyrim SE/AE and took a few hours to choose ~150 mods, check the compatibility and versions, add patches before downloading everything in Vortex and sort them to have a good deploy order.

Once I've done that, I launched the game and started a new save to test everything (then add/update/delete mods for better result). 

Now, I got an issue. I need to create a Load Order correctly because the one LOOT (integrated tool in Vortex) suggests me doesn't suit all my mods.
LOOT puts automatically mod A before B but I can't see mod A in the game because mod B overwrite some files. By reading mod A and B description, mod B should be loaded BEFORE mod A to work properly. 

I already sorted my mods in the "Mods" section in Vortex but now I have to do it again in the "Plugins" section. I have around 90 mods to check (the rest is only textures so no need to load in a certain order) but I don't want to do it manually.

I use a lot of mods to give games (specially old games like Skyrim or Fallout) a second life and I play those games for a long period of time before moving to something else or changing mods for something new but I always struggle and get frustrated when the time of doing the Deploy Order and then the Load Order all by hand comes because LOOT can't do it alone like I actually need. 

The option that could be, in my humble opinion, a useful feature is a button to mirror the Load Order on the Deploy Order.

For example, I download and deploy my mods in the section "Mods" and then I go to the "Plugins" section and I click a button called "Mirror the Deploy Order" to get a Load Order on the base of what I already have done instead of taking more time to check everything and create new rules. 

Even after, if I change the Deploy Order, the button will be helpful to update the Load Order and will help people making their dream game without having to play around in Vortex for hours because of two orders. 

Not everyone needs this feature but i'm sur that various actual games but also futur games have this logic and requires, in Vortex, to create a Deploy AND a Load Order.

This button could be anywhere but I'm sur a lot of people who heavily mods their games (like me) will be more than happy to have this option to at least have a base to work with. 

I don't know I was clear enough and I'm sorry for my English. I hope you understand the request but more importantly the need and the reason behind that feature.

Best regards

**Comment by TanninOne** [comment]
I don't see a robust way of doing this.
LOOT has a bunch of implicit rules it sorts by (some are well known, like "regular plugins can not load before masters", others are "magic").
Vortex doesn't have access to those rules, we just get a sorted list from LOOT, we don't know if there is an important reason behind any specific ordering.
If there was exactly one plugin in every mod we could still try to replicate the load order on the mods list by completely disabling manual ordering of mods but even if that was desirable, it's not practical.
If modA contains pluginA.esp and pluginB.esp and then modB contains pluginC.esp
and loot generates the order "pluginA.esp -> pluginC.esp -> pluginB.esp" - what mod order do we apply? does modA go before or after modB?
Going the other way would be even worse because LOOT has much more information to go on to generate a sensible order, including information from the community.

No offense, but in my experience users vastly underestimate the value of the ordering LOOT applies and overestimate their ability to manually provide a good load order. This doesn't have to be true for every single user but it is true for the most. 
Plugin order customization should be very punctual, most users who want to completely modify their load order do that under false assumptions of how load ordering work. The tools we have for such punctual changes are sufficient, if you actually do want more control, disable automatic ordering and use a different tool (e.g. the load ordering integrated with the game).

**Comment by SatanicGeek** [comment]
The feature could replace the auto-sort from LOOT but it's a confort-feature to help people.
But I understand your comment and I agree.
It was an idea I wanted to submit ^^

Thank you for your answer !
