### ISSUE TITLE
Collection does not show up in Workspace

### ISSUE THREAD

**Issue by whoot** [Nexus-Mods/Vortex#13566]
I created a collection and switched to new hardware, so I had to install Vortex again.
However, my collection does not show up in the Collections -> Workspace tab anymore.

To answer some questions beforehand:
- I am logged in with the profile/user that I used to create the collection
- I waited a few minutes, but the collection does not show up
- I added the collection to my profile by downloading it from https://next.nexusmods.com, but Vortex does not recognize that I am the owner/creator. Therefore it only shows up in the Collections tab, but not in the Workspace tab, meaning I am unable to edit it.
- I also tried to import a config backup from my old Vortex installation, but this just adds the collection as I would download it from https://next.nexusmods.com

**Comment by TanninOne** [comment]
That is the expected behavior in 1.6, the workshop page only shows collection you have locally.
You can install the collection and then "clone" it to the workshop to continue editing it.

**Comment by whoot** [comment]
Thanks for your fast response.
WIll this result a new collection or will I be able to edit my own collection?

**Comment by TanninOne** [comment]
@whoot If you clone your own collection and upload a change, that will update your existing collection on the site, it will *not* generate a new page.

But keep an eye on the UI. The option to clone is available on any collection, not just your own and if you were to clone someone elses (or Vortex thinks that you are, e.g. because you have multiple accounts and Vortex is logged in with the wrong one) _that_ will create a new collection.
If everything is correct, Vortex will explicitly say "You curated this collection" on the dialog when you start installing it. That tells you that Vortex has correctly identified it as your own collection.
