### ISSUE TITLE
Vortex Glitching and Extremely Slow Download Speed 

### ISSUE THREAD

**Issue by Codecooo** [Nexus-Mods/Vortex#13810]
**Describe the bug**
I installed Vortex in my PC, after I opened it Vortex started glitching and slow download speed not only on Vortex but also on Nexus Mods website after the maintenance. The Vortex new update fix nothing and the slow download speed has been happening for 3 days.

**To Reproduce**
1. Install Vortex
2. Opens it and start click on something 
3. Congrats now Vortex is glitching

**Expected behavior**
Well, I expected a clean and non glitching Vortex  and a normal download speed

**Screenshots**
I'll provide screenshots once I could do so.

**Platform (please complete the following information):**
 - OS:  Windows 10 Home 64-bit 22H2
 - Vortex Version 1.7.4

**Additional context**
I've tried to fix this by reinstalling Vortex and restarting my PC but it changes nothing.

**Comment by TanninOne** [comment]
This is the Vortex issue tracker, slow downloads are caused by the site or your own internet connection. So - sorry but you're wrong here.
And whatever you mean by "started glitching" is way too vague.

**Comment by TanninOne** [comment]
As I said before: slow downloads are not caused by Vortex. There may be some issue with your own network connection, your ISP or with the download server (by default Nexus Mods routes you to the geographically closest server, if that server is overloaded you might get crap download speeds even while other users are downloading fine). 
The best thing you can do about that is follow this guide: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
and if it does in fact lead to a problem with the servers, make sure to report it to the support staff for the page.

Regarding the graphical glitches, this is caused by global graphics settings in your driver control panel (I suspect you have a nvidia card so "NVIDIA control panel"  -> Manage 3D settings. You should leave the global settings there on default/application controlled and make customizations for individual games.
If you don't want to do that you can go to settings->interface in Vortex and turn off "Enable GPU acceleration" but that will make the UI less responsive.
