### ISSUE TITLE
Suggestion: Other Devices as Valid File Locations

### ISSUE THREAD

**Issue by EpicGamerNexus** [Nexus-Mods/Vortex#14068]
Allow other devices to be used as a valid file location. This will allow for many more games on the Nexus platform.

**Comment by TanninOne** [comment]
@EpicGamerNexus I don't know what you're talking about. What devices are currently not "valid file locations"? And which games can't be on Nexus (???) because of that?

**Comment by EpicGamerNexus** [comment]
Sorry, I just re-read what I said, what I meant was that when you link a mobile device to your computer and allow the computer access to the device's files, Vortex isn't able to use it as a directory for a game, instead will say "Invalid file path." or something similar. And I meant that it would allow more games to be possible to work with Vortex.

**Comment by TanninOne** [comment]
I'm still not certain what the issue is, an external drive should work fine as long as it's formatted NTFS, with exFat you're limited to move deployment.

If you get an error message, please post the full and exact error message, screenshot if you need. I can't investigate "or something similar" unless I already know about the issue - which you shouldn't assume. If I knew about something and it was easy to fix I'd already done it.
