### ISSUE TITLE
MOD Download Failed

### ISSUE THREAD

**Issue by ZzNoah** [Nexus-Mods/Vortex#14062]
**Error**
Certificate validation failed
Encountered an invalid SSL certificate. If this happens on a network connection to a server that has a proper certificate (like the Nexus Mods API) it may indicate a significant security issue in your system.

**Platform:**
 - OS: Windows 11
 - Vortex Version 1.7.8

**Comment by TanninOne** [comment]
What the error message says.
The Nexus Mods api sends a valid certificate. If Vortex receives an invalid certificate, that means your network traffic is being manipulated.
This is often the case temporarily if the ISP, or another service provider like Cloudflare is having trouble.
If it's not temporary it could be your firewall or AV protection having expired while also being shit.
Otherwise you may indeed be the target of malware hijacking your traffic and hoping software won't verify certificates.
