### ISSUE TITLE
Aws::S3::Errors::NotFound

### ISSUE THREAD

**Issue by bongodoctor** [Nexus-Mods/Vortex#14126]
I keep getting this error when uploading/updating a specific collection - it contains the same files/mods as other collections that have successfully been updated...
[network.log](https://github.com/Nexus-Mods/Vortex/files/10979933/network.log)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/10979934/vortex.log)

**Comment by bongodoctor** [comment]
Ok done more testing - this is happening with other collections as well - so it isn't specific to one collection - was able to update an SE collection which is very small - maybe it is to do with the size of the collections in terms of mods and or bundled files?

**Comment by TanninOne** [comment]
This is a server error. The log contains additional information:
```
Wed, 15 Mar 2023 12:44:53 GMT - debug: uploading file targetUrl=https://nexus-collections-temp.nexusmods.com/uploads/..., dataSize=3045797073
Wed, 15 Mar 2023 12:44:53 GMT - debug: upload complete targetUrl=https://nexus-collections-temp.nexusmods.com/uploads/..., dataSize=3045797073, statusCode=413, elapsed=82
Wed, 15 Mar 2023 12:45:10 GMT - warn: error notification message=The server rejected this collection
```

The status code 413 means "Content Too Large"

So, as you suspected, this is due to the collection size (3GB in this case). The server outright refuses the upload instantly, implying there is a limit set on the server side.
I'm not aware that there is an (intentional) cap though, you might want to report this to the website (https://github.com/Nexus-Mods/web-issues/issues)

**Comment by bongodoctor** [comment]
Thanks for clarification - what is weird is that another collection that is larger than the one I was trying to upload did successfully upload...

**Comment by TanninOne** [comment]
@bongodoctor As far as I understood it the configuration on the backend was changed and that caused the file cap whereas collections uploaded earlier were fine.
I didn't know about that configuration change or I would have been more confident in what the cause was.
