### ISSUE TITLE
Bug Report: Load Order not reflecting Deploy Order

### ISSUE THREAD

**Issue by Drakah** [Nexus-Mods/Vortex#14211]
I went to "Load Order" and dragged to where I wanted them to be and "deploy" the order.
However, the "Mods" list is unchanged under the "Deploy Order".
The actual "~mods" filenames are also unchanged.
Exiting Vortex and reloading did nothing.

Please see screenshots. Tested on March 4, 2023

Windows 10
Vortex Version 1.7.8
![Screenshot 2023-04-02 104854](https://user-images.githubusercontent.com/35508294/229957902-95c52022-2418-42f0-ab16-603586258e9b.jpg)
![Screenshot 2023-04-02 104943](https://user-images.githubusercontent.com/35508294/229957916-f7dd9057-fb7b-4f07-b752-c882a6d04d46.jpg)

**Comment by TanninOne** [comment]
The reason load order and deploy order are different words and are on different screens is because they are different things, one does not affect the other.

The deploy order is the order in which files get deployed on the filesystem, it's the non-destructive alternative to extracting files and winrar telling you "the file x already exists, do you want to replace it".

The load order controls the order in which the game loads the mods, the effect of which is game-specific.

In the case of this game, you will probably not see two mods replacing the same file as each mod is in its own directory so the deploy order is probably irrelevant.
The game has no special mechanism to control load order, it just loads the mods alphabetically. That's why the load order management in Vortex adds those AAA, AAB, ... prefixes to the mod directories so you can force the alphabetic order.
