### ISSUE TITLE
Mods having 50/50 chance of downloading or not

### ISSUE THREAD

**Issue by Noomu** [Nexus-Mods/Vortex#14318]
That's as plain as it is, suuuuper annoying and i don't know how to bypass it

![image](https://github.com/Nexus-Mods/Vortex/assets/123291735/9627e2db-e4f0-4196-b934-9da46b36464a)

Windows 11
Most recent Vortex Build

**Comment by TanninOne** [comment]
There is no actionable information here, all I can see is that you have corrupted archives and I can assure you that most users do not get this 50% of the time.
The files could be corrupted because of a bad internet connection, because of a virus on your system, some other broken or malicious software, because of a disk fault, ...
If you had attached a log that _might_ give us a better idea but it also might not.
