### ISSUE TITLE
Game Extension not loaded (Skyrim Special Edition) / Invalid game extension: should have required property 'requiredFiles'

### ISSUE THREAD

**Issue by Enesore** [Nexus-Mods/Vortex#14399]
Happens on every Vortex 1.8.5 launch. I do not have Skyrim SE installed.

[vortex.log](https://github.com/Nexus-Mods/Vortex/files/11743781/vortex.log)

**Comment by kelerena** [comment]
I have a similar problem
The only way I could achieve it was by making Steam my primary instead of SKSE.
Could this cause the problem? Also, I reinstalled the vortex, but it's still not good.



/Facepalm/
Problem solved, I deleted the folder C:\Users\xxxx\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Skyrim_ Special Edition v1.0.4

**Comment by Kherosen** [comment]
Same issue at your same time. I was installing some collections for skyrim AE and everything was fine, then all of a sudden it collapsed lmao. I tried to solve it by repairing skyrim trough steam, but didn't work... then i tried to reinstall Vortex, run it both normally and as admin, but dodn't work. i also tried to delete the extensions in vortex regarding skyrim, but didn't work either... not sure why it happened and not sure how to solve it... still trying tho, if i manage to solve it i'll post here

**Comment by Str1spectre** [comment]
Same problem here
 error: Failed to install the extension "Game: Skyrim: special edition" from "github.com"

**Comment by Enesore** [comment]
This appears to be resolved now.

**Comment by Kherosen** [comment]
> This appears to be resolved now.

What did you do to solve the issue on your side?
