### ISSUE TITLE
Implement portable installation option

### ISSUE THREAD

**Issue by ExE-Boss** [Nexus-Mods/Vortex#14642]
Instead of storing the data in <code><var title="Using the PowerShell environment variable syntax">$env:appdata</var>/Vortex</code>, a portable installation would store all the data in the installation directory (ex. an external drive).

**Comment by modderchris** [comment]
agreed, portable installs are REQUIRED, I have a laptop AND a desktop, in
order to play my saves ACROSS devices I would have to MANUALLY edit BOTH
installs, a much simpler and elegant solution is to expose the hardcoded
directories to editing, even if it is a config doc that most people never
edit
I am going to set up my games to mod-sync to an external SSD someday, even
if I have to symlink every single directory vortex stores data in(far too
many if you ask me) just to ensure it thinks it is the same PC and install
sadly currently I simply do not have an acceptable drive or money to do so
yet, but someday I WILL be doing a 100% PORTABLE install(besides the stupid
steam "game not installed" stuff which I will bypass by using a script that
checks if steam.exe is running and launches if needed before triggering the
F4SE or SKSE launchers
I already have depotdownloader scripts to force verify to OLDER versions of
the modded games when steam decides to update and not allow users to easily
say "no this game needs to stay at the old version and doesn't have any
justification to force all users to the same version"

**Comment by festro** [comment]
Great if this 
"The Nexus Mods App will be a ground-up reimagining of what we (and you) want our mod manager to be, building on the lessons learnt from Vortex and NMM before that." 
is true than make sure to add a portable install option to the next iteration as this is clearly a wanted feature, otherwise is will come off as corporate PR crap and serve as another reason to drive users and modders away from the platform, I think enough damage was done to this platform with that "collections" fiasco.

**Comment by IrinaIsha** [comment]
Oh cool, NexusMods is wasting everyone's time with a meaningless rebrand instead of providing the features the community wants. Again. Here's hoping someone makes a mod management platform that isn't corporate crap sometime soon.

**Comment by modderchris** [comment]
> Oh cool, NexusMods is wasting everyone's time with a meaningless rebrand instead of providing the features the community wants. Again. Here's hoping someone makes a mod management platform that isn't corporate crap sometime soon.

kinda expected these days, pretty much EVERY company is to full of brain dead YEC nutjobs who can't connect teh "people hate us" to the "because of the shit we are going to keep doing after we rebrand to get rid of the hate"

same with religion in the US government, a literal violation of the founding laws of our government is being violated, and ironically the very things designed in the constitution to protect us from the very religious persecution that lead to our founding are being called "unconstitutional"
yes, people literally agree that "what makes america what it is" is "against what america is" and the very same people who say stuff like that say the earth is 6000 years old, in literal human years despite the same scripture they use saying basically "dates are not literal, don't treat them as accurate"

**Comment by IrinaIsha** [comment]
> kinda expected these days, pretty much EVERY company is to full of brain dead YEC nutjobs who can't connect teh "people hate us" to the "because of the shit we are going to keep doing after we rebrand to get rid of the hate"
On the bright side, every time a useful tool gets infested with corporate garbage, there ends up being members of the community who have the skill and desire to make an alternative that usually ends up being excellent.

Speaking of which, to anyone else who ended up here from Google like I did: Turns out Mod Organizer 2 is still alive and well despite NexusMods acting like it is obsolete, and Mod Organizer 2 is made fully and easily portable by selecting the "portable installation" option during install. Good luck all.

**Comment by modderchris** [comment]
> > kinda expected these days, pretty much EVERY company is to full of brain dead YEC nutjobs who can't connect teh "people hate us" to the "because of the shit we are going to keep doing after we rebrand to get rid of the hate"
> 
> On the bright side, every time a useful tool gets infested with corporate garbage, there ends up being members of the community who have the skill and desire to make an alternative that usually ends up being excellent.
> 
> Speaking of which, to anyone else who ended up here from Google like I did: Turns out Mod Organizer 2 is still alive and well despite NexusMods acting like it is obsolete, and Mod Organizer 2 is made fully and easily portable by selecting the "portable installation" option during install. Good luck all.
> 
> (Edit: Accidentally lumped my first sentence in with the quote lol good job me)

so do you know if MO2 can hook vortex download links? would be great if it acted like vortex in that new updates and downloads get hooked via some form of add-on and maybe even LL files if you are open-source

**Comment by IrinaIsha** [comment]
> so do you know if MO2 can hook vortex download links? would be great if it acted like vortex in that new updates and downloads get hooked via some form of add-on and maybe even LL files if you are open-source

I don't really understand much of this to be honest, I'm not very experienced with Skyrim modding, but MO2 seems to handle download links perfectly out of the box - for example clicking "Download with Mod Manager" links from NexusMods opens MO2 and download the mod through it. Good luck!

**Comment by modderchris** [comment]
> > so do you know if MO2 can hook vortex download links? would be great if it acted like vortex in that new updates and downloads get hooked via some form of add-on and maybe even LL files if you are open-source
> 
> I don't really understand much of this to be honest, I'm not very experienced with Skyrim modding, but MO2 seems to handle download links perfectly out of the box - for example clicking "Download with Mod Manager" links from NexusMods opens MO2 and download the mod through it. Good luck!

so it does do exactly what I want, and it is not as frequently broken as vortex was(one time a game that is among the most popular to mod(fallout 4) just vanished for over a week as a valid game to mod)

**Comment by ElektroStudios** [comment]
`--shared` parameter should also be added when using `--user-data`.

Full instructions on how to launch Vortex in "portable" mode are specified in the following Markdown file:

https://www.nexusmods.com/skyrimspecialedition/mods/47390?tab=files&file_id=192954

I found it very useful.

**Comment by RaXorX** [comment]
```
; -----------------------------------------
; Portable Vortex Launcher Script
; -----------------------------------------

!define APP_NAME "Vortex Portable"
!define EXE_NAME "vortex.exe"
!define DATA_DIR "vortex_data"

Name "${APP_NAME}"
OutFile "Vortex Launcher.exe"
;Icon "vortex.ico" ; Optional: Add an icon file in the same folder if you have one
SilentInstall silent ; This makes the launcher invisible/instant

Section "Main"
    ; 1. Get the current directory of the launcher
    InitPluginsDir
    
    ; 2. Define the path for User Data relative to the launcher
    StrCpy $1 "$EXEDIR\${DATA_DIR}"
    
    ; 3. Check if vortex.exe actually exists in the root
    IfFileExists "$EXEDIR\${EXE_NAME}" +3
        MessageBox MB_OK|MB_ICONSTOP "Error: ${EXE_NAME} not found in $EXEDIR"
        Quit

    ; 4. Execute Vortex with the required flags
    ; --shared: Ensures portable behavior
    ; --user-data: Points to our local folder
    Exec '"$EXEDIR\${EXE_NAME}" --shared --user-data "$1"'

SectionEnd
```

Created a NSIS portable launcher script. Just compile it using NSIS, drop it in vortex folder (you can use 7-zip on the exe file, which is already using nsis script in the first place to install it - extract vortex application files from there) and just use the launcher to open it in Portable Mode. Or use attached compiled file.
