### ISSUE TITLE
does not match the redirection URI used in the authorization request, or was issued to another client

### ISSUE THREAD

**Issue by OldGamerDarthyTvOfficial** [Nexus-Mods/Vortex#15046]
Hi, i try to login with Vortex but: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. 

:(

**Comment by IDCs** [comment]
Hi there @OldGamerDarthyTvOfficial

I'm afraid that any certificate issue which you may encounter is generally down to the routing done by your ISP. Alternatively it could be caused by an intermediate application (Anti-Virus) which intercepts and modifies your login packets. Regardless we can't help you on our end, sorry :(
