### ISSUE TITLE
Install problem with document folder (yes I already followed the fix, it didn't work)

### ISSUE THREAD

**Issue by mischaphr33k** [Nexus-Mods/Vortex#15308]
I am trying to install vortex. I downloaded the installer into the downloads folder on my computer. I didn't change anything during the install process, just let it go with the defaults. Then I got the 'your "my documents" folder is missing or misconfigured' error.

I went to the website and followed the fix. Twice. My 'my documents' folder is Not the problem here. I keep getting the error and at this point I don't know what else to do. Can someone give some advice on an alternative fix or tell me what might be going on?

**Comment by IDCs** [comment]
Hi there!

I'm afraid that system mis-configuration is beyond something we can debug for you. Try opening inserting `%USERPROFILE%/Documents` in a file explorer window and see if your system is able to resolve the correct path. If it's not, that's a clear indication that your system-wide environment variables are returning erroneous values.

I'm not sure if this can be fixed by simply repairing your Windows installation, you might have to re-install Windows completely.
