### ISSUE TITLE
bms error lego star wars skywalker saga

### ISSUE THREAD

**Issue by juancagd** [Nexus-Mods/Vortex#15374]
--------------------------------------
- enter in folder C:\Program Files (x86)\Steam\steamapps\common\LEGO Star Wars - The Skywalker Saga
- open input file C:\Program Files (x86)\Steam\steamapps\common\LEGO Star Wars - The Skywalker Saga\GAME.hdr

Error: incomplete input file 0: C:\Program Files (x86)\Steam\steamapps\common\LEGO Star Wars - The Skywalker Saga\GAME.DAT
       Can't read 4 bytes from offset 0a00000043c4c246.
       Anyway don't worry, it's possible that the BMS script has been written
       to exit in this way if it's reached the end of the archive so check it
       or contact its author or verify that all the files have been extracted.
       Please check the following coverage information to know if it's ok.

  coverage file 0     0%   4202769    4064897269 . offset 0a00000043c4c246

Last script line before the error or that produced the error:
  365 getdstring SIGN 4
  coverage file 0     0%   4202769    4064897269 . offset 0a00000043c4c246
  coverage file -1   65%   2759027    4202741    . offset 00000000002abcbc

Press ENTER or close the window to quit

**Comment by minecraftplayer101010** [comment]
I have the exact same issue and it says the same thing. I hope somebody figures out how to fix this.

**Comment by IDCs** [comment]
Hi there @minecraftplayer101010 @juancagd

I wasn't even aware that there is a Vortex extension for any of the Lego Star Wars games. This is something you should report to the author of the extension (but since I don't know who is distributing that extension, I'm not sure who is the main contact for it 🤷)

The issue appears to be caused by a corrupt GAME.DAT file - try verifying your game files through the game extension and see if that helps.

**Comment by xmusjackson** [comment]
Since this appeared at the top of google when searching for a solution, I figured I'd share that here, if allowed. (I can delete this comment if not)

The new DAT files use a new compression algorithm (oodle) for some files and a slightly new format for the offsets.
A fixed script can be found here: https://github.com/xmusjackson/ttgames-quickbms/raw/main/ttgames.bms

**Comment by minecraftplayer101010** [comment]
@xmusjackson How do I download the file? It is just lines of code.
