### ISSUE TITLE
Node Mod Map

### ISSUE THREAD

**Issue by FjellrevG434** [Nexus-Mods/Vortex#15377]
**Is your feature request related to a problem? Please describe.**
I have seen node map in cycles resolving and manage groups. So I thought that it was a part of some menu but it is not.

**Describe the solution you'd like**
I would like to have button on mods and plugins page "Node Mod Map". This could be a node map that works similar to that one in Obsidian(Note app). So all mods' relations could be seen visualy from one place and not simply long and boring list of Manage rules.

**Additional context**
It woul as well be a good thing to make filters for relationless mods so the are not seen.

**Comment by IDCs** [comment]
Hi there - your report does not include sufficient information for us to extract anything actionable. We will forward your suggestion to the NMA team which will supersede Vortex's capabilities, but I'd recommend offering a visual explanation of what you expect the mod manager to do so that we get a better picture of whether it's already supported or a future enhancement.
