### ISSUE TITLE
BG3 - LSLib fails to read PAK files without .NET 8 installed

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15391]
**Describe the bug**

LSLib updated to 1.19.4 and requires the [.NET 8 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.3-windows-x64-installer) to be installed. Vortex core only requires .NET 6. When trying to read PAK files, during deployment and if not cached, error pops up saying Failed to read PAK file.

**To Reproduce**

1. Remove vortex state (so that the cache is wiped).
2. Start fresh management of BG3
3. Latest LSLib (1.19.4) should auto download
4. Install mods\collection
5. During deploy, red error notification will show Failed to Read PAK

**Expected behavior**

LSLib to read PAK correct

**Screenshots**

![image](https://github.com/Nexus-Mods/Vortex/assets/26166085/346383f8-aea6-4a07-94fe-e44bbbf62ddc)

![image](https://github.com/Nexus-Mods/Vortex/assets/26166085/c0b64224-b0db-4d06-8639-30d3602cb7fe)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by noahm1216** [comment]
Hello! I still have this issue after trying to create a brand new profile. 
Win10
Up-To-Date
Latest .NET & BG3 & Vortex as of 07/04/2024

- BG3 + Vortex was working fine less than 1 week ago (none of these issues and 40+ mods)
- Open Vortex today and create a new profile (try turning on 1 mod)
- Try creating my first collection following the website's instructions on Nexus mods
- Unable to fully commit due to "Failed to upload to API"
- Signed out, --> closed Vortext --> sign in through authentification
- Still unable to load profile, just trying to load mods
- "Failed load order operation" (see attached log and screenshots)
- Tried re-downloading: .NET8 --> Restarted Computer --> LSLIB 1.19.5 --> Still have issue
-  Relocating files to fresh new H: Drive Folders (next to old )

![image](https://github.com/Nexus-Mods/Vortex/assets/16135831/a100b6f4-d16c-4668-974d-78232fe69c4b)
![image](https://github.com/Nexus-Mods/Vortex/assets/16135831/93c9025d-f8c6-45ec-adaf-86cf7bba03a4)


[Failed Load Order Operations.txt](https://github.com/user-attachments/files/16103922/Failed.Load.Order.Operations.txt)
