### ISSUE TITLE
[StardewValley] Updating any mod wipes the mod's config

### ISSUE THREAD

**Issue by SoraHjort** [Nexus-Mods/Vortex#15419]
**Describe the bug**
When ever you update a mod in Stardew Valley via Vortex, it will delete the config.json file that is within the mod's folder.
Which means you have to reset the config options every time you install an update.

**To Reproduce**
1. See a mod that needs updating
2. Update the mod
3. Now the config file is gone

**Expected behavior**
It should not be deleting the config files unless the updated mod specifically has a replacement file.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.10.8

**Additional context and info**
I would not think it'd be related but just on the off chance it comes up, Deployment Method is set to Move.

The wiping of config files have happened so much that I ended up with a powershell script that I run prior to doing updates that just backups every json file so that if I notice something changed I can just revert. But it's still quite annoying to have to do that.

If this is looked into to be fixed, the process can't also simply be setup to ignore config.json files, due to mods using sub directories to store additional farm/save file specific config files. Like the Happy Birthday mod stores it's per save info in the data folder with unique number IDs (the seed maybe? never looked into it) as the file name for the json file.

I would think idealy the method to go about it would be to see what files were in the pre-update archive to see which files have been procedurally generated (like the config files tend to be) and remove those before applying the update.

**Comment by oliverrook** [comment]
I can vouch for this. It is incredibly annoying

**Comment by IDCs** [comment]
Hey there - @oliverrook, @SoraHjort - would you be willing to help us test an improvement which we hope will fix this issue?

We implemented an opt-in "configuration mod" functionality which intends to keep track of the `config.json` files for all mods located inside the game's mods folder. That way, if you re-install or update a mod, your configuration file will remain intact.

<img width="645" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/d2611fdd-c88c-49e5-927f-cc82e8e79d66">

If you do opt to help us, we will ofc ensure that no damage is done to your setup.

Some things to note:
* Vortex creates a snapshot of a game's directory after each deployment event.
* Each deployment event will execute a snapshot comparison to detect new files, this is how Vortex will pick up newly generated config.json files unless the manual "Sync Configuration Mod" button is pressed.
* Disabling/removing the config mod will revert the config.json files to the appropriate mods.
* This functionality is toggleable through the settings page.

**Comment by oliverrook** [comment]
I would be willing to help test this, yes.

**Comment by insomnious** [comment]
@IDCs Wrap up a 0.3.0 archive to start sending and testing

**Comment by IDCs** [comment]
Hey @oliverrook,

Apologies for not responding sooner - we get so many github notifications, it's possible for us to miss ticket activity unless you tag us like my colleague did above.

Please find version 0.3.0 of the SDV extension below.
[game-stardewvalley-0.3.0.zip](https://github.com/Nexus-Mods/Vortex/files/15247967/game-stardewvalley-0.3.0.zip)

I would prefer being present when you test the extension if possible, so that we can debug any issues that may come up during your tests, but it's really up to you. Just send me a friend request on Discord (nagev_)

## Prep/Backup
Before we do anything we need to backup your config files and Vortex's state.

* For the state, open Vortex and go to the Settings Page -> Workarounds Tab -> Click on "Create backup" and save the state backup .json file somewhere safe.
* If you have space to spare - I would backup your entire staging folder to ensure that all config.json files and any other changes are safe; alternatively if all you care about are the configuration files, you can open a PowerShell or cmd terminal inside your `SDV staging/mods` folder and run `robocopy . "../ConfigBackup" /S config.*` which will automatically find and backup your configuration files while maintaining the folder structure to `../ConfigBackup` as seen in the snippet below.
<img width="539" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/c3400694-d25c-43a9-ae66-253da1236244">

## Extension installation
Once everything is safe and sound. 
* Make sure Vortex is closed.
* Go to your `%appdata%/vortex/plugins` directory and extract the contents of the zip file to its own folder as seen below
<img width="532" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/e334976b-3ca3-4d78-af34-c78c210ce28c">
* Start Vortex and confirm it's running version 0.3.0 of the extension via the extensions page

## Extension usage
As mentioned in this ticket, the new config mod functionality is currently disabled by default and needs to be enabled, either through the settings page.
<img width="595" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/af84e2a3-10a4-4688-80c1-b9af5238421f">

Or just by clicking the Sync mod configurations button.
<img width="848" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/9f1af817-36a1-4471-9618-b7be385efbe1">

You should now be able to install/update/enable/disable mods as you usually do and Vortex should be syncing any generated `config.json` files to the newly generated "Stardew Valley Mod Configuration" mod entry. It does this whenever you press the sync button, or whenever you deploy/purge your mods.

## Recovery
If you wish to restore your environment to its previous state:

* Purge your mods and remove/uninstall the "Stardew Valley Configuration Mod" before closing Vortex.
* Delete the Stardew Valley extension from your `%appdata%/vortex/plugins` folder
* If you backed up your configuration files using the command I recommended in the prep/backup stage, go to your `SDV Staging/ConfigBackup` folder and copy all of its contents over to `SDV Staging/Mods`
* If you backed up the entire Staging folder - just delete the current staging folder and restore your backup.
* Start-up Vortex - it may complain about mods being added or removed (depending on the changes you made while you were testing the new extension) - look carefully at the directories Vortex is mentioning and ensure that the changes are expected before hitting apply.
* Ignore any errors that may be popping about invalid modTypes and go to Settings Page -> Workarounds Tab -> Click the Restore... button and browse to the state backup json file you created.
* Vortex should now restart - hit deploy, and you should be back to your old modding environment.

**Comment by IDCs** [comment]
@oliverrook, @SoraHjort - this functionality will never be released unless someone is willing to test it.

**Comment by sammihere** [comment]
@IDCs Can I help test? I'm having the same issue and would really like to see this released!

**Comment by IDCs** [comment]
Hey @sammihere, certainly, that would be great!

Have a look at the instructions I left for oliverrook and let me know if you encounter any issues.

> Hey @oliverrook,
> 
> Apologies for not responding sooner - we get so many github notifications, it's possible for us to miss ticket activity unless you tag us like my colleague did above.
> 
> Please find version 0.3.0 of the SDV extension below. [game-stardewvalley-0.3.0.zip](https://github.com/Nexus-Mods/Vortex/files/15247967/game-stardewvalley-0.3.0.zip)
> 
> I would prefer being present when you test the extension if possible, so that we can debug any issues that may come up during your tests, but it's really up to you. Just send me a friend request on Discord (nagev_)
> 
> ## Prep/Backup
> Before we do anything we need to backup your config files and Vortex's state.
> 
> * For the state, open Vortex and go to the Settings Page -> Workarounds Tab -> Click on "Create backup" and save the state backup .json file somewhere safe.
> * If you have space to spare - I would backup your entire staging folder to ensure that all config.json files and any other changes are safe; alternatively if all you care about are the configuration files, you can open a PowerShell or cmd terminal inside your `SDV staging/mods` folder and run `robocopy . "../ConfigBackup" /S config.*` which will automatically find and backup your configuration files while maintaining the folder structure to `../ConfigBackup` as seen in the snippet below.
> 
> <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/8960252/328877959-c3400694-d25c-43a9-ae66-253da1236244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU3MzIsIm5iZiI6MTcyNzMzNTQzMiwicGF0aCI6Ii84OTYwMjUyLzMyODg3Nzk1OS1jMzQwMDY5NC1kMjVjLTQzYTktYWU2Ni0yNTNkYTEyMzYyNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDcyMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE1ZmFiZWQ4MmFkYzYxNTE2NDEwNDk3YzU4OTRiNmUyNDUyYjU0ZjJmMTg3NjkxMWQ4NTdiZTQwYWU1ZDA5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dnko_VeQtaBXgri0mMm-CAsA_jiX497m4Vzvz_0b5to">
> ## Extension installation
> Once everything is safe and sound.
> 
> * Make sure Vortex is closed.
> * Go to your `%appdata%/vortex/plugins` directory and extract the contents of the zip file to its own folder as seen below
> 
> <img alt="image" width="532" src="https://private-user-images.githubusercontent.com/8960252/328879032-e334976b-3ca3-4d78-af34-c78c210ce28c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU3MzIsIm5iZiI6MTcyNzMzNTQzMiwicGF0aCI6Ii84OTYwMjUyLzMyODg3OTAzMi1lMzM0OTc2Yi0zY2EzLTRkNzgtYWYzNC1jNzhjMjEwY2UyOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDcyMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc3YjgwYmQ2ZTQ4NTM3ZjY4NDkxYWNhZTY3ZTFkMTZmY2IyMmRlMDgyOTllMTQxNWFkOWYxMThkNGIxODJjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sOO-wAoE1KnYJv7YxqyaLE1ieabgQBQaR8qSm52qoUI">
> * Start Vortex and confirm it's running version 0.3.0 of the extension via the extensions page
> 
> ## Extension usage
> As mentioned in this ticket, the new config mod functionality is currently disabled by default and needs to be enabled, either through the settings page. <img alt="image" width="595" src="https://private-user-images.githubusercontent.com/8960252/328880843-af84e2a3-10a4-4688-80c1-b9af5238421f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU3MzIsIm5iZiI6MTcyNzMzNTQzMiwicGF0aCI6Ii84OTYwMjUyLzMyODg4MDg0My1hZjg0ZTJhMy0xMGE0LTQ2ODgtODBjMS1iOWFmNTIzODQyMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDcyMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJhODQ4YTAxNDg5ZjM3ZGYxY2Y2YjMzOGIyZmU0ZTQxMzBmNTA3N2RlYTBkMDVkMWNiODhiZjY2ODg0M2FkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nA2la-SAcLBaB0Ib6zVU-w-6jYd2bfPeseX5yh_5Fdk">
> 
> Or just by clicking the Sync mod configurations button. <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/8960252/328881133-9f1af817-36a1-4471-9618-b7be385efbe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU3MzIsIm5iZiI6MTcyNzMzNTQzMiwicGF0aCI6Ii84OTYwMjUyLzMyODg4MTEzMy05ZjFhZjgxNy0zNmExLTQ0NzEtOTYxOC1iN2JlMzg1ZWZiZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDcyMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjczMTEyNDhhMGVmOGE5NmI2NzU5MjgxMzUzNWRlOTg5YjZjOGFjMmQxM2JhMDk4NTc1NmMxMjM0NTJkMGUzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hgNhm0LssYv8iTM7YkW_XgeQ-fu5bf8A493uiYkk-s8">
> 
> You should now be able to install/update/enable/disable mods as you usually do and Vortex should be syncing any generated `config.json` files to the newly generated "Stardew Valley Mod Configuration" mod entry. It does this whenever you press the sync button, or whenever you deploy/purge your mods.
> 
> ## Recovery
> If you wish to restore your environment to its previous state:
> 
> * Purge your mods and remove/uninstall the "Stardew Valley Configuration Mod" before closing Vortex.
> * Delete the Stardew Valley extension from your `%appdata%/vortex/plugins` folder
> * If you backed up your configuration files using the command I recommended in the prep/backup stage, go to your `SDV Staging/ConfigBackup` folder and copy all of its contents over to `SDV Staging/Mods`
> * If you backed up the entire Staging folder - just delete the current staging folder and restore your backup.
> * Start-up Vortex - it may complain about mods being added or removed (depending on the changes you made while you were testing the new extension) - look carefully at the directories Vortex is mentioning and ensure that the changes are expected before hitting apply.
> * Ignore any errors that may be popping about invalid modTypes and go to Settings Page -> Workarounds Tab -> Click the Restore... button and browse to the state backup json file you created.
> * Vortex should now restart - hit deploy, and you should be back to your old modding environment.

**Comment by IDCs** [comment]
Hey @sammihere - did you get a chance to test the new extension?

**Comment by sammihere** [comment]
Hey @IDCs - sorry I'm so late but was able to test and it worked great for me!

**Comment by iqraut** [comment]
I would think idealy the method to go about it would be to see what files were in the pre-update archive to see which files have been procedurally generated (like the config files tend to be) and remove those before applying the update.
The backup script is a sensible workaround, but Vortex really should preserve files that were generated after installation rather than treating the mod folder as disposable during an update. Comparing the old installed files against the new archive sounds like a much safer approach, especially for mods that store per-save JSON data in subfolders. It would also avoid hardcoding specific filenames like config.json. For general modding and gameplay references, this [[Stardew Valley guide](https://stardewvalleyapk.app/)](https://stardewvalleyapk.app/) can be useful too.
