### ISSUE TITLE
Vortex uninstalling it self.

### ISSUE THREAD

**Issue by darkt1981** [Nexus-Mods/Vortex#15422]
**Describe the bug**
Vortex uninstalling it self.

**To Reproduce**
1. Open vortex, install anything close vortex.

Message, vortex will update it self and then close, but it doesnt update it self it uninstalls it self, multiple people on google have had this issue for over 3 years now on google.

No anti virus software active not even windows crappy defender.

**Expected behavior**
Uninstall vortex and reinstall a new version. 

**Platform (please complete the following information):**
 - OS: Windows 10 latest
 - Vortex Version : multiple versions

**Additional context**
Maybe add a option to tell vortex to sod off and no do auto updates, because having to reinstall it 4-5x a day is just a joke.

**Comment by IDCs** [comment]
Hi there - double check the shortcut you're using to start Vortex, I think you'll find that it points to an old installer rather than Vortex's executable. So you're basically closing Vortex to update - it installs fine; but when you try to run Vortex through your shortcut, it just installs the older version on top of the update hence it asks you to update again.
