### ISSUE TITLE
Verify Extension: [837] A Plague Tale Requiem

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#15447]
# Verify Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** |  A Plague Tale Requiem Vortex Extension |
| **Extension Mod ID** | 837 |
| **Extension URL** | [A Plague Tale Requiem](https://www.nexusmods.com/site/mods/837)  |
| **Game Name** | A Plague Tale Requiem |
| **Game Domain** | aplaguetalerequiem  |
| **Game URL** | https://www.nexusmods.com/aplaguetalerequiem |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Checked with

|  |  |
|--|--|
| **Extension Version** |  |
| **Vortex Version** |  |

## Instructions

https://nexusmods.atlassian.net/wiki/spaces/VORTEX/pages/2892529680/Extension+Verification+Pipeline#Games ​

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [x] Is the extension named correctly?
- [x] Is it packaged correctly?
- [x] Is artwork correct?
- [x] Is the changelog accurate?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest. This is completed using the [Actions at GitHub](https://github.com/Nexus-Mods/vortex-add-extension/actions), there is one action for each extension type. ​

- [x] GitHub Action run
- [x] Manifest file manually checked for errors
- [x] Contacted author
- [x] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated. [Templates are on Confluence](https://nexusmods.atlassian.net/wiki/spaces/VORTEX/pages/2906750977/Announcements+Templates) ​

**Comment by IDCs** [comment]
The extension is currently blocked due to:

* Mods on the site are mostly shader presets which cannot be used without a 3rd party application https://reshade.me/ the extension does not inform the users of this requirement.
* The extension only supports 2/19 mods.

To unblock:

* The extension author should at the very least raise a notification informing users of the reshade requirement

**Comment by ChemGuy1611** [comment]
Acknowledged. Working on these updates.

**Comment by ChemGuy1611** [comment]
I have added a notification for Reshade installation to the extension. 

On the topic of Reshade presets, these are .ini files that can technically be placed anywhere, but the game executable location (which is where this extension installs mods) is ideal. Because of this, there is no need to add additional mod types. Additionally, if a mod does actually contain reshade shaders, these are almost always packed by the mod authors so that the mod can be deployed the game executable's folder with the correct directory structure. Therefore, no special mods types are necessary to handle those types of mod installs. 

Thank you for your time and effort on adding this extension to Vortex!
