### ISSUE TITLE
Verify Extension: [840] Final Fantasy IX Game Extension

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15478]
# Verify Extension: Final Fantasy IX Game Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** | Final Fantasy IX Game Extension |
| **Extension Mod ID** | 840 |
| **Extension URL** | https://www.nexusmods.com/site/mods/840 |
| **Game Name** | Final Fantasy IX |
| **Game Domain** | finalfantasy9  |
| **Game URL** | https://www.nexusmods.com/finalfantasy9 |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [ ] Is the extension named correctly?
- [ ] Is it packaged correctly?
- [ ] Is artwork correct?
- [ ] Is the changelog accurate?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest.

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated.

**Comment by IDCs** [comment]
Although it does appear that most mods on the website act as asset replacements and the extension should be able to cater for that; it currently would barely support any of them due to the hectic packaging patterns.

To unblock:

* At a minimum a custom installer needs to be created to cater for the packaging patterns and ensure the mods are deployed correctly
* Alternatively some stop patterns could be implemented
* (Optional) - this is a unity game so I'm surprised none of the mods on the site use BepInEx currently - might be wise to integrate the extension with Vortex's bepinex extension `requireExtension('modtype-bepinex')` in case this changes in the future.

**Comment by IDCs** [comment]
Closing as stale
