### ISSUE TITLE
Verify Extension: [852] Lies of P Vortex Extension

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15531]
# Verify Extension: Lies of P Vortex Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** | Lies of P Vortex Extension |
| **Extension Mod ID** | 852 |
| **Extension URL** | https://www.nexusmods.com/site/mods/852 |
| **Game Name** | Lies of P |
| **Game Domain** | liesofp  |
| **Game URL** | https://www.nexusmods.com/liesofp |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [ ] Is the extension named correctly?
- [ ] Is it packaged correctly?
- [ ] Is artwork correct?
- [ ] Is the changelog accurate?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest.

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated.

**Comment by ChemGuy1611** [comment]
Thanks for pointing that out. I will remove that first resolve line.

**Comment by IDCs** [comment]
@ChemGuy1611 you're going to hate me but it's still not fixed 😆 

The setup function is asynchronous and will return immediately unless it's told to wait for something. You're currently calling

`fs.ensureDirWritableAsync(path.join(discovery.path, spec.game.modPath));`

Which indeed kicks off the mods path creation process, is not awaited by the setup function and therefore can potentially attempt to access that folder before the path was created.

This is easily fixed by adding a `return` in front of the directory creation call - that way the setup function will not resolve unless the directory is confirmed to be created.
```
return fs.ensureDirWritableAsync(path.join(discovery.path, spec.game.modPath));
```

**Comment by IDCs** [comment]
I'm afraid version 0.1.2 is still not returning correctly. Just change your entire setup function to this:
```
function setup(discovery, spec) {
    // make sure the mod folder exists (! is for trusting that it won't be null)
    return fs.ensureDirWritableAsync(path.join(discovery.path, spec.game.modPath)); 
}
```
