### ISSUE TITLE
Review: Grounded

### ISSUE THREAD

**Issue by 0-F** [Nexus-Mods/Vortex#15725]
### Nexus Username

0R4X

### Extension URL

https://www.nexusmods.com/site/mods/880

### Game URL

https://www.nexusmods.com/grounded

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hey there @0-F - started reviewing your extension and it's pretty solid; however, I noticed that you did not provide an installer for UE4SS and are relying on the user to install it manually. Given that UE4SS is a hard requirement for a significant number of mods, please enhance your extension to detect and install it for the user.

**Comment by 0-F** [comment]
Hi @IDCs - I uploaded a new version of the extension.
The latest version of UE4SS is now automatically downloaded and installed from the official GitHub repository.
UE4SS is installed as a mod and it is visible in Vortex in the "Mods" section.
I use some code from your [vortex-download-helper](https://github.com/IDCs/vortex-download-helper) and from the [Palworld](https://github.com/Nexus-Mods/game-palworld) extension.

**Comment by IDCs** [comment]
Thank you for your contribution - sorry it took so long to re-review your extension. Good job overall, but please note that the UE4SS is missing notification is still being raised if the user didn't deploy his mods (which is expected) but you can check that the mod is installed and enabled rather than whether it's located in the game's directory (as it surely will be once the user deploys his mods)

Either way, I didn't see that as a reason to keep blocking this extension - added to the manifest.
