### ISSUE TITLE
[Suggestion] Use Task Scheduler to bypass UAC Prompt

### ISSUE THREAD

**Issue by PhantomGamers** [Nexus-Mods/Vortex#1576]
Applications such as [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming/blob/master/BorderlessGaming.Logic/System/AutoStart.cs#L66) and CCleaner use this functionality to gain admin access without prompting the user after the initial prompt for permission to create the task.

Borderless Gaming's purpose is for running at startup, but CCleaner creates a task that only runs on demand, which then runs the main exe as admin with the required arguments.
A similar approach could be used here.

**Comment by PhantomGamers** [comment]
I have no experience with node.js (that is what this is written in, right?), so I probably won't be able to implement this myself, but perhaps this library would be of use: [skitsanos/schtasks](https://github.com/skitsanos/schtasks)

**Comment by PhantomGamers** [comment]
> I'm unclear about why/when you would need to run as an elevated user other than initial install?

Symbolic links require admin rights.

**Comment by gab** [comment]
Alternatively, Steam has SteamService.exe a.k.a. SteamClientService that runs as admin, that it calls upon to perform admin tasks without having to prompt the user. I would think that if such a system is good enough for the leading PC games platform, it's good enough for Vortex. If the service is well-written with constraints on what it can do, the inherent security risk can be mitigated.

(The constant prompting in symlink mode is enough to drive one crazy, and sometimes you have no other alternative due to one drive being full, with no room for game + mods staging folder. Really hope this can be implemented.)

**Comment by TanninOne** [comment]
Valve is a corporation making billions of dollars probably employing hundreds of developers working on their platform.
We are two people working on Vortex.
The question shouldn't be "if it's good enough for Steam, is it good enough for Vortex?" it should be "If a billion dollar company has the capacity to develop, maintain and properly test a system service, is it a valid conclusion that a team of two people can?"

Besides: No, just because Valve does it doesn't mean it's a good idea. SteamService.exe is a cause for system crashes for a lot of users, it's considered an extremely high security risk and is regularly recognized as potential malware by virus scanners even though it has an expensive certificate.

So the question becomes: "If this is causing so much pain for Valve, can a two-developer team deal with at least as much fallout?"

The idea of using a task was way more plausible but tbh, considering Windows 10 allows symlinks without elevation now, I feel like this is simply not necessary any more.
