### ISSUE TITLE
Installer error states 'Vortex can't be closed' repeatedly.

### ISSUE THREAD

**Issue by The-Leach** [Nexus-Mods/Vortex#15775]
**Describe the bug**
When trying to 'Restart & Install' the latest Vortex update, the update begins, then gets stuck. I then receive a message that says "Vortex cannot be closed. Please close it manually and click Retry to continue." 

**To Reproduce**
1. Open Vortex
2. Click on notifications
3. Click on "Restart & Install" next to 'update downloaded'
4. Allow permission for Vortex to make system changes (administrator prompt)
5. Error appears when progress bar is circa 1/3 through.

**Expected behavior**
Vortex to install with no problems
Clicking 'retry' should remove the error

**Screenshots**
Exactly the same image as is on this post: https://github.com/Nexus-Mods/Vortex/issues/15552

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.11.5 (5/21/2024)

**Additional context**
No matter what I do, this always appears, I saw this issue post - https://github.com/Nexus-Mods/Vortex/issues/15552 - but I have plenty of storage space available also, so it may not be due to storage if this is the same issue. I currently cannot install the update due to this.

**Comment by IDCs** [comment]
@The-Leach - in the meantime please install the update manually through the website - just install the update on top of the existing version of Vortex - your data will persist as long as you didn't set the downloads or staging folder inside Vortex's root folder (C:/Program Files/Black Tree Gaming Ltd/Vortex by default)

I think your issue is different than #15552 - in your case it appears to be down to inability to download the update from Github. This appears to be a common issue in some countries 😬 

How many games are displayed in your games page? should be around 300 - if not, that's a clear indication that there's a connectivity issue between you and Github.

**Comment by IDCs** [comment]
Closing due to lack of response
