### ISSUE TITLE
Review: ETB Rocket Gateway

### ISSUE THREAD

**Issue by lu2000luk** [Nexus-Mods/Vortex#16034]
### Nexus Username

lu2000luk

### Extension URL

https://www.nexusmods.com/site/mods/934

### Game URL

https://www.nexusmods.com/escapethebackrooms

### New features

Nothing, it literally is an extension to enable the funny buttons on the mods page cuz i want users to be able to use the nxm system i made for the app in way too long...

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by lu2000luk** [comment]
Tbh you know what, you should not make an announcement on #vortex-announcements

**Comment by lu2000luk** [comment]
The extension is a dummy that just serves as the user to know how to download mods for the game.

**Comment by insomnious** [comment]
Enabled the game button but not releasing the extension. I think the better of two evils is to have the button so ETB Rocket can catch the nxm:// link, and if Vortex catches it nothing happens. If we have an extension, we are saying Vortex supports the game which it doesn't and that will need a lot more support and managing.

This is until we can create a new game stub type thing so that Vortex can handle nxm links for games it doesn't manage and we can provide help like point them in the direction of other mod managers.
