### ISSUE TITLE
Add an option to manually tell Vortex to sort mods by categories. 

### ISSUE THREAD

**Issue by Zippomoon** [Nexus-Mods/Vortex#16329]
I just had to reinstall Windows on my PC, and I got hundreds (if not over a thousand) of mods left over from the previous install - some of which aren't on the Nexus anymore - problem is after re-adding them to Vortex the app didn't sort them into categories automatically, and I don't want to have to sort all those mods one by one manually.

**Comment by ChemGuy1611** [comment]
You can sort by category by clicking on the "Category" column title at the top of the mod list. 

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/3b864a8f-075e-409d-b840-492e55250893">

**Comment by IDCs** [comment]
Hi there @Zippomoon - the categories are stored in Vortex's state which is located in `%appdata%/vortex` - re-installing Windows will indeed remove the categories and any type of sorting mechanism you had in place.

When re-installing Windows or moving to a different PC with the same mod setup you'll have to export/import your state through the Settings Page -> Workarounds Tab. Otherwise some metadata loss is inevitable.
