### ISSUE TITLE
Vampire The Masquerade Bloodlines - Cannot Deploy Mods On Clean Steam Installation

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16348]
**Describe the bug**
The bundled plugin for Vampire the Masquerade Bloodlines cannot deploy mods when managing a fresh Steam installation. This is because the extension includes a mod type for the "Unoffical_Patch" folder, but does not have a write check for that folder. The GOG version of the game apparently comes with this folder included, but Steam does not. 

Because there is a mod type with that folder defined, Vortex will give the deployment error if the folder is not present, which it will not be on a fresh Steam install. 

**To Reproduce**
Start managing VTMB on a clean Steam install. You will get the error that deployment is not possible because of the missing "Unofficial_Patch" folder.

**Expected behavior**
No deployment failures on a fresh Steam install.

SOLUTION:
I have attached updated extension files that will resolve this problem by simply setting the "Unofficial_Patch" folder as the default mod installation folder and including a default tool to launch the game with the required command line argument to use that folder to load mods. 

**Platform (please complete the following information):**
 - Windows 11
 - Vortex v1.12.3
 - VTMB Steam version

[game-vampirebloodlines.zip](https://github.com/user-attachments/files/16788055/game-vampirebloodlines.zip)

**Comment by IDCs** [comment]
Hey there @ChemGuy1611 - thanks for bringing this to our attention; will ensure the setup function now creates the unofficial_patch folder. Will also have to modify 

Regarding the other changes:
- Changing the default mod type will cause issues for users that have a working setup; if you're certain that all mods should now be installed in `Unofficial_Patch`, a migration function needs to be written - have a look at the other bundled extensions that are using the `context.registerMigration` call (7dtd + others).
- As far as I know, only the GoG version of the game has the unofficial patch included; although it is a hard pre-requisite for most mods out there, there are still some that function without the patch, which is why the default mod path was set to `Vampire` rather than `Unofficial_Patch`.

Given the items above, I think the default mod path should remain `Vampire`.

BTW - you can submit a PR for the vortex-games repo when modifying bundled extensions; the PR freeze is only in place for new game extensions.
