### ISSUE TITLE
Failed to get  list of tracked mods issue

### ISSUE THREAD

**Issue by Valkyrie44278** [Nexus-Mods/Vortex#16347]
Everytime I open the vortex mod manager i get a message pop up saying failed to get  list of tracked mods, ive uninstalled and reinstalled it serveral times but to no avail any idea how to fix it.  
![image](https://github.com/user-attachments/assets/4a40bcec-0de7-4543-a3a5-89b6200247c4)

**Comment by IDCs** [comment]
Hi there - the text in that dialog box is misleading (this was fixed a few weeks back but the fix has yet to be released)

error code 429 is caused by the server rate limiting functionality - basically you sent too many requests during a short period of time and the server will not serve any more of you requests for a brief period of time (~60 minutes at most)

This is not a bug, it's the server telling you to slow down.
