### ISSUE TITLE
Review: WH40K Space Marine 2

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16383]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/961

### Game URL

https://www.nexusmods.com/warhammer40000spacemarine2

### Existing Extension URL

NONE

### New features

Installs mods next to the game's "shipping" executable for now. Includes mod types for config files and paks. I will update to add automatic installers for this if/when mods are release that use those folders. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by insomnious** [comment]
Hey there

I'm looking at your extension now the game has been released properly. 

The game wouldn't run from Vortex as it just crashed when it was attempting, both by clicking play and by using the supported tool. This was fixed by just letting the game launch via Steam and keeping it nice and simple. I adjusted your code to the below and it works fine

```js
async function requiresLauncher() {

  let game = await queryGame();

  if (game.gameStoreId === "steam") {
    return { launcher: 'steam' };
  }  

...
```
There are a few binaries that you can load the game with but I would remove the supported tools as it's not needed at this point

I tested a couple of mods from the site and they seemed to work in game fine.

So if you could just default to using the launcher and remove the supported tools, we should be good to go.

Thanks
