### ISSUE TITLE
maxMemory doesn't work as commandline argument or as startup.json parameter

### ISSUE THREAD

**Issue by vikram-jadhav** [Nexus-Mods/Vortex#16418]
**Describe the bug**
The code indicates that it processes either --maxMemory or --max-memory as a command line argument. Also, there's some evidence that maxMemory is also parsed from startup.json. However, none of these options works, and the app crashes when I use 4k texture packs for rdr2 and click deploy mods with error memory usage growing fast {"usage":"3.74 GB","previous":"3.63 GB","max":"4.00 GB"}
2024-09-12T14:20:40.860Z [ERROR] render process gone {"exitCode":134,"reason":"crashed"}. 

**To Reproduce**
1. install AIO Megapacks for RDR2 using Vortex
2. In shortcut to Vortex.exe pass command line args --max-memory 8192 --maxMemory 8192
3. For added measure, also add "maxMemory":"8192" pair to startup.json found in C:\Users\<username>\AppData\Roaming\Vortex
4. deploy mods and wait. The app will keep crashing, saying it's using too much memory (vortex.log) , e.g. >= 4GB

**Expected behavior**
The user should be able to set the maximum memory to avoid the crash above. 

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.12.4

**Comment by IDCs** [comment]
Hi @vikram-jadhav, unfortunately the 4GB limitation is a compile-time flag/limitation which is hard-coded in the Electron framework we use. Looking through their issue tracker, it appears that they are not planning on changing that. https://github.com/electron/electron/issues/33994

Being able to support more than 4GB would require us to create our own fork of Electron to remove the limitation, which I'm afraid is not an option at this point (given that Vortex is being phased out in favour of NMA)

That being said, Vortex should never crash due to memory; the fact that it does, suggests that Vortex or the game extension itself may have a memory leak somewhere. Can you please send a link to a collection or mod which you've confirmed is breaching the memory limit so I can investigate.
