### ISSUE TITLE
Trying to re-install vortex after an issue

### ISSUE THREAD

**Issue by JNUzuller** [Nexus-Mods/Vortex#16431]
Hello, I ran out of room on my main drive for my PC for vortex mods and was trying to move over vortex to the larger drive I have. However I ran into an issue and have had to completely uninstall the product as a whole. Now that I am trying to re-install it though, no matter what I do it won't let me re-install vortex on this PC

**Comment by IDCs** [comment]
Hi @JNUzuller, can't help you unless you specify exactly what the issue is - we need error information, logs, etc. Vortex itself should be left on your main drive "C:\", you can then set the mods staging and downloads folder locations to the new drive.

Please be as descriptive as possible in your response and include screenshots.

**Comment by IDCs** [comment]
Closed due to inactivity
