### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by dmcaaa** [Nexus-Mods/Vortex#1877]
when I open vortex and click the login in button a box pops up saying the following: This file does not have a program associated with it for performing this action. Please install a program or, if one is already installed, create an association in the default programs control panel.
What is the file name and what program needs to be associated to it.

**Comment by IDCs** [comment]
Hi @dmcaaa, unfortunately that error is usually being raised by Windows itself due to OS configuration errors (possibly some issues with how Windows is configured to handle LNK file types). I suggest you google the error and fix this yourself. (Good place to start https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/d-this-file-does-not-have-a-program-associated/35da9609-0b98-452e-a84e-3c32f709a191)

I'm going to close this issue given that it does not seem to be related to Vortex.
