### ISSUE TITLE
Failure to Install Assets Without Admin Priveleges

### ISSUE THREAD

**Issue by Pixel3r** [Nexus-Mods/Vortex#2683]
When installing SkyUI for Skyrim (Legacy Edition) functionality is correctly installed, but some assets are not, until Vortex is run as an administrator.

1. Download the SkyUI package from Nexus or Steam. 
2. Install and enable SkyUI in Skyrim (Legacy Edition)
3. Run game and progress until inventory can be accessed. 
4. Open Inventory or Magic Menu.
5. Error message appears saying that magicmenu.svg, equipmenu.svg, and similar files are missing/incompatible, and advising mod conflict.

The expectation is that installing a mod would include all aspects of the mod.

**Platform (please complete the following information):**
 - OS: Windows 7
 - Vortex Version 0.16.15

**Comment by TanninOne** [comment]
If running Vortex as Admin solves the problem then that means your file permissions are messed up, thus preventing Vortex (running as regular user) from installing them.

By running Vortex as admin (ignoring the warning it gave you) and (apparently) installing mods this way you made the problem worse because now you probably have more files in your game directory owned by admin that the regular account can't overwrite. Running stuff as admin is what caused this problem in the first place.

None of this is a Vortex problem, the whole point of windows security measures is to prevent one account from accessing (writing, maybe even reading) files from a different account, a tool like Vortex can't circumvent that.

When you get a problem that a software can't access files due to permission problems then you should fix the permissions of the files in question, not escalate your account rights.
