### ISSUE TITLE
Uncapped Download on free account

### ISSUE THREAD

**Issue by bimoalfarrabi** [Nexus-Mods/Vortex#2685]
I just want to report to Vortex dev team about uncapped download speed on free account

**Screenshots**
![screenshot 160](https://user-images.githubusercontent.com/46051173/50347312-b2243b00-0567-11e9-8099-ea454edd40f6.png)
![screenshot 161](https://user-images.githubusercontent.com/46051173/50347320-b6e8ef00-0567-11e9-88c5-1f64adf5517a.png)
![screenshot 162](https://user-images.githubusercontent.com/46051173/50347327-ba7c7600-0567-11e9-9b9a-32887dc16f68.png)

**Platform:**
 - OS: Windows 10 64-bit
 - Vortex Version 0.16.15

**Comment by TanninOne** [comment]
a) Vortex does not, in any way shape or form implement any speed cap, this is done by the server, any kind of malfunction needs to be reported to the web team.
b) This is probably not a malfunction though, as was anounced a while ago, users that don't block ads are now given up to 2 MB/s bandwidth instead of 1 - I assume that's what this is.
