### ISSUE TITLE
Compare conflicting files before reporting the conflict

### ISSUE THREAD

**Issue by TekumzeWolf** [Nexus-Mods/Vortex#2957]
When installing related mods that often use share some common files each and every mod reports a conflict to the previous one.

For example two companion mods use the same body meshes/textures/whatever and uses a sort of "common" folder to store them.

More often then not these common files are identical so it doesn't really matter which mod overrides the other.

**Describe the solution you'd like**
Vortex could compare the conflicting files and if they are identical then those particular files are not reported as conflicting.

Many times (as in the sample described above) the resulting new mod would not produce any conflicts.

**Comment by TanninOne** [comment]
This would be quite expensive performance-wise, long-term you would definitively be better off just setting a rule.

**Comment by TekumzeWolf** [comment]
When adding a mod you already check for conflicts. When you find them you do a simple file comparison. If the files are same you don't report the coflict.. if they are different then you proceed as normal.

**Comment by Rattledagger** [comment]
Even if you just clicks to create a rule without any kind of verification whatever files is really conflicting, would guess you're using 5 seconds/rule. If you take the time looking-into what files is really conflicting, using 1 minute/rule or even more wouldn't be unrealistic, especially if you tries to look-up the various mods and see if it's mentioned something of how to handle file-conflicts.

As a comparison, reading all the files in a 100 MB mod and creating some kind of check-sum per file takes roughly 1 second on ssd. Comparing the already created check-sums between two (or more) mods should be a fast process only using some cpu-time (and memory).

Example, I'm using 5 house-mods what all is built from the same mod-resources using some of the same paintings, towels etc. Despite all the files is binary the same, according to Vortex there's around 100 file-conflicts per mod and with 5 mods this means I need to create 10 rules. Best-case 10 rules takes 50 seconds to create and if I do take the time to look what is really conflicting using 10+ minutes isn't unrealistic.

Or, using Vortex could have used 5 seconds to create check-sums for all mods files, used less than 1 second cpu-time finding all the files was binary the same for a total time of 6 seconds, and I had to create zero rules.

Since 50 seconds >> 6 seconds calling this "expensive performance-wise" isn't very accurate.

In most instances users will use Vortex to install the mod-files and as part of this all files is read from archive and written to hd/ssd. If Vortex takes advantage of this time to also create the check-sum per file would guess this mostly can be done without even re-reading the file from hd but instead reading from memory, meaning unless a mod is 1 GB+ in size users wouldn't even be aware any check-sums had been created at all since the extra overhead is so small.

Pros:
* Users only needs to handle real conflicts.
* The fewer rules users needs to create, the more time can be used for playing the game.
* A better chance users will keep track of what conflicts exists, instead of just clicking-away just to get all conflicts to go away without caring whatever wins the conflict, similar to how many just clicked "yes to all" in NMM.

Cons:
* Creating check-sums for large mods will take some time.
* Storing the check-sums will increase Vortex disk-usage.
* Filtering-out binary equal files from list of file-conflicts must be programmed.
* Many mods files never conflicts so creating check-sums for these can be seen as a waste of time, but not sure if only creating check-sum for conflicting files will be much better.

A small benchmark at the end, using an older version of the Skyrim mod 3NPC, with 45189 files, 322 folders and 2.83 GB files. Using fastsum (from fastsum.com) to create md5 checksums took 135 seconds when run from hd but only 15 seconds if deleted the md5-file and immediate re-run since now all files was cached in memory. Installing the mod took 248 seconds, meaning if it's possible in Vortex to use cached files during mod-installation where'll only be a small extra overhead to the total installation-time of a mod - even if you install to hd.

**Comment by TanninOne** [comment]
You don't see most of the problem.
a) Many of our users don't have their mods on ssds
b) There are plenty of mods larger than 100MB
c) The amount of time it takes to check a mod depends in large parts on the number of files, not the size. A mod with thousands of small files (they exist) on a regular HD could easily take minutes to hash.
d) Vortex can't just assume the files stay the same. The hashes would have to be recreated at least once every session, otherwise if you change files in a mod Vortex wouldn't notice that it's no longer the same file as before.

If mods were "sealed" as in: Users can't touch them after installed (without going through Vortex), yes, this might be feasible. Calculate checksums during install and then run with that. But that would make every self-proclaimed pro-user throw a fit.

Also, you seem to have a few misconceptions:
a) If you have 5 mod conflicts then you need 5 rules, not 10
b) Once you have created the rules you don't have to touch them again so this is a one time investment of - well - let's say 50 seconds - vs a permanent ui slowdown. Even if it was just comparing md5 hashes this would still add to all the other stuff vortex has to do continuously in the background.
c) Vortex can't read the files while it's extracting them, extraction is handled in a separate 7zip process to ensure best performance and stability.

**Comment by Rattledagger** [comment]
> Also, you seem to have a few misconceptions:
> a) If you have 5 mod conflicts then you need 5 rules, not 10

This is simple, with two mods A and B you need to create one rule, example "B load after A".
When you add 3rd. mod C, since it conflicts with both A and B, you need to create two new rules, example "C load after A", "C load after B". At the same time, you need to keep the original rule ==> you've got 3 rules.
Add 4th. mod D, since you conflict with A, B and C you need to create 3 new rules + you keep the 3 old rules ==> total 6.
Add 5th. mod E, since E conflicts with A, B, C and D you need to create 4 new rules + keep the 6 old rules ==> 10 total rules.

> b)  Once you have created the rules you don't have to touch them again so this is a one time investment

Since where's nothing like infinite free disk space, it can be required to uninstall mods to make space for other mods or another games mods and since Vortex loses all information of file-rules on uninstallation you can't expect the rules is a once-off operation. In case Vortex learns to automatically re-install all mods in a profile with correct fomod-choices, file-overwrites etc. creating rules can be a once-off operation, but Vortex isn't where yet.

> c) Vortex can't read the files while it's extracting them, extraction is handled in a separate 7zip process to ensure best performance and stability.

Doing a few more tests, while Windows 10 does seem to cache writes, at least with large mods chances are many of the files are already out of the memory again and unfortunately can't create hashes "for free".

> d) Vortex can't just assume the files stay the same. The hashes would have to be recreated at least once every session, otherwise if you change files in a mod Vortex wouldn't notice that it's no longer the same file as before.

Wouldn't either "creation time" or "last written" be changed for any normal file-changes?

Since can't assume can create hashes "for free", the cheapest would be something like:
* 1: If two mods X and Y already has a file-rule between X and Y, skip checking X and Y for conflicts.
* 2: If all conflicting files between X and Y does not have the same size in both mods, skip further conflict-checks.
* 3: Stop hashing for mod X and Y if the hashes are different for a file.

In case no conflicts was found between two mods, where are now two possibilities, maybe configurable with a Settings:
* 4a: A new rule "Non-conflicting mod Y load after non-conflicting mod X" is automatically created and if no other conflicts with X and Y both will show-up with green lightning-bolt in Conflict-column.
* 4b: Both X and Y shows-up with red lightning-bolt and when you click either X or Y red lightning-bolt the suggestion is (if clicked X) either "Non-conflicting mod X load after non-conflicting mod Y" or "Non-conflicting mod X load before non-conflicting mod Y".
* 5: Regardless of 4a or 4b, mods shows-up with rules and with green lightning-bolts under conflicts. This means can change the rule to any of the other rules (but not from "normal" rule to "non-conflicting…"-rule).
* 6: Mods are only re-hashed if you set the rule back to blank rule (or you uninstall the mod).

Since you're creating rules for the conflicts, even the files are detected to be the same, you only need to hash once, since even if you changes some of the files you already have a loading-rule. Also you only hash if all conflicting files has the same size.

Now a better name than "Non-conflicting mod X" and "Non-conflicting mod Y" is a possibility.

**Comment by TanninOne** [comment]
> This is simple, with two mods A and B you need to create one rule, example "B load after A".
> When you add 3rd. mod C, since it conflicts with both A and B, you need to create two new rules, example "C load after A", "C load after B". At the same time, you need to keep the original rule ==> you've got 3 rules.

If your mod C conflicts with A and B then that's two conflicts. What I said was "if you have 5 conflicts you need 5 rules" not "if you have 5 mods with one or more conflicts you need 5 rules".

On topic:

4a is a no-go because if Vortex created a rule "X after Y" automatically and then Y gets changed (through an update or xedit or something) the rule would be wrong and users would be blaming us for an automatism that messed up their load order.
4b doesn't save any time, the user would still have to set a rule so what's the point? It's just a ton of work for us and still a performance hit for practically no gain.

It might be feasible for us to check only the hash of conflicting files only when you open the conflict resolution dialog so vortex can give a hint like "Conflicting files in the two mods are identical anyway so it doesn't matter atm which you load first." for the same effect as 4b but with a lot less effort and no performance hit outside that dialog.
But that would still be misleading, because again: An update to one of the mods might change this and turn the "not-really-a-conflict-conflict" into a proper conflict and then you have a rule that's wrong with a 50% likelyhood that vortex created for you or that you created in zombie-mode because Vortex said it didn't matter.
Even if the two mods don't have any real conflicts you're better off loading the more specialised, smaller or more frequently updated mod last. Or, if you intend to modify one of the mods (e.g., clean an esp) then the one that you intend to manipulate should go last. Vortex can't know any of that.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
