### ISSUE TITLE
Vortex stuck at the spash screen

### ISSUE THREAD

**Issue by nitanmarcel** [Nexus-Mods/Vortex#3072]
**Describe the bug**
I just installed the new vortex version and it gets stuck at the splash screen, until i click it and it says "Vortex is not responding."
le, add screenshots to help explain your problem.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 0.16.15

**Dumps Files:**
http://www.mediafire.com/file/ovo1kik31c1w8a1/dumps.rar/file

**Comment by IDCs** [comment]
Hi @nitanmarcel, it looks like you're affected by one of our access violation crashes (Can't say which one as the dump file is corrupt). This usually happens when an external application is attempting to access the same memory address as Vortex (This may be caused by an overzealous Anti-Virus software among others) 

Please have a look at the below forum thread where Tannin goes through what we currently know about this issue and see if you're able to pinpoint what is trying to access the same resources as Vortex.

https://forums.nexusmods.com/index.php?/topic/7151166-whitescreen-reasons/

I'm going to leave this issue open for a while in case you have questions and/or are able to find out more about this as it may help users with the same issue. (Please do let us know if you're able to resolve this)

**Comment by nitanmarcel** [comment]
OK, I will try to fix the problem later afternoon. I also forgot to say that I'm using an old version which starts without any problems.. I'll come back later with answers. 

Thanks

**Comment by IDCs** [comment]
Hi @nitanmarcel, are you still affected by this issue ? if not, would be helpful to know how you managed to fix it...

**Comment by TanninOne** [comment]
closed due to lack of feedback
