### ISSUE TITLE
Disable autodeploy

### ISSUE THREAD

**Issue by Iloei** [Nexus-Mods/Vortex#3153]
Currently, removing a mod starts a redeploy (and remove seems to not always work for some reason, but I am still figuring out that part).

We should have an option that prevents redeploy on disabling a mod, just like there's an option for preventing redeploy on enabling a mod (or the same option should do both).

The deploy button should also get a high contrast background when deployment is stale.

**Comment by TanninOne** [comment]
That's not possible. When you remove a mod it has to be undeployed before the mod gets deleted, otherwise symbolic links would become invalid (pointing to files that no longer exist) and hard links would no longer be recognizable as hardlinks and would then not get cleaned up at all.
Only an installed mod can be undeployed safely.

**Comment by Iloei** [comment]
This is a bit disturbing. It means that vortex does not keep a record of where deployed files came from where.

**Comment by TanninOne** [comment]
It does keep track of it but it uses that manifest only as a fallback. Using the file relation stored by the filesystem is much more robust, considering our community has a tendency of blindly deleting files they don't recognize.

You don't get rid of your main parachute to safe weight, just because you also have a backup.

**Comment by Iloei** [comment]
Well, in that case, could we get a "marked for removal" mechanism?

I am looking for two things:

1) I want to know (when I mark a  mod for removal) that it will be removed - so I want that to show up in the UI right away, but also

2) I don't want to have the system bog down on long term operations preventing me from interacting with the UI. 

I understand that safety is important, but with the current implementation, I don't really know what it's doing.
