### ISSUE TITLE
Move double-click mod details panel to right-click context menu.

### ISSUE THREAD

**Issue by rzjnzk** [Nexus-Mods/Vortex#3236]
It is conventional for the right-click context menu to provide all possible actions on a selection of items in a list. As an end-user, I do not find the details panel that appears when a mod is double-clicked to be intuitive. For example, adding mods to a category should be done from the right-click context menu, and furthermore, when adding a mod to a category, one should be able to add to a new category, as opposed to opening a separate UI element to create categories. I also recommend that the mod list be colapsable per mod category, as was the case with Nexus Mod Manager.

Note: source should be moved to the existing details-style mod view, author and mod description can be found from 'Open on Nexus Mods', and additionally, I would suggest displaying this information when the user hovers the mod in the details view.

Suggested right-click context menu entry additions:

- Move to category [additionally, possibly allow for a mod to reside in multiple categories, regardless of tree structure]
- Rename
- Change game section
- Change mod type
- Add personal note [the note can be displayed when the user hovers the mod in the details view]

The 'Drop files' section should be removed in favor of dropping mod files directly on the mod list, or rightmost pane.

I will better format and articulate my suggestions if needed.

**Comment by TanninOne** [comment]
Sorry, but we can't accept issues that contain more than half a dozen change requests. Please always create one report per issue so that we can track them individually.

On topic: Doing complex actions from a context menu is a PITA for many users because the menu closes as soon as you accidentally click outside the menu so users who have trouble clicking precisely wouldn't be happy with that solution.
Also I'm against putting too much functionality into context menu because overloaded menu make it harder to spot important functionality.

Creating categories directly from the input box is an interesting idea but since categories are organized in a tree I don't see how that would work. You'd need the separate dialog anyway to set up the structure, rename categories, sort them and so on.
So all this would do is duplicate part of the functionality in a new location.

Collapsible mod list is already a tracked feature request.

The "drop files" section was specifically requested by our UI expert because if it just works when dropping on the mod list it's apparently not obvious enough that the functionality exists.

**Comment by rzjnzk** [comment]
@TanninOne 
I will try to better narrow down what I am trying to say and create separate issues for what I can. Though, is it acceptable to create an issue with regard to the content of the side panel and the right-click context menu, though without mention of the 'Drop files' section and category tree?

**Comment by TanninOne** [comment]
I'm not sure what you're asking tbh.
Each issue you report should be atomic, meaning: it should be possible to understand and complete the issue without knowing any other issues but apart from that it should be as focused as possible.
The point is: When I've finished implementing a feature I want to be able to close a corresponding issue to document the progress.
I don't want to have issues that are partially done but I also don't want to have to do feature B together with feature A just because they were requested in the same issue.
