### ISSUE TITLE
capability to filter mods by SKSE requirement

### ISSUE THREAD

**Issue by Brutusvp47** [Nexus-Mods/Vortex#3893]
A request or maybe it is all ready possible.
Would be nice if it were possible to filter mods based on if they require SKSE64 or not.
What with the frequent updates by Beth, it would be nice to know what Mods I will need to be concerned about needing to up date
Thanks

**Comment by IDCs** [comment]
Picked this one up thinking it would be pretty straight forward feature I could add for 1.0 but wow blimey was I wrong.

- Mods such as SkyUI would require us to extract BSA contents and verify whether they require the script extender.
- Requirements data is currently **not** file based so we can't use the Nexus API to retrieve this information. This _does_ need to change soon, so I would argue lets wait for the per-file requirements/semver enhancements before we tackle this one

**Comment by TanninOne** [comment]
What you're asking for is practically impossible at this time.

In the case of SkyUI for example it does depend on the script extender because it's using it's script functions but those calls are in compiled pex files. The amount of effort it would take for us to extract and then decompile those files and then parse them against the entire set of skse functions (including its plugins!) is insane, 100% impractical.

The requirements information on the website is not currently available to us, once it is we'd definitively integrate it into Vortex anyway.

Finally we're planning a feature where we monitor the game version and warn if the game has been updated to let you know that mods may have become incompatible but obviously this wouldn't tell you which ones.
