### ISSUE TITLE
[Bug Report] - Faulty un-installation

### ISSUE THREAD

**Issue by DDunphy** [Nexus-Mods/Vortex#4079]
**Describe the bug**
Uninstalling Vortex leaves almost a hundred remnants behind, from folders to registry entries. Reinstalling is then problematic, since it's very hard to make sure every remnant is deleted. not sure what you are using as a packaging tool, but you might want to run it back through since it looks like the only thing that's being uninstalled is the add/remove programs entry - even the parent folder in program files is being left behind.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by TanninOne** [comment]
The uninstaller removes the application itself and the registry keys created by the installer.
Everything else you find in the registry is either stuff that the OS or other applications store _about_ Vortex, it's not the job of our uninstaller to clean these up, and the nxm link association where it would make 0 sense to remove it because either way, the links aren't going to work until you set up another application to handle them.

Regarding files on disk the uninstaller isn't intended to remove mods you installed through vortex or profiles you created with it, in the same way you don't expect the uninstaller of Photoshop to remove all the images you created with it.
There is no way for us to know whether you're uninstalling Vortex just to install a newer version or if you just want to install it to a different drive or if you're uninstalling for good. And if you're uninstalling for good, whether you want to keep the mods installed for the games, intend to import them into a different manager or want everything cleaned up.
And then your choice might be different for each game you had managed. And then, if we do uninstall profiles, would you be aware that that also removes the save games and settings made for this profile?

An uninstaller that allows you to remove everything but gives you options to chose what to keep would be almost as complex as the application itself, it would have to support all the deployment methods and profile formats for example.
That's just not realistic. You need to use Vortex to clean up before uninstalling or if you uninstalled Vortex and then found you didn't clean up, you can just install it again.

**Comment by DDunphy** [comment]
Ok, fair enough on half of it.  However, I have packaged apps in large
companies in the past, and a best practice is cleaning up after references
windows creates. It’s never going to be 100%, but there’s a lot of
low-hanging fruit that’s pretty easy to clean.  For example, you leave your
“black Tree Gaming” install directory behind in program files (default).
You can’t say you don’t own that.  You also leave a pile of directories
behind in the Skyrim\data\ folder, and their only content is a “folder
owned by vortex” flag - pretty sure all those are yours too :)  It’s not
hard with the right tool, you just might have to add some scripting at the
end - a few hours at most.  I love the tool, but the more you leave behind
the more cluttery things get, and more potential for issues if/when things
do get reinstalled.  If you want/care about more detail, happy to be part
of the solution.  If not, good luck with things.

**Comment by TanninOne** [comment]
Look, we have considered the uninstall process, I also didn't hatch yesterday, it's just more complex than you realize.

If you purge inside Vortex, it will clean up all empty data directory it created, that's why we have the "__folder_managed_by_vortex" tag in the first place.
If the uninstaller just went and removed the "managed by vortex" tags and empty directory, that would be a destructive operation that may (in certain cases) make a future purge impossible or incomplete - not a good idea.

From your message I can assure you that you massively underestimate the complexity here. Clearing out data that Vortex has to generate in different games (each game potentially having its own specific rules) is way way way more complex than just removing a "regular" application.
Some games might store data in xml, json, yaml, csv, ini or other data files that is required to cleanly remove the mods deployed for that game. Some games may depend on certain empty directories.
The uninstaller removing some files and empty folders without doing a proper purge based on all the Vortex knowledge about the game might render the game unusable and prevent a clean purge in the future, causing more clutter, not less.
An uninstaller in the way you imagine it would have to replicate large parts of the Vortex functionality and it would have to have support for every single game Vortex supports and would have to be extended with every game we add -> impractical.

The purge operation in Vortex is the only correct way to clean up in a game directory, everything else has just as much potential of causing damage as it has to clean something up.

If you think you can do better, feel free to poke around, this is open source after all. There are a few things that we may actually be able to clean up in the uninstaller that it currently don't, e.g. the "Black Tree Gaming" directory, but I can promise you it's all going to be irrelevant stuff that doesn't take up space anyway but anything of importance (the game directories) I guarantee you you won't be able to clean up without risking to do much more damage than good.

The only real way the uninstaller can be improved is by adding a command-line parameter to Vortex itself that will start Vortex in "clean up" mode where it goes through all managed games, purges them, maybe asks the user if they want to uninstall all mods, remove all downloads, move the save games to the default dir and so on and then have the uninstaller _call_ Vortex with that parameter to do all that cleanup before uninstalling the application itself.
But this would require a lot of work, considering all the error cases you may have to handle.

**Comment by DDunphy** [comment]
Ok, good information.  I'm using NMM for comparison, and I haven't seen the
issues I've seen with Vortex.  I hadn't considered the open source option,
that's a good idea, maybe I can contribute if I have the opportunity.  The
command line can be embedded within the installer and a form shown to the
user to do a "Clean" uninstall.  I do understand the complexity, it's
something we deal with in very large companies all the time.  Please take
this as constructive criticism, not a critique of your efforts or
experience.

**Comment by TanninOne** [comment]
You're using NMM for comparison? NMM doesn't clean up anything.

I guess it's a matter of perspective, for example when Vortex changes an ini file it creates two additional variants (.base - the original file, .baked - the file after Vortex applied its own settings) so that it can later to a three-way merge to tell custom user-settings from vortex-made changes and can undo the vortex changes without undoing the user changes.
NMM irreversably changes the ini file, the only way to get the nmm settings out is by restoring a backup you have to create yourself which will then lose you all custom settings made after.
Now you could call the Vortex approach "cluttered" because it's two added files. Or you can appreciate that Vortex let's you cleanly and reliably remove just the changes Vortex made.

In the same way Vortex can remove just the directories it created from the game directory, restoring it to the original state. NMM can't, it can either remove mods it installed and then blindly remove **all** empty directories, potentially breaking the game and/or tools - or it doesn't clean up at all.
But sure, you can consider the marker files that make that possible in Vortex "clutter".

Imho Vortex is way, way superior to NMM in regards to clean up behind it.

Vortex supports over 50 games, the Bethesda games alone require Vortex to write stuff to three different directories each (the game dir, My Games and App Data), 4 data files (plugins.txt, loadorder.txt and two ini files) and savegames. Other games have multiple mod directories, yet others have different mod directories depending on whether you got the game from Steam or somewhere else. There are easily several hundred locations where an uninstaller might have to clean up - tendency growing with each release.
I really kind of doubt that you've come across a lot of applications that have their hand in so many different locations, why would they?

**Comment by DDunphy** [comment]
You'd be surprised.  Keep in mind I'm old - I started my career with
Windows 3.11, through WinNT, Win2k, then XP.  Things really didn't improve
until MSI technology really matured in Windows 7, so when you run it
through that filter of ancient history, it might shed light on why what I
shared isn't insurmountable in my mind - the situation isn't new to me.
I've gone back to NMM for the time being, but if I can fit it, I'm pretty
curious about the installation part of the app.
