### ISSUE TITLE
7DTD wrong mods path

### ISSUE THREAD

**Issue by Darktotaled** [Nexus-Mods/Vortex#4215]
Downloaded Vortex today so i could easilly add mods to my games. I've downloaded 3 mods for 7 days to die 17.2, which are in the printscreen link: http://prntscr.com/n9s3ie
launched the game but it didnt have anything new as it should be. I played it normally till i was done with base building and exited the game. Went to the game folder so i could see if the mods were there and the mods i downloaded via vortex were in the game folder instead of the mods folder.
Not only posting an issue but also asking for an option where we can properly set up the installation folder for the mods. If i remember correctly, some 7dtd mods needs to be extracted inside the mods folder while others that change files in the game have to be extracted in the game folder.

Vortex = latest version(04/09/19)
Game = 7 Days to Die Alpha 17.2
Mods = Firearms 2, Bigger Backpack, Gas and Oil Extraction.

Thanks in Advance

**Comment by IDCs** [comment]
Hi @Darktotaled, I assume by latest version you mean the latest **stable** version (0.17.8) ?

The mod path issue has been fixed in https://github.com/Nexus-Mods/vortex-games/commit/6fc85e3c84cfb2ed5bd09483bdaddaa41b2016f0 which is available in our testing branch (https://github.com/Nexus-Mods/Vortex/releases/tag/v0.17.11) give that a shot and let us know what you think - please note that we have made major changes to 7dtd which will require you to re-install those 3 mods you mentioned.

As for your suggestion, I will discuss this with @TanninOne. (Going to close this issue as the bug you reported is already fixed)

**Comment by Darktotaled** [comment]
Cool.
Thanks for the quick reply =]
Best wishes
