### ISSUE TITLE
Vortex not following dependencies\ vortex keeps changing install order

### ISSUE THREAD

**Issue by RowdyRaza** [Nexus-Mods/Vortex#4499]
Vortex has been messing up my install order for mods so I tried arranging my mods using dependencies but, it's still messing it up making new vegas almost unmoddable

I'm trying to ultramod my new vegas and everything works the day you complete modding and the next day your game is all buggy because vortex ruins my install order

 - OS: [e.g. Windows 7]
![0Untitled](https://user-images.githubusercontent.com/50795137/57980646-60fd7200-7a47-11e9-85bc-d14acce5eef5.jpg)
![Untitled](https://user-images.githubusercontent.com/50795137/57980647-60fd7200-7a47-11e9-876e-f00cf8821cf8.jpg)

**Comment by TanninOne** [comment]
This is not a bug report, just a claim.
You don't show the bug in action.
All I can see is that you're forcing install order on mods that have no conflicts with each other which makes me think you don't understand how install order works in the first place.
Any load before/after rule on a mod that has no lightning icon is pointless.
The install order decides which order mods are deployed in so that the ones loaded later overwrite the files from those loaded before. To show that this doesn't work as intended you need to show
a) that you've set the install order as you claimed (with "mod a" load after/before "mod b"), both mods visible, and
b) show that a file from the mod that was supposed to be loaded first is getting deployed despite that same file existing in the mod being loaded after.

**Comment by RowdyRaza** [comment]
my bad, I'll rephrase if that helps 
Vortex keeps changing my install order alphabetically, I want my install order the way I meant it to be the way I originally installed my mods, is there any way I can do that?

**Comment by TanninOne** [comment]
Again: The Install order doesn't matter between mods that are not related, it's completely 100% irrelevant, why would you want to waste your time on something that makes no difference.

If you just want to _see_ the mods in the order you installed them, all you have to do is click the header of the column you want to sort by and if you click the cog in the top right of the table you can enable the "Installation Time" column.
