### ISSUE TITLE
0.18.6 - installer.exe remnant in ProgramData?

### ISSUE THREAD

**Issue by hl2guide** [Nexus-Mods/Vortex#4775]
**Describe the bug**
installer.exe leftover in %ProgramData%/Vortex folder.
I'm not sure if this happens each time.

**To Reproduce**
1) Install Vortex 0.18.6
2) Uninstall it.

**Expected behavior**
No installer.exe file remnant in %ProgramData%/Vortex folder.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17044982/59037370-73373700-88b4-11e9-9e7d-7b2f06a5eb2f.png)

**Platform**
 - OS:  Windows 10
 - Vortex Version 0.18.6

**Comment by TanninOne** [comment]
This is done as part of the (third-party) installer/updater system.
I assume this file is required to support "incremental" updates, meaning technically the updater would download only the parts of the update that are different from the previous version. For that to work the old installer obviously has to be stored somewhere.
While we don't currently use incremental updates we do intend to enable them at some point.

**Comment by hl2guide** [comment]
I would like to suggest that a checked "Clear Vortex Installer Cache" checkbox upon uninstall would be considerate of the user's disk space.

**Comment by TanninOne** [comment]
Vortex uninstalling requires a bit of work anyway. Right now uninstall is simply the uninstaller generated by the tool used to install it (electron-builder), it removes only the application itself, no data whatsoever.
An uninstall step that also allows (optionally) removing data (temporary files, mods, downloads, ...) is planned but it's not a trivial amount of work (since users can customize all the mod directories, mods are probably deployed to game directories and so on) so it's a fairly substantial project we currently don't have time for.
