### ISSUE TITLE
Feature Request: Install from URL

### ISSUE THREAD

**Issue by Megacrafter127** [Nexus-Mods/Vortex#4926]
**Is your feature request related to a problem? Please describe.**
Thanks to the `Install from Archive` option, it is easily possible to use Vortex to install and manage mods not on the nexus. However, since the installation is from a local file(which Vortex does not make a copy of or store its location), you cannot download/install updates, or use the `reinstall` option available in Vortex whith mods on the nexus.

**Describe the solution you'd like**
Add an `Install from URL` option, which requests a URL from the user.
If this URL points to an archive file that could be used with `Install from Archive`, Vortex downloads the archive from that URL and then installs the plugins from it like `Install from Archive` would.
If the URL does not point to a valid archive file, an error message is displayed to the user.

Since the archive is now stored by Vortex, the reinstall option can be provided like it is with mods on the nexus.

The URL the archive was obtained from is also stored by Vortex, such that (if the protocol has one) the header can be used to determine if the archive changed(last-modified, hashsum, if transmitted).
This can be used to inform the user that a new version of the mod **might** be available.

If during one such update-check it is determined that the URL stopped pointing to a valid archive (connection/protocol errors, invalid mimetype in headers, etc.), flag the mod in the list with an icon (and maybe display a message), that the URL the mod was obtained from is no longer valid. (this flag could also be used to exclude the mod from future update checks)

This method of checking for updates might not work for every site out there, but it should at least be compatible enough to download and install.

**Comment by TanninOne** [comment]
You can click on the drop-area on the downloads page and there input a download url to download it directly. You can also enter the url to a webpage and vortex will let you browse it.
After the download you'd still have to click the install button to get the archive installed but that's only one more click than your proposed solution which I find doesn't justify increasing the clutter in the ui with another button.

Now regarding the update check: It's not so much that your proposed way of checking for updates "might not work for every site" but more that I'd be surprised if it worked with any site. Could you link to a modding site that offers direct download links and hosts new versions of mods with the same url but updated header?

**Comment by Megacrafter127** [comment]
> You can click on the drop-area on the downloads page and there input a download url to download it directly. You can also enter the url to a webpage and vortex will let you browse it.
> After the download you'd still have to click the install button to get the archive installed but that's only one more click than your proposed solution which I find doesn't justify increasing the clutter in the ui with another button.

If downloaded and installed this way, is the `reinstall` option available through the list of mods like it would be for mods from the nexus, or is it just like with install from archive, where that option is not available as the archive is not stored by vortex, and thus might not persist?

> Now regarding the update check: It's not so much that your proposed way of checking for updates "might not work for every site" but more that I'd be surprised if it worked with any site. Could you link to a modding site that offers direct download links and hosts new versions of mods with the same url but updated header?

I know of no such sites. However, it is a solution that provides some basic functionality that doesn't involve implementing whatever update mechanism the many sites are out there are using.

**Comment by TanninOne** [comment]
Yes, you can reinstall any mod that you have installed from files stored by Vortex. The only reason "Install From File" doesn't let you reinstall is because the file isn't in a location "owned" by Vortex.
You can also drag&drop your manually downloaded mods into vortex (the dropzone at the bottom of downloads/mods) and then install it, that will also allow you to reinstall because then Vortex knows where the file is.

> However, it is a solution that provides some basic functionality that doesn't involve implementing whatever update mechanism the many sites are out there are using.

How can you call it "basic functionality" if you can't find a page that uses it? It's not basic functionality, practically every file host will have some form of versioning where new uploads get a different url.
And even if we just look for "does the file exist or not" that's not trivial because the page may not return an error code when the file is deleted very often they may return some placeholder html page which we wouldn't be able to tell apart from the actual file without downloading it which is completely impractical because if we did download, that would mean we'd be downloading the full mod every update check as long as it's available.

And what do you mean "update mechanism the many sites out there are using"? They don't. Other modding sites don't have an update mechanism. I'm not aware of any site apart from Nexus Mods that provides an open interface for tools to update mods.

It just doesn't work like that. Vortex has an extension api through which you could support for update checks for third-party sites but every page works differently, most are built in a way that wouldn't allow this at all and those that do would have to be done individually.
There is no "generic" way to check for file updates.
