### ISSUE TITLE
NMM import - nuke the NMM install after import

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5026]
We could try to remove all mods from the NMM manifest as we import from it. This has a high chance of breaking the NMM install or fail entirely if the manifest is in any way broken.

We could have a backup to work around that but it still has the potential of piss of users if they don't understand they can revert and then break things even worse.

This would fix problem e) completely - if successful, but could produce a whole new reason for outrage.

**Comment by kennethfogarty** [comment]
I think that any kind of deliberate interference with another program is a no-no from a variety of levels.
You could inform/alert the user that one imported, they should not then try to invoke NMM afterwards, because that action will have consequences, including wrecking their mod setup, and more than likely any games they were playing before transitioning from NMM to Vortex.
The downside of this is, will people read and understand the message?

**Comment by TanninOne** [comment]
rejected
