### ISSUE TITLE
Rename Mods in Staging Folder

### ISSUE THREAD

**Issue by FenghuangZero** [Nexus-Mods/Vortex#5285]
Currently when a mod is installed, the archive is copied to the Staging Folder and given a name identical to the archive. When these archives are downloaded directly from the Nexus website, a suffix is added providing the mod's ID number for the game, the version number, 
and occasionally a site-wide ID number. This suffix is automatically hidden when viewing the mod within the Vortex UI, however remains on the folder name when viewed in File Manager. If the mod is updated to a different version opting to replace the existing copy instead of creating a variant, the suffix remains unchanged and corresponds to the wrong version number.

My recommendation is, when changing the Mod Name within the Vortex UI, change the mod's folder name in the Staging Folder to match, or when installing from an archive, ignore the suffix when naming the mod folder in the Staging Folder. This will allow for easier navigation in file manager.

**Comment by TanninOne** [comment]
Navigating the staging folder in a file manager is not really something we support. Obviously it's possible but we're not going to go out of our way to make it "easier" because just about everything you can do there outside Vortex has the potential of breaking something _inside_ Vortex.
The staging folder is a Vortex data folder, use Vortex to manage it.

The directory names are ids, if you change them Vortex will not be able to keep track of the associated meta information.
Renaming inside Vortex would be possible but error prone because third-party extensions may be using these ids to associate their meta information with the mod, Vortex would not be able to update those references and thus lose you data.

The only proper solution would be to introduce a second level of indirection, meaning extensions use a "hidden" id and vortex core maps that id to the directory name and then Vortex would be able to change the directory name without invalidating the id. But that would make all extensions more complex - again: for a use-case we don't really support in the first place.
