### ISSUE TITLE
Xbox One S Gamepad doesnt Work when Vortex starts Kingdom Come

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [Nexus-Mods/Vortex#5509]
**Describe the bug**
When starting Kingdom Come Deliverance with the latest version of Vortex the Gamepad inputs dont work.
I disabled all mods and just started the unmodded game through Vortex.
My Gamepad-inputs arent recognized by the game.
If i start the game through Steam the Gamepad works fine.

**To Reproduce**
Connect Gamepad, start Steam, Start Vortex, start game through Vortex.

**Expected behavior**
Gamepad-inputs should work in the game.

**Screenshots**

**Platform (please complete the following information):**
- Latest Windows 10 Pro

**Additional context**
It used to work just fine. Didnt play it for a while and when i started Vortex it prompted me to update and i did.
Havent gotten it to work ever since.

**Comment by cemerson** [comment]
+1 to this _- although I wonder if this issue is tied more to the issues KCD has with gamepads on Windows in general._ 

My notes (fwiw):
* If I start KCD with Vortex the gamepad is never recognized (just confirming this issue)
* If I start KCD with the gamepad OFF and power it on when at the KCD main menu, the game never see the gamepad.
* If I start KCD with the gamepad ON the game usually does NOT see the gamepad when at the main menu. If I power off the gamepad at this point and power it back on, the game then recognizes the gamepad (I have to do this every time I play the game)

**Setup:** Gamepad: Xbox 360 gamepad, wireless. Windows 10 x64. Latest Vortex and version of KCD game.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
