### ISSUE TITLE
Bug with managing conflicts using Manage Rules

### ISSUE THREAD

**Issue by Serbinek** [Nexus-Mods/Vortex#5779]
Bug Description:
I have a lot of mods installed for Skyrim SE and I have a lot of conflicts which is expected. However problem occurs when I try to manage those conflicts. When setting Mod A to load after Mod B, Mod B is automatically set to load before Mod A but also all the other mods which it has conflicts with. For example, SMIM has 25 conflicts and ELFX 15. If I set SMIM to load before ELFX, ELFX is set to load after SMIM but also ELFX is set to load after the remaining 14 mods and I can't change those conflicts because the box is grayed out and I am unable to click it.

1. Have a number of conflicting mods
2. Find 2 mods which have more than 2 conflicts and also conflict with each other
3. Set first of those 2 mods to load after/before the second one
4. Open manage rules and conflicts from second mod should all be set to before/after and unable to change, and only one of those conflicts will have locket

Expected behavior
Conflicts would be set only for those two mods which I choose to load before/after one another and not for all the other conflicts.

Platform:
 - OS: Windows 10
 - Latest stable Vortex version as of 30th November 2019

**Comment by Rattledagger** [comment]
Just tested this and get the same result. As an added "bonus", after creating enough rules the warning-message "There are unresolved file conflicts" will not show-up, even where's still many conflicting mods as shown by the still red lightning-bolts in the "Dependencies"-column. The information you get by clicking on red/green lightning-bolt seems to be correct.
Vortex v1.1.4, tested on original Skyrim.

**Comment by TanninOne** [comment]
Why not include a screenshot?

**Comment by Drift91** [comment]
It seems this is still an issue. Is there some kind of file I can delete or reset that stores or caches the file conflict information?
![image](https://user-images.githubusercontent.com/2638764/83242458-759c3c00-a16a-11ea-954c-83656ad357d4.png)
As you can see, it's generated a completely random and incorrect rule and then locked it in place. I do not have any manually set rules referencing XPMSE so I don't get where that rule is coming from.

**Comment by TanninOne** [comment]
You are looking at an excerpt of the rules set.
"XP32 Maximum Skeleton Extended" is set to load after "BakaFactory APC LE SE", that's why
BakaFactory is _before_ XP32.
Those grayed out, locked rules are "implicit". They aren't actually set, they are the logical result from other rules you have set. Wich you can see in the first two lines there.
The explicit rule you've set is "patch after base mod". The second line shows the "implicit" which is "base mod before patch". They mean exactly the same thing.

**Comment by Drift91** [comment]
> they are the logical result from other rules you have set.
No, they are not. As the top rule in the screenshot is labelled "only rule currently set". The second conflict in the screenshot is to be expected, I agree. However the one I've pointed an arrow at the bottom is not, nor are the ones just above or below it.

Again, I want to emphasize, these are the *only* rules set after I reset all my rules back to "???" to figure out why several incorrect implicit rules existed. After that, literally the first rule I set ended up creating 4 implicit rules when it should have only created one.

**Comment by TanninOne** [comment]
That rule ("XP32 Maximum Skeleton Extended" is set to load after "BakaFactory APC LE SE") definitively exists, there can't be an implicit rule without an explicit one. The only thing that's possible is that the screen doesn't show it, maybe because of a bug, but you're not giving me a way to verify that because you're only showing the mod rules Bak... to Bat...

**Comment by TanninOne** [comment]
closed due to lack of feedback
