### ISSUE TITLE
Suggestion - backup userlist.yaml file and re-instate if it gets corrupted

### ISSUE THREAD

**Issue by XavierT31830** [Nexus-Mods/Vortex#5820]
(i will do my best with my english)
After a crash windows _(blue screen : stability pbl with my new PC, lot of BSOD, maybe fix now with new chipset driver of my MB, no BSOD during last 3 hours)_ during the installation of one more mod, i open Vortex and i have this red error : 

LOOT operation "loadLists" failed: yaml-cpp: error at line 1, column 3: unknown escape character:
cause.func:  loadLists
func :   loadLists

(details)
Error: LOOT operation "loadLists" failed: yaml-cpp: error at line 1, column 3: unknown escape character: 
    at handleResponse (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:39:69591)
    at Socket.e.on.e (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:39:68224)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

I think userlist.yaml is broken but i don't know how to repair it.

 - OS: Windows 10 Pro 64
 - Vortex Version 1.1.5

I know that delete this file solve just a part of the problem, but if i do that i loose ALL my rules, ALL my order groups and all my load order on my +200 mods... it took me something like more than 2 weeks to perfectly adjust that so i am searching on another solution, please tell me that there's another solution...

I save this broken file to keep an original, i hope there's a way to repair that file in order to recover all my personnal rules, all my settings...

[EDIT] Suggestion : add a "script" or something making Vortex able to copy this file just before installing a mod in order to keep a fresh backup in case of crash like that...

**Comment by IDCs** [comment]
Hi @MamylaPuce, can you please send us the file so we can have a look at it.

**Comment by IDCs** [comment]
Hi again @MamylaPuce, I'm afraid that your userlist.yaml file is corrupted beyond repair :(
![image](https://user-images.githubusercontent.com/8960252/71246920-98027180-230f-11ea-8314-2231b4b343e5.png)

We will look into adding something to protect against something like this happening again

**Comment by MamylaPuce** [comment]
Hello,
omg... the worst news of the end of this year for me ^^ So if i understand good, i am obliged to delete the file and i will have to work again on all rules... Ok :(  Sad but ok.
Yes i think this suggestion could help a lot, this soft is very good, many modders prefer MO2 but i like Vortex, no problem to understand how it works, smooth, fast, simple for me (i was on NMM), i love all on this soft but it’s really a shame to lose all this work because of such an important file which is not protected enough.
Thanks for fast reply, i hope Vortex will become as popular as MO2 because i love this soft, its design, its utility, it's a good job.
Regards,Have a happy holiday !
Mamy la Puce 
    Le vendredi 20 décembre 2019 à 11:05:39 UTC+1, IDCs <notifications@github.com> a écrit :  
 
 
Hi again @MamylaPuce, I'm afraid that your userlist.yaml file is corrupted beyond repair :(


We will look into adding something to protect against something like this happening again

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
