### ISSUE TITLE
Vortex Download Failures Since Data Cap Implemented

### ISSUE THREAD

**Issue by CocoCatDumb** [Nexus-Mods/Vortex#5844]
**Describe the bug**
The majority of downloads coming into Vortex after selecting "Slow Download" option fail (I am not a premium member, and I don't know if having the fast download option would help. I don't have the money to waste trying it, however).  A successful download rarely occurs. Vortex provides a notification that the download starts, the download may or may not show as "Pending" in the queue, then it fails.

**To Reproduce**
1. Go to any mod in Nexus Mods
2. Click on Mod Manager Download in the Files menu
3. Click on "Slow Download"
4. Go to Vortex
5. View the error notification

**Expected behavior**
A successful download. So that a mod can be subsequently installed.

**Screenshots**
![Error Notification](https://user-images.githubusercontent.com/59518163/71773056-7f57a580-2f24-11ea-95d5-def1864e213c.PNG)
![More Info](https://user-images.githubusercontent.com/59518163/71773086-a0b89180-2f24-11ea-9965-df623461cb52.PNG)

(The URL error message is not the only one that may appear,)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.1.5

**Additional context**
Originally, I'd assumed this error to be related to a network issue on my end. However, as a result of that error, I've begun using another system entirely and I am still seeing the issue in exactly the way I experienced it previously.

The downloads typically go through after multiple tries. The most amount of times I've attempted the download of a single mod and experienced a failure was 10, but it had taken less tries for other mods. It should not be failing this often at all.

**Comment by TanninOne** [comment]
Since you didn't provide a link to an affected mod I tried with three random mods, all of which downloaded just fine on the first try.

Also please understand that this kind of problem is usually not caused by the client starting the download but by the website providing it (in the error message you posted for example the website didn't even give us an url to download from) or your connection to it.
Had you contacted the website support staff they could tell you whether the website was encountering technical difficulties at the time but we (Vortex dev team) can't really help with that.

So I'll just have to assume this was a temporary server problem.

**Comment by johnson1965andrew** [comment]
Vortex Version: 1.15.2.0
Memory: 48 GB
System: Windows 11 pro 24HB
I've been trying to install mods from Nexus for 48 hours. I have attempted with over 20 different mods and all result in "download failed". No report from Nexus Mods as to any server problems. Why are you ignoring this consistent problem from so many users?
