### ISSUE TITLE
build: upgrade to electron@^7.0.0

### ISSUE THREAD

**Issue by thetric** [Nexus-Mods/Vortex#5849]
With the [release of Electron 7 the support for Electron 4 has officially ended](https://electronjs.org/blog/electron-7-0). This seems to be a rather huge upgrade so it makes sense to upgrade step by step

**Comment by TanninOne** [comment]
There is already a branch for updating electron but since mayor electron updates are released at a ridiculous rate and they tend to require a lot of work (since they always break compatibility with all native modules of which we use a bunch) updating isn't high on our priority list, especially since there are no security issues (I'm aware off) that would make the update necessary.
