### ISSUE TITLE
Ability to copy text from Vortex Error Screens

### ISSUE THREAD

**Issue by Urhas** [Nexus-Mods/Vortex#5890]
**Is your feature request related to a problem? Please describe.**
It is extremely annoying to have to take screenshots of Vortex errors as you are unable to copy\ paste text from error screens

**Describe the solution you'd like**
The ability to copy text or the addition of a copy to clipboard button for vortex error screens.

An example of the error page is the one captured in :
https://github.com/Nexus-Mods/Vortex/issues/5889

**Comment by TanninOne** [comment]
That's not entirely unintentional tbh.

Usually errors that we want reported because they _might_ indicate a problem with Vortex will have a report button that will not only add in the error message but also details about the Vortex version you're running, OS version and so on.

The error you linked is in the website, not in Vortex. We don't actually want users to report issues like this to us because we can't do anything about them, they need to be reported to the web team.
I know this is frustrating but we have very limited resources for the Vortex team and we don't want to encourage problems to be reported to us that we already know in advance we can't do anything about.
