### ISSUE TITLE
Maximize to wrong position

### ISSUE THREAD

**Issue by simsrw73** [Nexus-Mods/Vortex#605]
If you maximize, restore, maximize the Vortex window, on every other Maximize the entire window is shifted 20-25 pixels down, leaving a gap at the top and obscuring the bottom portion of the window off-screen.

**Comment by TanninOne** [comment]
This is a bug with electron, you can see it on discord and slack as well, probably any electron application that uses a custom titlebar starting from a certain electron version (I'm fairly certain this behaviour didn't exist when  we initially implemented the custom toolbar).

There isn't really a point tracking this here since we can't do much about it until electron is fixed and that can take a while.

**Comment by simsrw73** [comment]
Ok. For reference: It’s been reported there ([electron#12971](https://github.com/electron/electron/issues/12971)) with more info (unclear if cause is [Chromium#853546](https://bugs.chromium.org/p/chromium/issues/detail?id=853546) or update to Windows), includes possible workarounds.
