### ISSUE TITLE
Major update available

### ISSUE THREAD

**Issue by swatt6400** [Nexus-Mods/Vortex#6062]
**Describe the bug**
I just installed v1.2.3 - first time ever installing Vortex.  Just downloaded the very latest release.

**To Reproduce**
1. See notification when Vortex launches saying "Major update available"
2. Click Download
3. Then when it goes to install, it says (sorry I closed it now and reinstalled) that you're installing an older version, and you can Quit or say Yes, I'm mad.
4. This now comes up when re-launching Vortex

**Expected behavior**
Don't show an update notification if you're on the latest version, and if the Download is going to get you an older version.

**Screenshots**
Sorry, didn't capture.

**Platform (please complete the following information):**
 - OS: Win 10
 - Vortex Version v1.2.3

**Comment by Pickysaurus** [comment]
You need to change your settings.

If you installed the 1.2.3 test build directly, Vortex will think you're not opted into the test branch.

Settings -> Vortex -> Update -> "Testing"

This will stop that prompt.

**Comment by TanninOne** [comment]
Vortex auto-updates to the latest version on the channel you're subscribed to. The stable channel is at 1.1.15 so that's what Vortex is trying to "update" to.
As Pickysaurus explained: the solution is to switch to the testing channel.

The (only) officially supported way of getting Vortex is to download from https://www.nexusmods.com/site/mods/1 which hosts only stable releases and then, if you want a testing release, switch the update channel in settings.
