### ISSUE TITLE
Vortex can't update mods

### ISSUE THREAD

**Issue by MarbleDaemon** [Nexus-Mods/Vortex#6074]
**Describe the bug**
Vortex can't update mods

**To Reproduce**
1. Go to 'Mods'
2. Click on 'Check for Updates'
3. No update detected even though the mods actually have update on their Nexus Page

**Expected behavior**
Mods that have updates should be marked

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.1.15

**Comment by TanninOne** [comment]
a) This is missing information, like: What mods are you talking about?
b) Usually, when Vortex can't detect updates for a mod that's because the author isn't providing the necessary information. We can try to improve the detection _if_ you give us concrete examples but until magic is invented there will always be some mods that software can't reliably detect updates for.
