### ISSUE TITLE
Bug Report - Mod Conflict Auto Setting

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/Vortex#6164]
Vortex Version 1.2.9.

When in the mod config window, the opposite selection is no longer automatically applied.

eg: Mod A to load before/after Mod B, the reverse selection is no longer applied to mod B and must be done manually. (Mod A after will no longer set Mod B to before and vice-versa).

**Comment by TanninOne** [comment]
Don't do it manually, just leave it on ???, the notification about unresolved conflicts will still disappear.

If you have a rule "a after b" that implies "b after a". That's what the grayed out rules are, they aren't actually rules but just implied ones and apparently Vortex doesn't show them correctly atm.
But actually setting the inverse rules too may cause problems further down the line, it's more work for you and it will slow down the mod sorting because the sorting will actually have to consider these rules even if they are redundant.

**Comment by crowbar01** [comment]
Doesn't grey out either, it's just which mod overwrites which files, setting one as a priority, be it the suggested or otherwise, it did used to set the opposing mod in the conflict window to the opposite setting, which no longer happens

**Comment by TanninOne** [comment]
Yes I know, I can reproduce the issue. I'm just saying: Do not set the inverse rule. You should only have one rule for each pair of mods in conflict.
