### ISSUE TITLE
XCOM2 Allow mods for DLCs

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#6304]
This is bug report to track this topic: https://forums.nexusmods.com/index.php?/topic/8764768-need-to-change-mod-install-folder/

According to the reporter, XCOM2 has some mods that must be installed to the DLC folder.

**Comment by matthewadamsteil** [comment]
I am the original reporter. XCOM 2 has and expansion XCOM2 WOTC that is nested inside regular xcom2 folder. 

The best solution is for the nexus to add a new game (XCOM2 WOTC) as a game page, much like Divinity: Original Sin 2 and Divinity: Original Sin 2 Definitive edition. That seems like a alot of work particular since it seems that there are a lack of active modders to port their mods or even make a new mod page. 

The next best thing would be if i could select where vortex installs the mods. Its seems to be a feature that vortex had before but had been removed in recent releases.

**Comment by TanninOne** [comment]
@Pickysaurus added support for WOTC in the last release 1.4.3
