### ISSUE TITLE
API Feature Request: Automatically load non-English translation files from extensions

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6311]
**Is your feature request related to a problem? Please describe.**

If I'm reading [the code](https://github.com/Nexus-Mods/Vortex/blob/62f307dbb974d203352702d8fb354660086ba244/src/renderer.tsx#L494) right, Vortex will automatically load a `language.json` file from an extension's install location for English translation/string keys.

**Describe the solution you'd like**

It would be useful to extend this to other languages as well, so that extensions can potentially package their own extension files. This would make it easier to get translations done and keep strings up-to-date through extension updates.

**Describe alternatives you've considered**
Obviously the existing approach of individual translation including extra namespaced files would work as well, but would require updates to strings in extensions to then need updates in a lot of unrelated translation extensions.

**Additional context**

I have a (seemingly working) prototype of this based on how Vortex does things in the [BeatVortex extension](https://github.com/agc93/beatvortex/blob/master/src/index.ts#L196). This API automatically loads files based on name for any language, from the extension directory:

```text
language_en.json -> 'en'
language_fr.json -> 'fr'
```

**Comment by TanninOne** [comment]
No, sorry, that's not the way it's intended to work.
The language.json file you can load there is for the english base language, so that - for example - plurals can be formed correctly.

Actual translations are released as separate "extensions" through the extension system. Languages are only offered through the UI when a localisations has been installed and those translations are intended to cover as much functionality (including extensions) as possible.

If we now allow extensions to offer their own translations this will cause a lot of confusion, i.e. what takes priority if an extension offers its own translation but the installed localization package also has one for that extension?
And: should I offer a language in the language dropdown if only a single extension has translations for it?

I think if you have translations for an extension you should work with the maintainer of the corresponding localization to get it integrated, that way everything related to that language is in one place and can be maintained in a consistent way.

**Comment by agc93** [comment]
Okay, fair enough, that makes sense.

My concern originally was that _hypothetically_ an extension with a large user base changing the wording of a single string would immediately break the translations and cause a lot of flow-on work for translation maintainers, but I also see the reasoning behind designing things that way 👍
