### ISSUE TITLE
Why is it still not possible to choose the root to deploy plugins? (Dark Souls 1)

### ISSUE THREAD

**Issue by Kongolan** [Nexus-Mods/Vortex#6325]
So i'm modding Dark Souls 1 right now and it seems like Vortex is not very capable of it. The main reason for this is, that you can't specific the unpack directory with the "Mod Type" option.

For this the mod UnpackDarkSoulsForModding (https://www.nexusmods.com/darksouls/mods/1304?tab=description) you need unpack it, where the DarkSouls.exe is located, aka the root located in DarkSouls/DATA folder. But Vortex always puts the files down in the DsFix folders. Since DarkSouls seems to have almost 50% of the mods to be unpacked in the root, a option for a Mod Type root, is highly needed. Right now modding with Vortex is just a pain.

I hope this is an easy fix to implement to enhance the flexibility of Vortex by a lot, since you could also install DsFix via this method without preinstalling it, like Vortex suggests.

**Comment by TanninOne** [comment]
You can change the mod type of a mod to "dinput". Mods with that mod type get deployed to the base directory of the game.
I'm not entirely sure what your problem is here because you specifically mention the mod type feature which is specifically there to solve this problem.

**Comment by Kongolan** [comment]
It would deploy it to the root directory but not the DATA directory, where the executable is located. Dark Souls i packed different, so a flexible feature, which would create a Mod Type per Game or is just customizable would be needed. Dark Souls 1 is packed like this root (most likely in steamapps/common/Dark Souls/DATA), while Dark Souls contains another folder for the directX installer: 
![image](https://user-images.githubusercontent.com/1629090/83670995-45bebf80-a5d4-11ea-813f-096005a27e95.png)

**Comment by TanninOne** [comment]
a) it's perfectly possible already to have different mod types per game but
b) it's not necessary in this case, because the mod can just contain a data directory

expecting that Vortex has different installation mechanisms for each individual mods because the mod authors can't adhere to a consistent directory hierarchy is just not realistic.
The mod author can simply repackage the mod to contain the file as "Data\UnpackDarkSoulsForModding.exe", literally 10 seconds of work. There is no point for Vortex to have a separate installation path/mod type to support that.
