### ISSUE TITLE
API Request: allow tool parameters to be returned from a promise

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6629]
**Is your feature request related to a problem? Please describe.**

It would be convenient to be able to semi-dynamically define the parameters for an `IGame` which seems to just use the `ITool` parameters definition. As it stands, parameters are completely static and there's no ways to control how a game launches based on anything (settings, state, anything like that).

**Describe the solution you'd like**

It would be good to be able to define a `Promise<string>`, like `ITool.queryPath` already can. Ideally that would be resolved when the game/tool is launched, but if that's complicated then just having it resolve after the store and API is fully ready would also be decent.

**Describe alternatives you've considered**
I'm honestly not sure of another way to do this, but I might be missing something.

**Additional context**
This would make it possible (for example) to change launch args for a game/tool based on a user setting, or extension state.

**Comment by TanninOne** [comment]
This will probably require a bit more consideration because the current api is designed such that the user can edit all the tools, the user can edit the tool, see the parameters being used, change them, so the parameters you set through the api is more of a preset.

If you want to control the parameters dynamically you'd probably want to disable the user-customizable parameters input _or_ have that appended to whatever gets generated programmatically, in both cases we need a new mechanism on top of what's currently there, not just an extension.

Alternatively there is feature request #3415 which would introduce "variables" that could be used in the parameters line.
With that variant the user could still edit parameters and remove the dynamical parts but at least by default it would work correctly

**Comment by agc93** [comment]
That's a good point, I hadn't really thought about the "main" game exe still being a user-configurable tool.

For what it's worth, in my specific scenario, I'm just looking at providing arguments to the Beat Saber mod loader (provided on the command line at launch) in a way that users are able to override a little more neatly than manually editing the Command Line field in the tool dialog. I could reasonably make any of "disable the user-customisable input", "dynamic variables in parameters" or just "append user parameters to extension-provided ones" work.

**Comment by TanninOne** [comment]
@agc93 Sorry for the late reply.

So assume I would introduce a new api that lets you say something like this
`registerToolParameters(() => ({ BS_FOOBAR: api.getState().settings.beatsaber.foobar === true ? "--foobar" : null }));`
and then in the command line parameters you could then use `--something --somethingelse {BS_FOOBAR}`

Such that the callback registered in registerToolParameters is evaluated everytime the user starts a tool and the variables returned by the callback are then replaced in the effective command line, this would solve your problem?

I would probably keep this global so that an extension can introduce variables that are generally useful (stuff like USER_HOME or APPDATA or something)

**Comment by agc93** [comment]
That API would be absolutely perfect for my use case at least! I'm assuming the `{BS_FOOBAR}` would still be visible in the Command Line Parameters UI for users? 

I like the idea of making it global too, definitely adds potential for cleaner integrations and less duplicating common logic needed for common parameters.

**Comment by TanninOne** [comment]
Yes, it would be visible on the command line, so technically the user could remove it

**Comment by agc93** [comment]
That definitely seems like a pretty good middle ground to me then: extensions can control the parameters they add to a granular level, but users can still control parameters themselves if they know what they're doing.
