### ISSUE TITLE
Read before assuming. Issue with install

### ISSUE THREAD

**Issue by Lyrithus** [Nexus-Mods/Vortex#6705]
**Describe the bug**
Fact: I have the correct, default directory for the "My Documents" folder, here is Copy/Paste:

C:\Users\drumr\Documents

And I even tried the quick fix - Folder [Properties>Location>Restore Default]. Yet Vortex constantly (for both auto install, and manual install location options) says that it ***cannot find the "My Documents" folder***, no matter what. I Believe I know why:

A few weeks ago, I decided to Completely remove OneDrive, which was at the time set up as the default location for Queries regarding library folders, like Documents. It's file location was [C:\Users\drumr\OneDrive\Documents]. To change this, I first copied all of the data to [C:\Users\drumr\Documents] and then force stopped the OneDrive service, then opened regedit to make the default library folders within [C:\Users\drumr] instead of [C:\Users\drumr\OneDrive]. I believe that either Vortex is looking for the old file directory (which would mean that your help page on this matter is incorrect), or, there may be something leftover in the registry giving Vortex false directory information. 

 - OS: Windows 10
 - Vortex Version 1.2.17

**Comment by TanninOne** [comment]
Vortex isn't "looking for" the documents directory. Windows offers a function to ask for where the documents directory is.
The error message you get indicates that Windows itself isn't telling us where the documents directory is, at which point this is a problem in your windows setup.
You seem to be referring to some previous issue or the forum in a manner that makes me think you believe there is only one person working here and that yours is the only feedback we deal with but I honestly don't know what previous communication you refer to.

Fact is: In a correctly configured windows we can ask the operating system where the Documents directory is
Fact is: we have no other reliable way to discovering the documents directory. nor does any other application, they will either fail as well or they use an unreliable hack.
Fact is: It's in your own interest that you fix this in windows instead of us providing some workaround (like manual selection)
Fact is: This is what usually works for people with this problem: https://wiki.nexusmods.com/index.php/Misconfigured_Documents_Folder
if it does not, please look for a working solution using google and then tell us what you found.
