### ISSUE TITLE
Table attributes still visible in toggle menu even when their condition returns false

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6849]
**Describe the bug**
It's entirely possible this is intended behaviour, but it doesn't *seem* like it would be.

If a custom attribute is registered using `context.registerTableAttribute`, but using the `ITableAttribute.condition` property to only show (for example) when the current game supports the attribute, it will still be visible in the Toggle Columns menu at all times, regardless of whether the `condition` returns false or not.

**To Reproduce**
1. Add an attribute with `context.registerTableAttribute` that just returns `false` for it's `condition`
2. Click on the cog for the Toggle Columns menu
3. The attribute will be selectable here, regardless of `condition`'s value

**Expected behavior**
Like I said, this could be expected behaviour, but it just *seems* like `condition` returning `false` should also hide it from the toggle menu. If it is intended, maybe there could also be a `toggleCondition` or something to hide very niche attributes unless the current game supports them?

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.2.18

**Comment by TanninOne** [comment]
This is indeed kind of intentional because we don't know the reason for the condition returning false. The column/attribute might be hidden because it doesn't apply to the active game but also because some other feature isn't active (yet). Depending on that reason it may still make sense for the user to be able to toggle the column even if it isn't currently used, hiding it makes that impossible.
Showing the checkbox for a column that isn't being used may be weird but at least it doesn't prevent a potentially sensible use-case.
I guess it would make sense to mark the entry though to indicate it won't have an immediate effect.

**Comment by TanninOne** [comment]
After a bit of considerations I decided to completely hide those columns from the toggle menu after all.
It's just too difficult to explain to a user why we let them toggle a column that won't show up anyway and the possible for a sensible use-case is probably theoretical anyway. If one comes up we can still reconsider.
