### ISSUE TITLE
Misleading help text for deployment method's popover

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#7435]
**Describe the bug**
The popover text used by the ℹ/`More` element used for both the Settings > Mods > **Deployment Method** and Settings > Interface > **Deploy Mods When Enabled** settings are the same. I don't know if this is intended, but it seems a little confusing that the help for the **Deployment Method** dropdown talk about whether you want to automatically deploy or not.

**To Reproduce**
1. Go to Settings > Mods
2. Click on the ℹ icon beside Deployment Method
3. Do the same for Settings > Interface > Deploy Mods when Enabled
4. See the same help text

**Expected behavior**
Seems like these should have function-specific help text to me. 

**Platform:**
 - OS: Windows 10
 - Vortex Version: 1.3.8

**Additional context**
It's entirely possible this is intentional, in which case feel free to close it.

**Comment by TanninOne** [comment]
Yeah, this is intentional, the text is supposed to explain what deployment is in the first place, the deployment methods have their individual explanation texts.
The current explanation text does indeed miss an explanation of why the method is selectable in the first place though. I will try to elaborate on that a bit.
