### ISSUE TITLE
Downloads Folder Error

### ISSUE THREAD

**Issue by Rhuiviel** [Nexus-Mods/Vortex#7454]
I cant get the program to work at all. As soon as it starts, it pops up an error message. 

Unable to finalize downloads creation/transfer. 

I definitely have full permissions for read/write. I've checked this. It also says this:

EISDIR: illegal operation on a directory, open 'C:\Users\dain_\AppData\Roaming\Vortex\downloads\__vortex_downloads_folder'

I never had this problem with NMM.

**Comment by Pickysaurus** [comment]
Hmm, looks like there's a backslash missing in that path.

**Comment by IDCs** [comment]
@Pickysaurus, the slash is in there, but is escaping a character which is why it's not visible.

@Rhuiviel, for us to provide better support we always require users to include as much information as they can when reporting an issue. Basic things like Vortex version, Windows version and CPU architecture type (x86/x64) are a MUST for us to even consider looking at an issue. Additionally it's always a good idea to attach your vortex.log files!

I'm going to close this issue as you've provided us with nothing actionable - please provide all the information I've requested above (including vortex.log files which can be located inside "%appdata%/Vortex") to this issue and I will re-open it once that's done.

BTW EISDIR signifies that Vortex tried to run a file operation on the path you mentioned expecting to find a file, but encountered a directory instead. I assume "C:\\Users\\dain_\\AppData\\Roaming\\Vortex\\downloads\\__vortex_downloads_folder" is a directory ? is it possible you had created this folder manually in an attempt to fix a different error ?

FYI NMM is still available here: https://github.com/Nexus-Mods/Nexus-Mod-Manager
