### ISSUE TITLE
Minor style glitch in drop-down menus

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#7581]
Dropdown menus do a little dance when you mouse in and out of them. 
![Dropdown bug](https://user-images.githubusercontent.com/31670524/94686565-ecb52d00-0322-11eb-8018-0ba5d2e24555.gif)

**To Reproduce**
See GIF

**Expected behavior**
Option size remains the same

**Comment by TanninOne** [comment]
I know it looks glitchy but this is actually intentional, the alternatives are worse.
If we always restrict the dropdown to the width of the sidebar, in some cases users wouldn't be able to distinguish categories. But if we always allowed the sidebar to extend beyond its width, that would interfere with mouse clicks to the rest of the table.
That's why the menu is allowed to extend beyond the sidebar only while the mouse is hovering over it.
