### ISSUE TITLE
Mod update fails frequently

### ISSUE THREAD

**Issue by epinter** [Nexus-Mods/Vortex#7597]
**Describe the bug**
The mod update feature is inconsistent. Sometimes works, sometimes don't. A clear example is the mod [Skyrim 2020 Parallax by Pfuscher](https://www.nexusmods.com/skyrimspecialedition/mods/2347). It's a big mod, and every time I need to update I need to resolve all the 40 conflicts again. If I check update, Vortex refuses to display the new version or changelog, instead it shows new version notification on another file of the same mod id (a hidden optional file, whiterun parallax textures in this case). So I download from nexus site (using vortex), and I see the two versions, the old "1 Skyrim 2020 4.6 by Pfuscher" and the new "1 Skyrim 2020 5.0", as two separate mods.

Another example, the mod [Racemenu](https://www.nexusmods.com/skyrimspecialedition/mods/19080), I updated the mod today to version 0.4.15, Vortex didn't detect the files from version 0.4.14 and 0.4.15 as same mod.

I did a test to understand the problem, downloaded the "Footprints" mod, everything shows correctly, all versions grouped in one mod. My second test was to rename the 'Footprints 1.5.3-3808-1-5-3.7z' to 'aaaa.7z', and to my surprise vortex continues to detect the mod correctly, ignoring the filename. The last test with Footprints mod was to modify the .7z adding a file into it, this time Vortex wasn't able to detect the Footprints mod. So Vortex detects the mods using the CRC ?

My last test was to download the following files using the web browser from nexus site, and dropping them using Windows Explorer in the "VortexDownload\skyrimse" directory.

'Footprints 1.5.2-3808-1-5-2.7z'  
'Footprints 1.5.3-3808-1-5-3.7z'
'Footprints-3808-1-5-1.7z'
'RaceMenu Special Edition v0-4-10-19080-0-4-10-1573329786.7z'  
'RaceMenu Special Edition v0-4-11-19080-0-4-11-1574392171.7z'  
'RaceMenu Special Edition v0-4-12-19080-0-4-12-1576724270.7z'  
'RaceMenu Special Edition v0-4-13-19080-0-4-13-1596731054.7z'  
'RaceMenu Special Edition v0-4-14-19080-0-4-14-1597081311.7z'  
'Wet and Cold SE v2.2.3-644-2-2-3-1580347227.7z'  
'Wet and Cold SE v2.2.4-644-2-2-4-1580458380.7z'  
'Wet and Cold SE v2.3.0-644-2-3-0-1580692154.7z'  
'Wet and Cold SE v2.4.0-644-2-4-0-1601332084.7z'  
'Wet and Cold v2_20 Alpha 1-644-2-20A1.7z'  
'Wet and Cold v2.2.1A-644-2-2-1A-1547761840.7z'  
'Wet and Cold v2.2.2-644-2-2-2-1551293916.7z'

None of the Racemenu files was grouped as the same mod, footprints was correctly grouped, and 7 files from "Wet and Cold" shows as 4 mods.

**To Reproduce**
See description above.

**Expected behavior**
Different versions of the same mod must be shown as one mod with multiple versions.

**Screenshots**
Attached.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.11
- All mods are for Skyrim Special Edition

![Screenshot 2020-10-02 001407](https://user-images.githubusercontent.com/1561280/94884884-19616580-0445-11eb-97a8-218cd4091c5b.png)
![Screenshot 2020-10-02 001447](https://user-images.githubusercontent.com/1561280/94884889-1a929280-0445-11eb-8330-7cf42a52e27d.png)
![Screenshot 2020-10-02 001320](https://user-images.githubusercontent.com/1561280/94884890-1a929280-0445-11eb-9f9b-867a35d9dc86.png)
![Screenshot 2020-10-02 001349](https://user-images.githubusercontent.com/1561280/94884892-1b2b2900-0445-11eb-9913-cd1f27845e07.png)

**Comment by TanninOne** [comment]
Mod updating and grouping both depend on Vortex knowing that two files are different versions of the same thing, whether this is possible depends on the mod author.

Consider this mod: https://www.nexusmods.com/skyrimspecialedition/mods/5804
You wouldn't want Vortex to update from "8.4 A Quality World Map - Classic with All Roads" to "9.0.1 A Quality World Map - Vivid with Flat Roads" just because one has the bigger version number. These are two different *variants* of the mod uploaded to the same mod page.

Due to these kinds of mods, a mod manager has two choices: It can either err on the side of "caution" and update only if it's certain that a file is actually a newer version of the same *variant* of the mod. In this case it might miss automatic updates and require users to manually update.
Or it can update whenever it sees a newer version of the mod, in which case it will replace some mods with a completely different variant. In this case users will first bite their table due to the mod manager overwriting the mod they wanted with something they didn't want and then they need some way of actively suppressing the update, which is both frustrating and makes the UI more complex.

Vortex goes with the first variant: if the mod author uploads the mod in a way that lets us know two files are different versions of the same mod variant we update automatically, if they don't, users have to update manually.

For the mod grouping we have that same problem: If we group mods that aren't actually the same thing, you wouldn't be able to enable them alongside each other - which would be bad if one was a patch/optional addon to the other. Thus we prefer to group too little rather than too much. But in the case of grouping - because we can't constantly make api requests to the site - we have even less information about the mod than during the update check.
E.g. the update check knows that "RaceMenu v0.4.15" is currently the only main file of the mod, RaceMenu v0.4.14 is listed under "old files" so it's safe to assume one is an update of the other. The mod grouping function doesn't have this information available.

I know this is annoying - trust me, I've been frustrated by this for 10 years now - but the only way this could be fixed is for the site to have stricter rules for uploading mods - and a way to fix the information for all the existing mods.

**Comment by epinter** [comment]
So, a feature that allows the user to group mods manually would be useful in this case ?
