### ISSUE TITLE
Extension's custom i18n namespaces are not used unless manually loaded

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#7605]
> I don't know how much of this is bug vs intended behaviour vs lack of docs

**Describe the bug**

An extension specifying its own namespace (using `info.json` + `context.api.NAMESPACE`) will not be able to use any translations from that namespace unless it also manually loads the namespace at startup using `context.api.getI18n().loadNamespaces(context.api.NAMESPACE)`.

**To Reproduce**

Minimal reproduction (including high-level instructions) are in [this repo](https://github.com/whyareyoudoingthis/vortex-i18n-namespace)

1. Specify a custom namespace in `info.json`
2. Call `context.api.translate('Some Text', {ns: context.api.NAMESPACE})`
3. Text will not appear translated (unless the translation is also in `common.json`)
4. Add a call to `context.api.getI18n().loadNamespaces(context.api.NAMESPACE)` in `once()`
5. Translations in the extension's namespace will now be loaded from file as expected

**Expected behavior**
As always, it's possible this is either a) limitations in design or b) intended behaviour, but **to me** it feels like it should be possible to load the namespace at the same time as the translations are loaded (aka somewhere around `extensions.setTranslation()`)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.11

**Comment by agc93** [comment]
As a potentially separate issue: this also means there seems to be **no way** for an extension to register a UI action (using `IExtensionContext.registerAction` and have its title translated in a custom namespace (since the namespace won't be loaded until `once` is finished). This feels pretty wonky to either a) fill `common.json` with a ton of potentially very-game-specific translations or b) split translations between `common` and the extension namespace.

**Comment by TanninOne** [comment]
I'm confused. Have you forgotten your previous issues re translations? (https://github.com/Nexus-Mods/Vortex/issues/6920 and https://github.com/Nexus-Mods/Vortex/issues/6311)
The english base text is read from the language.json file that is bundled with the extension, *not* from the translation which is a separate package.
This is completely intentional and necessary. The extension, including its english base texts is self contained in a single directory, the locales/en directory is not supposed to contain files shipped with an extension.

Regarding the registerAction title: You're not supposed to translate the title there, translations are supposed to happen only immediately before a text is passed to the ui, the title of an action is part of the action registration, not its rendering.
If you were translating it right there, translation would happen the moment the extension is loaded and it wouldn't update when the language changes.
As such the translation of action titles (as well as all other titles/labels used in register...) happens under the hood...

...or is supposed to happen because I can confirm *that* seems to be broken right now.

**Comment by TanninOne** [comment]
To extend on this:

extensions, including their base language are supposed to be one, self-contained, package. Translations are also one, self-contained, package per language.

The english base language file only has to exist to deal with plural variants ("one comment" vs "15 comments"). Everything else the way it's intended way it's supposed to work is that the text inside the code *is* the english text.
Because of that and because translations are single packages anyway, namespaces aren't actually all that important.

Right now there are plenty of cases where texts are passed untranslated from the extension to Vortex core and then when it gets rendered, that happens with in the default namespace because the code that actually has to render the text doesn't know which extension (and therefore which namespace) the text came from and it's pretty tedious to pass it along.
We will fix it on a case-by-case basis if necessary but long term I'd prefer to change the api to make this cleaner.

My plan is to have a "prepare for translation" function in the api that takes a string, potentially template parameters, returns an object that contains those plus the namespace of the extension calling it. This object can then be passed through anywhere in the vortex api that a string could be used and then when rendering we have everything available we need for rendering.

But obviously this is bit of a larger project, for now I'll have to keep putting out fires where it's actually required.

**Comment by agc93** [comment]
Sorry, it's possible I didn't explain this all that well. The use case I was going for was that a translation (not extension-specific, just a generic translation) would be able to keep translations for game-specific features in separate namespace files. That is, a hypothetical translation could include `common.json` for all the normal Vortex stuff then split the rest out into a `beatvortex.json`, a `vortex-showcase.json` etc to just keep things more organised and make updating translations easier across both Vortex updates and extension updates. Currently, I *think* this requires an extension to load its own namespace at startup or that wouldn't work.

That commit looks like exactly what I was trying to convey about registering UI actions so thanks for that 👍 

---

As always, thanks for all the great work and sorry for all the issues!

**Comment by TanninOne** [comment]
@agc93  I'm still not sure I understand the report tbh. Yes, there is supposed to be one translation namespace per extension, this is how it already works more or less. You do *not* have to loadNamespace yourself, that is handled by the backend automatically. The problem you demonstrated in your sample was a combination of
a) the sample not taking into account that english - being the base language - is treated differently, with its localization file being a part of the extension, not the translation
b) There still being a bunch  of cases where the actual translation of texts happens within Vortex, with no knowledge of which extension the text originated, rather than in the extension.
