### ISSUE TITLE
Vortex crashing hundreds of times on start-up

### ISSUE THREAD

**Issue by jenix106** [Nexus-Mods/Vortex#7665]
Vortex Version: 1.3.11
Memory: 15.95 GB
System: win32 x64 (10.0.18363)
Ever since downloading 1.3.8, Vortex crashes hundreds of times during start-up, this time being around 642. Reverting to an earlier version did not fix this, and I wasn't using an outside installer for anything before the crashes started. Wasn't able to send a bug report through Vortex because it automatically included 1284 log files.
[crash-renderer-1602459080077.dmp.log](https://github.com/Nexus-Mods/Vortex/files/5362393/crash-renderer-1602459080077.dmp.log)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/5362410/vortex.log)

**Comment by IDCs** [comment]
Hi @jenix106, alongside "crash-renderer-1602459080077.dmp.log" there should be a "crash-renderer-1602459080077.dmp" file. Please send us that one as well.

When Vortex crashes, do you get any error message at all or do you just get a whitescreen ?

**Comment by jenix106** [comment]
When I first try to open Vortex, it displays the Vortex logo behind every other program and doesn't progress from there. It only proceeds to the white screen after I try to open it again. No error message.
[crash-renderer-1602459080077.zip](https://github.com/Nexus-Mods/Vortex/files/5365092/crash-renderer-1602459080077.zip)

**Comment by IDCs** [comment]
@jenix106, can you please go to your "C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins" folder and move the "gamebryo-savegame-management" folder somewhere else and try to restart Vortex to see if that helps ?

**Comment by TanninOne** [comment]
The dump you sent in is from Vortex 1.3.5, not from the current version.

**Comment by jenix106** [comment]
I tried moving the file and updating Vortex, neither worked. I'm on 1.3.13 now.

[crash-renderer-1602510901088.zip](https://github.com/Nexus-Mods/Vortex/files/5366237/crash-renderer-1602510901088.zip)

**Comment by TanninOne** [comment]
please also move the plugins "gamebryo-plugin-management" and "theme-switcher" out  of bundledPlugins and try starting again.

Based on the kind of error you get I only see a limited number of possible causes, one being one of our native components messing up their memory management, which is why we're asking you to remove them from the equation.

Another possibility would be foreign software hooked into the process (gpu driver components, antivirus, malware and some tools changing the ui or input behavior of windows do this) messing up _their_ memory management, but from the dump it doesn't look like you have anything like that.

Final possibility I can think of is plain old hardware problems, specifically RAM. Is it possible you're overclocking your system too much or it gets too hot? Is your system otherwise stable during gaming and such?

If this doesn't help, could you send in a few more of the .dmp files it generates? I would like to see if it always crashes in the same place or whether that is also random.

**Comment by jenix106** [comment]
Looks like removing the plugins fixed the crashing. Thanks!

**Comment by TanninOne** [comment]
@jenix106 Ok, thank you. Can you restore the plugins one by one to determine which one it was?

**Comment by jenix106** [comment]
theme-switcher was the cause, but it only crashed once on its own. It only crashed a bunch of times with one or both of the other files.

**Comment by IDCs** [comment]
Hi ejs123, can you please go to your "C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins" folder and remove

**Comment by jenix106** [comment]
I have not used it before, nor have I installed another theme. Only thing I've done outside of mods is toggle different dashboard widgets.

**Comment by TanninOne** [comment]
I'm fairly certain the crash happens when Vortex queries the operating system for the list of fonts you have installed.

This currently happens at startup so that Vortex can immediately offer a font selection on the settings screen. This will change with the next Vortex update, so we only make that query on demand.

Now as to why it crashes I don't know, it has to be somewhat unusual because that code runs for every user on every start, we'd be swamped in crash reports if it wasn't very uncommon.
@jenix106  Do you by any chance have an idea what could be special about your system in regards to system fonts? Have you moved the fonts directory to a different drive or do you use some third-party software to change fonts system-wide?
Have you ever encountered problems in other software like Office when you try to select a font?

**Comment by jenix106** [comment]
I don't think there's anything special, I haven't gotten any errors before and I haven't downloaded anything font-related. The folder is still where it should be.

**Comment by TanninOne** [comment]
We are now only fetching fonts on demand so the crash shouldn't happen any more
