### ISSUE TITLE
Allow extensions to require a version/range of another extension.

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#7735]
**Is your feature request related to a problem? Please describe.**
The existing `IExtensionContext.requireExtension` function allows an extension to require another extension, especially useful if its using an API from that extension (either directly added to `IExtensionContext` or using `registerAPI`). However, there's currently no way to make changes to that API after it's shipped without breaking dependent extensions.

**Describe the solution you'd like**

Ideally, I'd like a parameter added to `IExtensionContext.requireExtension` to include an *optional* version range. Something like:

```typescript
context.requireExtension('Vortex Showcase', '~0.1.0')
```

The way I see it, Vortex could then disable/unload dependent extensions if the installed dependency doesn't match the version range, preventing breaking API changes from blowing up in user's faces.

**Describe alternatives you've considered**

As always, I could be misreading how the whole extension loading and/or dependency checking code works, and this is nothing that can't be solved with gratuitous error checking in dependent extensions but I think it would be more reliable this way.

**Additional context**

Obviously there's no way to specifically install a certain version of a dependency extension, but it would at least be good IMO to unload dependent extensions if the installed dependency is the wrong version.

**Comment by TanninOne** [comment]
I'm not sure how practical that is, considering Vortex updates extensions anyway.
For all intents and  purposes Vortex will always run the newest version of all extensions at any time so a dependency being outdated is not something you'd have to worry about.
The only scenarios I could see this being a problem is
a) the dependent mod gets updated before the dependency - which would really only happen if the same person supplies both and forgot to upload the dependency
b) the dependency has a breaking API change that makes it not backwards compatible and so the version range would have to be something like '<2.0.0'. But for that the author of the dependent extension would have to know the breaking change is coming and update their extension, just so that the ext. doesn't get loaded any more.

**Comment by agc93** [comment]
Yeah that's understandable, but figured I'd raise it in case it was possible. As it is, I'm pretty sure I'm the only one distributing APIs that aren't bundled in Vortex (except maybe the Unreal helper) so understand if it's not possible.

The use case I was thinking of was pretty close to your b) example. Essentially something like Showcase that has its own APIs could follow SemVer properly, and then (_hypothetical_ third-party-published) extensions using its API could specify something like `^0.1.0` in their `requireExtension` call and then if I made breaking changes in the future (necessitating a 0.2.x bump), Vortex would unload their extension, and it wouldn't blow up for users.

**Comment by TanninOne** [comment]
Well, I guess it is something we should support even if it's unlikely to become relevant any time soon and I don't think it will be hard to implement.
