### ISSUE TITLE
Vortex wont connect to Nexus

### ISSUE THREAD

**Issue by LadyFriend** [Nexus-Mods/Vortex#8031]
I opened the app and was given a pop up that said "Failed to log in" followed by "self signed certificate in certificate chain" and a url to the page where I could access my API code.
So I clicked on my now red user symbol, and it popped up the mini window, with the button to "log in on website". Except, unlike every other example I've seen online, when I click on that, it doesn't open the webpage, it opens another mini window in the app itself that just gives me the link to the page, and then a box to enter the code in myself. So I do that, and click save, and all it says is "failed to get access key".
So I reload the API code and try again. Same thing.
I've even uninstalled and reinstalled the app twice, and it still keeps doing it.
I've even tried googling this problem to see if there was ever any solution given to this problem, but I haven't been able to find anything that has helped me resolve this issue.

I'm gonna be honest, I'm not really computer savvy, and the only reason I'm asking for help here is because the app wont let me submit a report through there since I can't log in. So I found this page when looking for help with my problem, and figured I might be able to get some advice here. Because other than this, I'm not really sure what else to do at this point.

**Comment by TanninOne** [comment]
I'm afraid this problem is a bit beyond the scope of help we can offer.
"self-signed certificate in certificate chain" means that you have software installed that hijacks the secure http authentication between Vortex and the site and probably other connections as well.
This is either malware, a hacking attempt or also certain "security" software is known to leave the certificate chain corrupted, after they expired or get uninstalled.

The problem here isn't Vortex but the windows setup. I'm really sorry, but I can't offer assistance for this because even if I could solve it (which I can't) that'd still just mask a severe security problem with your system.
Please review what Anti-Virus/Firewall/Proxy/VPN software you use and verify they are actually trustworthy and set up correctly. If that doesn't help the answer has to be Malware.
