### ISSUE TITLE
Bug Report - Other: Gamebyro Plugins Management failed

### ISSUE THREAD

**Issue by Kraken716** [Nexus-Mods/Vortex#8065]
Vortex Version: 1.3.19
Memory: 15.9 GB
System: win32 x64 (10.0.17763)
I had just updated my Vortex and then found that I had no plugins tab, I searched everywhere and couldn't find a fix, but I did find that  the problem was with my Gamebyro Extensions which look like this: 
![Screenshot 2020-12-04 111026](https://user-images.githubusercontent.com/75474466/101144702-661e1400-3621-11eb-9d9c-fda674df3111.png)

Here are my Vortex logs:

[vortex2.log](https://github.com/Nexus-Mods/Vortex/files/5641714/vortex2.log)
[vortex3.log](https://github.com/Nexus-Mods/Vortex/files/5641716/vortex3.log)
[vortex4.log](https://github.com/Nexus-Mods/Vortex/files/5641718/vortex4.log)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/5641719/vortex.log)
[vortex1.log](https://github.com/Nexus-Mods/Vortex/files/5641720/vortex1.log)

I am also quite new to the modding scene and am also quite new to Vortex so please bear with me.

**Comment by TanninOne** [comment]
The error messages suggest that libraries are missing which is weird because Vortex is supposed to ship with everything you need.

Do you get an error message on startup saying that the Vortex installation has been manipulated? If yes, please reinstall Vortex.
If no, please try installing the current VC redistributables from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
And then please let us know if that helped.

**Comment by Kraken716** [comment]
Hi, this worked and my plugins tab is back!
Thank you!
