### ISSUE TITLE
Exclude files from deployment/conflict check by pattern

### ISSUE THREAD

**Issue by tim-elmer** [Nexus-Mods/Vortex#8254]
**Is your feature request related to a problem? Please describe.**
It's frustrating having to handle a web of interconnecting deployment rules just because I have 70-odd mods with a "readme.txt" or whatever in their root.

**Describe the solution you'd like**
I'd like Vortex to allow users to exclude a pattern from deployment, something like `(readme\.txt)|(changelog\.txt)`, that will be ignored for deployment (and thus conflict checking).

**Describe alternatives you've considered**
- Delete the files: This would work, but requires a decent amount of user effort, is negated any time the mod updates, and shouldn't be necessary with a tool like Vortex IMO.
- Use deployment rules: This is 'working' for me, but it quickly becomes messy with cyclical rules being a normal occurrence.

**Additional context**
This is similar to https://github.com/Nexus-Mods/Vortex/issues/942 and https://github.com/Nexus-Mods/Vortex/issues/2205, but specifies user-provided patterns rather than baked-in or by-game patterns.
This may sound similar to https://github.com/Nexus-Mods/Vortex/issues/2957, but it's a much cheaper search; just file name pattern mach vs. hashing an entire mod collection, and is dealing with files that don't need to be deployed, rather than duplicates.

https://github.com/Nexus-Mods/Vortex/issues/942#issuecomment-486162143 suggests this feature is in the works, but I don't see an issue for it.
https://github.com/Nexus-Mods/Vortex/issues/942#issuecomment-728883497 suggests that the feature has been implemented, but not to what degree (I'm guessing hard-coded per-game), and I can't find any evidence in the application to suggest otherwise.

**Comment by TanninOne** [comment]
Yes, the current implementation is hard-coded patterns per game.
Having this user-configurable is certainly a reasonable request, it's also quite a bit more complicated ui wise though. There is a good chance the user-configurable "ignorelist" would also have to be per-game because a pattern may be valid to ignore in one game but not in another (e.g. *.txt would be safe to ignore in most games but a few may have configuration files with that file extension) and you wouldn't just need a way to ignore a file pattern but also to review the patterns and remove them.

Plus there is a reasonable solution already (rules) so this hasn't the highest priority.

Considering we don't have a UI designer right now this will probably take some time before we get around to it.

We could however consider a solution with no UI at all for now, where you can configure patterns to ignore through a text file and then at some later time we could still add a UI to configure it more conveniently.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
