### ISSUE TITLE
IPC error "An object could not be cloned" when debouncer fires since 1.4

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#8554]
**Describe the bug**
The jump to Electron 11 has introduced a [breaking change from Electron](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception) that I'm having trouble pinning down.

I'm using the Vortex debouncer to fire an event after install that looks like this: (below snippet reproduced from [this extension](https://github.com/agc93/wingvortex/blob/main/src/index.ts#L167) )

```ts
const updateDebouncer: util.Debouncer = new util.Debouncer(
        (newModTable: IModTable) => {
            const state = api.store.getState();
            // ensure anything changed for the active game
            // trimmed for brevity
            log('debug', 'invoking PW slot updates', { newIds })
            return updateSlots(api, newIds.map(i => newModTable[GAME_ID][i]), false);           
        }, 4000);
return (oldValue: IModTable, newValue: IModTable) =>
        updateDebouncer.schedule((err: Error) => log('debug', 'Updated skin slots for PW mods', { err }), newValue);
```

But since the upgrade to Vortex 1.4, every time it fires I get an "An object could not be cloned" error (see below)

**To Reproduce**

This is honestly the hard part: I don't know _exactly_ what's causing this to freak out. I can't see any non-JS objects in my debouncer callback.
1. schedule a debouncer (as above)
2. Trigger the `schedule()` call and wait for the timeout
3. Big angry unrecoverable errors occur

**Expected behavior**
I had a look through some of the debouncers in Vortex itself and nothing seems to have changed there so could it be something specific to being a non-bundled extension? Either way, I'd hope the debouncer just ran like it did before 1.4

**Screenshots**
![image](https://user-images.githubusercontent.com/1369269/108028702-f80db880-7077-11eb-8148-ea94d2af7876.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.4.0

**Additional context**
I don't know how to diagnose this from here. Any guidance would be helpful.

**Comment by TanninOne** [comment]
Hmm, the error stack doesn't point to the debouncer as the culprit but to the log call.

When you log a message it gets serialized and sent via ipc to the "browser" process which then does the actual logging.

Afaik electron 11 now uses the structured clone algorithm to serialize objects for IPC instead of whatever they used before.
My assumption is that it freaks out because the object being logged here (err) is not serializable, it contains functions and properties.
Surely this was invalid before, but likely the old serialization algorithm was more forgiving (e.g. err.stack is usually a property representing a string the old serializer might have just turned it into a regular string)

I don't think this is a bug per se, objects you request to be logged should be serializable, we want to print them to a text file after all but I understand that this may introduce new problems with extensions that used to work before.

**Comment by TanninOne** [comment]
I just realized I pretty much repeated what the link you posted said...

I'm trying to reproduce the issue and will then attempt to catch it, at least for the logging call.

**Comment by TanninOne** [comment]
Ok, further information: inside updateSlots you use _nfs_.promise.readdir instead of the vortex fs wrapper functions.
This then returns a native Promise instead of the bluebird promises Vortex is built around.

The debounced function may return an Error or a bluebird promise, in case of a promise the debouncer will wait for the promise to resolve before invoking the callback you passed in with schedule.

Now because your updateSlots function returns a native promise, the debouncer doesn't treat it as a promise at all and thus passes the Promise object to the callback (the one you passed into schedule) and that then tries to log it.
And a promise can't be serialized.
You should be getting typescript errors for this because Debouncer is typed to only accept a function that returns either an Error or a Bluebird promise so your function doesn't actually fulfill the interface.

So there are a few things to address here:
a) I will make it so the log function will explicitly serialize the meta object so the structured clone algorithm doesn't throw a fit under the hood, that way we can at least handle errors ourselves
b) I will extend the debouncer to work with any kind of promise
c) you should fix the updateSlots function so it returns the expected type. The easiest way to do that is to use Bluebird.resolve(updateSlots(...)) - that way the promise returned from it is automatically converted to a bluebird promise.
alternatively you could just use the fs functions from vortex-api, that way filesystem errors would be handled in a more standardized way too.

**Comment by agc93** [comment]
Alright thanks for the info there, I honestly barely even registered that log call as being there. I'll add in a Bluebird wrapper over that promise and (for now) take out the call to `log` and hopefully that clears it up.
