### ISSUE TITLE
API Request: let the File Based Load Order use regular Promises

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#8582]
**Is your feature request related to a problem? Please describe.**
Most of the asynchronous APIs seem to use either `Promise` or `PromiseLike` so that the exact Promise type doesn't matter so much. The new `ILoadOrderGameInfo` type for the FBLO API though, specifically requires `serialize`/`deserialize` functions to accept/return `Bluebird<LoadOrder` types.

**Describe the solution you'd like**
Ideally, it could use a `PromiseLike` instead so that the extension could return either a Bluebird or native Promise.

**Describe alternatives you've considered**
I understand I can just install Bluebird but that's another package to keep up-to-date, keep synced to Vortex, etc (and I'm just significantly more familiar with the native Promises).

**Additional context**
Seems like most of the other async APIs that extensions use (`IExtensionApi.events.onAsync`, `InstallFunc`, etc) use `Promise` or `PromiseLike` so this is the first instance we're Bluebird is straight up required, from what I can tell.

**Comment by TanninOne** [comment]
@agc93 actually, you don't really need bluebird in sync, at least not if you use our webpack.js script to generate the webpack config, because then bluebird will be treated as an "external" and doesn't get backed into your extension. That way you always load the same version Vortex has.

I haven't verified but I'm fairly certain there are multiple locations where our api would expect bluebird promises because that's what we use all throughout the application.
It'd be a worthy endeavor though to ban bluebird from the api.

**Comment by agc93** [comment]
@TanninOne Yeah I just always want to keep them in sync since the type definitions I'm using could be wrong. For example, if I still had Electron 8.x installed locally, Webpack would (correctly) not bundle it since it's an external but it might not match the module that Vortex has loaded when the extension gets loaded.

Maybe just me being paranoid, but I try and keep the shared deps in sync as much just to avoid problems (even if Webpack doesn't bundle them)
