### ISSUE TITLE
Add a compact mode to the UI

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/Vortex#87]
Right now the large size of all the elements of the UI makes it difficult to see much on the screen at once, especially on low resolution screens (1366x768 here). Changing the default sizes, or at least having a compact theme available would be very, very much appreciated. Below an example of what, I think, should be resized. I'm not a designer by any means, so I won't claim these are the best changes possible, but it gives you an idea.
![2018-02-18_13-29-22](https://user-images.githubusercontent.com/12874678/36351856-c57b66be-14af-11e8-98e8-acbe2e21d899.png)

Again comparing to MO : I can see around 25 mods at once in the mod list of MO, against 7-8 in Vortex, despite Vortex showing less information on the screen than MO.

**Comment by TanninOne** [comment]
0.16.9 contains a compact theme that's particularly focused on providing more space in tables (mods, downloads).
I welcome concrete proposals to make that theme more efficient but since I'm no UI designer and we currently don't have one in the team, I'm only going to do small changes.

The sketched changes to the dashboard don't make too much sense to me, since there is a finite amount of information on the dashboard anyway, shrinking those widgets as you sketched would only increase the amount of empty space, you wouldn't see more information.

The login banner on the top can be disabled anyway, no point removing it entirely.

The "Go Premium" banners can also be removed easily, just buy premium. (scnr)
