### ISSUE TITLE
Vortex idle uses 2% of CPU and constant IO activity

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/Vortex#88]
Vortex, while idling, uses around 2% of CPU and seems to constantly be using around 10 KB/s of IO. Not sure if that's intended, so I thought I'd report it.
![processhacker_2018-02-18_13-34-22](https://user-images.githubusercontent.com/12874678/36351883-79a7c222-14b0-11e8-9de1-0c39e332e0d7.png)

**Comment by TanninOne** [comment]
This should be improved in 0.13.3, especially when Vortex is running in the backgound, can you verify?

Vortex will still have a bit of activity because some functionality in the UI is currently solved via polling but it should be very little, not in a way that disrupts other applications.

**Comment by CreeperLava** [comment]
From what I can see, it hasn't improved. Here are the values when Vortex idles, in the foreground :
![2018-03-02_15-53-44](https://user-images.githubusercontent.com/12874678/36904779-ecabca9a-1e31-11e8-9786-a450b4d9b253.png)
And in the background :
![processhacker_2018-03-02_15-52-51](https://user-images.githubusercontent.com/12874678/36904780-ecc82fdc-1e31-11e8-8fac-34a4f04e13cc.png)

**Comment by TanninOne** [comment]
As I said, the main gain is when Vortex is in the background which is when it's CPU usage matters most (who cares if the front application uses 1% CPU?)
0.05% is pretty much nothing.
Same goes for I/O. The difference between 0.13.3 and 0.13.1 is fluctuation. The reason it does have I/O at all is probably caching the chrome backend does in the background, every chrome/electron based application does that. As does every mozilla- or IE-based application. As does just about every other application under the sun, even the windows task manager itself has a bit of I/O from time to time.
I will admit this sucks a little bit when you're on a laptop running on battery because the I/O keeps the disk from going into standby but again: There is no mainstream webbrowser that doesn't have constant background I/O so it's unlikely _Vortex_ is the sole reason the battery runtime suffers a little.

Same goes for memory, chrome caches stuff it may need later, hence it utilises more memory than absolutely necessary as long as there is plenty available.

These numbers are absolutely fine.

**Comment by CreeperLava** [comment]
I checked, Firefox uses around 0.25% of CPU and a few KB/s of IO when idling in the foreground, with several tabs open. Mod Organizer, 0% CPU and 0 IO.
While I do agree, the Vortex numbers are hardly an issue, it still irks me that Vortex uses, comparatively, so much while idling in the foreground. Background numbers are fine.

Anyways, I look forward to seeing the next updates of Vortex, keep up the good work :).
