### ISSUE TITLE
Please simplify the "external changes" language.

### ISSUE THREAD

**Issue by billw2012** [Nexus-Mods/Vortex#8911]
**Is your feature request related to a problem? Please describe.**
Each time the External Changes dialogue is hard to understand. 

> "Save" will apply the changed file from the game directory permanently. 

> "Revert" will restore the original file from the mod directory.

"Game directory" vs "mod directory" isn't clear (the game has a mod directory). It would be clearer to just refer to the "original file" and the "modified one".

Then in the drop down you use other parenthetical referring to the files in a different manner as "the staging file" and the "deployed file". This adds confusion, again you should just refer to "restore the original file", or "keep the modified one".
But then this also has a third option to "use newer file". Does that mean newer by time stamp? Or version? Or appearance in the mod directory? I can make a better guess when I "Show individual files" about the meaning, as it shows timestamps, and I can't see any other reason it would do so.

**Comment by TanninOne** [comment]
We don't *know* which file is the modified one, that's the point. The user may have modified the file in the game directory or the staging directory, Vortex only knows that they are different.

> Does that mean newer by time stamp? Or version?
Files don't usually have versions. This is by time stamp.

**Comment by billw2012** [comment]
Files do have versions, right click a dll and go to details, and the mods OBVIOUSLY DO have versions, which is a .
Why does vortex not know which file is modified? It has the archives it has downloaded. Does it not record anything about these files when it unzips them? Hashing would be the obvious way to do this. 

And my main point is that the dialogue language is inconsistent and confusing, are you just trying to shut this asap on a technicality while ignoring the core issue I am raising?

**Comment by TanninOne** [comment]
@billw2012 dlls and exes _can_ have a version field but it's not required and it's not required the developer actually increments it.
All other file types (dds, png, txt, json, xml, ...) either don't have a version field at all or it is a custom format and we have no standardized way to get at it.

You are right that we could record the hash for every file we deploy, we even have (commented out) code for that, the problem is that there are mods with thousands or tens of thousands of files, there are mods several gigabytes large. Deployment could take hours if we had to hash every file which is again impractical.
Most mods for most users don't change so this would be a massive inconvenient for a very uncommon use case.

> And my main point is that the dialogue language is inconsistent and confusing, 
I don't necessarily disagree but this is the third iteration of the dialog, the wording isn't even mine, it's what came out of days of discussion with community members.
I'm not trying to shut this up but I can't change the wording every time someone is confused because we'd be moving in circles. I had requests to change the wording to exactly what I had initially.

The core issue is that there is no perfect solution for a generic case, I have worked on this and interacted with users on this several times over the last years. You will just have to trust me that your proposed solution may not work for other users, what you may find intuitive may have already confused someone else two years ago.

If you were to describe a specific use case we may be able to come up with something.

**Comment by billw2012** [comment]
Well my specific case (which over a couple of years of use is the only one I have ever encountered), is that files get modified in my mod directory in the game due to deploying mods via other mechanisms or other mod managers. Specifically in the last case because I am writing a mod, and deploying it directly to the game directory from my IDE, but I also test my nexusmod package of the same mod, so the two conflict. 

What I have a hard time understanding is how people modifying stuff in the staging directory is really something worth worrying about. How can that possibly happen without deliberative knowing action on the users part? The difference here is that the games directory/deployed mod files can easily be modified in many ways by non-deliberative actions, thus it makes sense to assume the player doesn't know what is happening there, or why. But if they modify staging files that are actually IN a Vortex directory and only easily found by knowing where to look, that should mean that when they later see the conflict dialog they are fairly sure why they are seeing it, and what "staging" and "deploy" mean. That isn't the case for someone who just followed a manual mod installation guide and ended up overriding a dependency that Vortex knows about. However maybe I miss something obvious here.

Probably the least controversial suggestion I have to clarify this is just to show the full path for both the files, instead of just the file name. If people modified the file deliberately then they will recognize the path. If they installed a mod manually they might recognize the games mod path.

However regarding hashing, zip and 7z files contain a CRC for every file (and separately for each directory). You don't need to manually hash everything, just either look to the original zip file, and then do the hashing when the conflict is detected to find out which one actually changed, or write out the hashes to a manifest when you first unzip them, and reference them from there.

Sorry I'm recreational UXing, but it was borne of a real frustration with having to parse this dialogs meaning every time, even though the underlying issue I want to solve is simple every time: keep the mod as I downloaded it, or keep it as I modified it.

**Comment by TanninOne** [comment]
> Well my specific case (which over a couple of years of use is the only one I have ever encountered), is that files get modified in my mod directory in the game due to deploying mods via other mechanisms or other mod managers. Specifically in the last case because I am writing a mod, and deploying it directly to the game directory from my IDE, but I also test my nexusmod package of the same mod, so the two conflict.

We are thinking of a mechanism that would allow auto-selecting what to do on external changes based on file patterns.
Initially this would just be an API interface that extensions can then use to to make concrete overrides.
This could then be applied for this use case, e.g. you could set an entire mod so that files from that mod always get synchronized game folder -> staging folder.

> What I have a hard time understanding is how people modifying stuff in the staging directory is really something worth worrying about. How can that possibly happen without deliberative knowing action on the users part? The difference here is that the games directory/deployed mod files can easily be modified in many ways by non-deliberative actions, thus it makes sense to assume the player doesn't know what is happening there, or why. But if they modify staging files that are actually IN a Vortex directory and only easily found by knowing where to look, that should mean that when they later see the conflict dialog they are fairly sure why they are seeing it, and what "staging" and "deploy" mean. That isn't the case for someone who just followed a manual mod installation guide and ended up overriding a dependency that Vortex knows about. However maybe I miss something obvious here.

All you're saying is correct, but modders tend to be tinkerers. A large part of our community want to know how Vortex works and then try to be smart about how they manage their mods. E.g. we had users who thought they _had_ to do file edits in the staging folder because they knew how staging worked but they didn't realize Vortex was capable of synching external changes at all, they assumed Vortex would simply overwrite files in the game folder with whatever was in staging.

Also, Vortex can't assign newly created files in the game directory to the correct mod. If you add a file to the staging folder however, Vortex knows which mod it belongs to. Especially when developing your own mod it may be quite tedious to add files to staging but then to edit existing files in the game directory.

The way it currently works at least we provide an explanation of what's happening and an opportunity for a user to ask for help if they don't understand the dialog rather than Vortex making assumptions about things it can't know for sure.

> Probably the least controversial suggestion I have to clarify this is just to show the full path for both the files, instead of just the file name. If people modified the file deliberately then they will recognize the path. If they installed a mod manually they might recognize the games mod path.

If users deliberately changed files and knew about the staging directory they should understand the distinction between the directory containing the mod and the game directory.

> However regarding hashing, zip and 7z files contain a CRC for every file (and separately for each directory). You don't need to manually hash everything, just either look to the original zip file, and then do the hashing when the conflict is detected to find out which one actually changed, or write out the hashes to a manifest when you first unzip them, and reference them from there.

Huh? We would still have to hash all the files on disk every deployment to see if any checksum changed!
Best case scenario we safe ourselves the initial checksum generation but on the flip side it would make the whole thing more complex because we support any archive format supported by 7z, I'm pretty sure they don't all use the same checksum algorithm. So we wouldn't just be storing the checksum, we'd have to switch between algorithms based on where the file initially came from.

> Sorry I'm recreational UXing, but it was borne of a real frustration with having to parse this dialogs meaning every time, even though the underlying issue I want to solve is simple every time: keep the mod as I downloaded it, or keep it as I modified it.

As I said: Vortex does not know which file is the modified one, if we did we could have a much simpler dialog, yes.
