### ISSUE TITLE
Misconfigured Documents Folder with correct documents folder location

### ISSUE THREAD

**Issue by therealpyroland** [Nexus-Mods/Vortex#9065]
**Describe the bug**
Misconfigured Documents Folder error message

**To Reproduce**
1. open vortex
2. get error message 

**Expected behavior**
no error message

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex-1-1-4-9-1616579989 (that's what the installer says)

**Additional context**
When I first had vortex my documents were in C:\Users\there\OneDrive\Documents but now there in C:\Users\there\Documents after I removed OneDrive and changed the default documents folder location.
I'm not sure if uninstalling will fix the issue. But I don't want to lose any mod data so I haven't tried that yet.

edit: I fixed it by making a fake OneDrive folder. still would be nice to not need it.

**Comment by TanninOne** [comment]
Vortex gets it's information on where Documents is directly from Windows, Vortex doesn't save it from one session to the next. If it's still trying to access the OneDrive directory you did not, in fact, change the documents directory in windows which will likely lead to problems with other applications as well.
Since this is not a Vortex problem, reinstalling it will solve nothing.

Please follow the instructions provided in the link of the error message: https://wiki.nexusmods.com/index.php/Misconfigured_Documents_Folder
