### ISSUE TITLE
Using LOOT (via Vortex) doesn't change the target game

### ISSUE THREAD

**Issue by tryguy** [Nexus-Mods/Vortex#92]
So, if I use LOOT outside of Vortex, and have it sorting Oblivion, for instance.

If I then use VORTEX to start LOOT again, with SSE as the active game, it won't current change LOOT into showing the relevant SSE files, even though I think it's supposed to.

I'm using 0.13.3. And under the LOOT shortcut, there's a command line tag: --game=skyrimse

So, it's obvious that it's supposed to change game contexts to suit what game is currently activated in VORTEX. Currently, it doesn't.

Edit: oh right, I'm using 0.12.3 of LOOT too.

**Comment by TanninOne** [comment]
Good catch. Vortex tries to set the right game through the command line but the game names are all wrong.
For Skyrim SE it has to be `--game="Skyrim Special Edition"`
For the other games capitalisation is wrong, so instead of "fallout3" it has to be "Fallout3"

Fixed in https://github.com/Nexus-Mods/vortex-games/commit/cb83d4e929b6c8b3075495c21c93ec4f6d8aa2d1
