### ISSUE TITLE
KotOR: Archives containing Override folders aren't unpacked correctly

### ISSUE THREAD

**Issue by wxMichael** [Nexus-Mods/Vortex#9281]
**Describe the bug**
When a mod archive contains one or more folders named Override, all files from all Override folders are unpacked and all other files are ignored, leaving the user with a potentially broken installation.

Scenario A:
Mod archive contains necessary files directly inside the archive, and then contains one or more subfolders with optional files, where those subfolders contain a folder named Override.
- Archive.7z
  - primary_file.tga
  - primary_file.txi
  - Optional Extra/
    - Override/
      -  optional_file.tga - **Only this file is unpacked**

Scenario B:
Mod archive contains both primary and alternate files in folders named Override.
The file extracted here could be either, possibly depending on folder names or archival order. I've seen both A and B get extracted in testing.
If the filenames are different, both are extracted when it's likely only one may be desired.
- Archive.7z
  - FolderA
    - Override/
      - replacer.tga
  - FolderB/
    - Override/
      - replacer.tga

**To Reproduce**
1. Download this mod with Vortex: [New Grass by MadDerp](https://www.nexusmods.com/kotor/mods/1207?tab=files)
2. Install the downloaded mod
3. Right-click the mod and Open in File Manager
4. The only file listed is `visualeffects.2da`

**Expected behavior**
The following files should have been unpacked. If we're to attempt Override folder detection, we may need to ask the user to choose which files are unpacked.
- LDA_grass2.tga
- LDA_ivy01.tga
- LDA_leaf02.txi
- LKA_Grass.tga
- LKA_leaf03.tga
- LKA_leaf03.txi
- LMA_bboard01 ver2.tga
- LMA_bboard01.tga
- LMA_bboard01.txi
- LTS_grassfx.tga
- LUN_pgrss01.tga

**Platform**
 - OS: Windows 10
 - Vortex Version: 1.4.12

**Comment by wxMichael** [comment]
Some mods affected by this behavior:
- [New Grass](https://www.nexusmods.com/kotor/mods/1207) - Main files silently ignored.
- [JC's Republic Soldier Fix](https://deadlystream.com/files/file/1180-jcs-republic-soldier-fix-for-k1/) - Optional files are silently ignored.
- [Weapon Model Overhaul Retexture Models](https://www.nexusmods.com/kotor/mods/1228) - Entire 208MB TSL installer is silently ignored.

**Comment by wxMichael** [comment]
Additionally, it looks like mods affected by this have all their files renamed to lowercase-only by Vortex when unpacked.

**Comment by IDCs** [comment]
Hi @wxMichael thanks for your report - I fixed the issue with the custom installer forcing filenames to lowercase when extracted.

I believe we had this chat before (I may be mistaken), but 99% of Vortex's custom installers treat each download as a singular mod and will not function correctly with mods that offer alternatives or optional files within the same mod archive. Those should be distributed in separate archives respecting the overall directory structure of the game's requirements, in this case the override folder is the game's mods folder and therefore Vortex will disregard anything that is outside of it - this is by design.

You need to understand that it is unfeasible for us to cater for every oddball packaging pattern which mod authors create at a whim - we would have to create a custom installer for each pattern which becomes a nightmare to manage when you're distributing 100s of game extensions each with its own packaging patterns.

That being said, Vortex fully supports a battle tested and well established mod packaging pattern for mod authors called "FOMOD" https://fomod-docs.readthedocs.io/en/latest/tutorial.html which does support installing optional elements and alternatives through a step based installer - this pattern is supported by ALL of our game extensions and should be used when this type of packaging pattern is desirable.

So overall there are 3 potential solutions to your report:
1. Contact the mod author, ask him to repackage his mod to use the FOMOD packaging pattern.
2. Contact the mod author, ask him to split the optional files and/or alternatives to different archives.
3. Split the archives yourself and install them separately.

> Weapon Model Overhaul Retexture Models - Entire 208MB TSL installer is silently ignored.
If the mod provides an installer in executable form, why not just use the installer instead of adding it as a mod for Vortex ? you'll have to run the installer anyway.

**Comment by wxMichael** [comment]
Hi @IDCs thanks for the response and that quick fix, though I don't believe we've talked prior, or at least not any time recently.

I do see another solution here, that being a notification to the user that files aren't being unpacked when they may need to be. Most games' mods use only a few filename extensions that could be notified about when not unpacked.
My main concern is that other users, like myself, may have to go back though all their mods to figure out what Vortex didn't unpack. It would be helpful for that process to be more transparent to the user.

As for that mod with the installer, I add all mods to Vortex because it helps to keep them organized and track what I've installed in each profile. Vortex does unpack some files, so it appears to be handling the mod. The icon indicating an exe is in the mod doesn't appear in the UI if the exe isn't unpacked. 

If the team doesn't want to expand the scope of game extensions here, I can respect that.
