### ISSUE TITLE
Feature request: Toggle deployment of txt files per game for games requiring hardlink (e.g, No Man's Sky)

### ISSUE THREAD

**Issue by Matakor** [Nexus-Mods/Vortex#942]
You get a lot of arbitrary conflicts due to txt files included with the mods that only tell you how to install the mod.

**Comment by TanninOne** [comment]
Generally ignoring txt files is not possible because some games/tools will have more important data in txt files and in other cases you may have other files you don't want to see conflicts for.

We intend to introduce a way to "blacklist" files/file patterns though

**Comment by TanninOne** [comment]
This has been implemented in the meantime but apart from a few very common patterns we have to decide from game-to-game which files to suppress because there are games where txt files are used by the game and may contain important information.
So if you have concrete examples of files that should be ignored in a specific game, please report them individually
