### ISSUE TITLE
Variants should share the same dependency

### ISSUE THREAD

**Issue by thecrazy** [Nexus-Mods/Vortex#9440]
Right now you need to reconfigure it every time you install an update or a variant. It's annoying.
If people really need individual dependency config per variant maybe offer to copy settings form another variant on install (a simple drop down menu would do it)

**Comment by IDCs** [comment]
Hey there @thecrazy, I'm assuming that this report is related to Stardew Valley ? I'm not familiar with dependency configuration in SDV, is it simply a .cfg file or something that defines a mod's requirements ?

Although we group mod variants when displaying them to users in the mod page, variants are basically unique copies of the same mod. Although I understand that it can be frustrating when certain files contain configuration data which you would prefer to only maintain globally, another user may prefer having separate configuration between different variants.

As you may know, Vortex is a generic mod manager that supports around 140 games (each with its own modding pattern) changing how variants work for 1 game will affect all other games too, most of which will not have the same modding pattern as SDV - therefore the only way to implement what you're asking for would require an API enhancement to allow each game to respond to it as it sees fit - not impossible, but not trivial either.

I'll leave this open as an enhancement while we contemplate if/how we can implement this.

**Comment by IDCs** [comment]
Hi again - we have considered your suggestion and although we understand it may be annoying to re-apply certain configuration items in-between variants; variants by definition are meant to be distinct, which is why on a design basis I'm afraid we're _not_ going to apply your suggestion, nor will we develop core API functionality to support it.

On the bright side Vortex is highly extensible through its extension system and a 3rd party extension could be developed to satisfy your requirement by members of your community.

A brief introduction and a sample extension can be found here:
https://nexus-mods.github.io/vortex-api/2020/09/04/Introduction.html
https://github.com/Nexus-Mods/Vortex/tree/master/samples/sample-extension
