### ISSUE TITLE
Identify manually added mods

### ISSUE THREAD

**Issue by cybercatgurrl** [Nexus-Mods/Vortex#96]
In NMM when a mod is manually added (in my case SkyrimSE) it will attempt to match it with the Nexus ID. Either Vortex isn't doing it or it isn't doing it well enough. I lent my friend some of my downloaded mods to make it easier on her download (Australia's internet sucks) and it automatically figured out what category it was and who the author was and the version, etc under NMM. Vortex doesn't do this.

**Comment by JustJinxed** [comment]
Neither Skyrim or Fallout 4 mods generally contain info files to pull from. NMM has a meta data matcher that works with the Nexus website. I wonder if they might switch to using an info file to help reduce traffic in the long run, or if they'll copy over the NMM ability. 

either way, I hate having to redownload every mod in order to get a reinstall option going. Can't imagine their servers are liking this much either.

**Comment by TanninOne** [comment]
Vortex has a more reliable way of identifying files using their hashsum, this way we can identify files even when they are not downloaded from nexus, as long as they are identical to a file that exists on nexus.
However, this identification depends on the server providing a database of these hashes and we're still having a bit of trouble with that db being outdated or incomplete.
But it is definitively something Vortex is supposed to have, don't worry.

**Comment by TanninOne** [comment]
I think this is resolved (for a long while actually) as the database has been created and is now being kept updated.
Please feel free to create a new report if there are still issues identifying manually installed files (as long as they exist on Nexus).
