### ISSUE TITLE
Some files not deploying.

### ISSUE THREAD

**Issue by XLRT** [Nexus-Mods/Vortex#9671]
I've been using Vortex for over a year. Recently I've noticed that urns in the ruins have low res vanilla texture. Upon investigation turns out that the texture is in the staging folder, there's no conflicts, no error message. Then I've noticed some weapon textures are missing as well, some textures are not deploying without reason. It's not random, always the same files fail to deploy. Iv'e checked the files, they're not corrupted, no disk errors. Tried to do move deployment, reset all of the rules, reinstall Vortex. Nothing helped.

To Reproduce:
I have no idea. Install nearly 2000 mods and try to resolve conflicts?

Expected behavior:
I would love to see all files deployed.

Screenshots:
N/a

Platform:
 - Windows 10
 - Vortex Version 1.4.14

Additional context:
Also noticed mod rules screen is buggy. Clicking before all/after all not always works (leaves some conflicts with ???). 
Also manage conflicts per mod doesn't save resolutions. Sometimes I had to save twice to not see them reverted.
Also removing locked rule resets resolutions I made before clicking save.

**Comment by IDCs** [comment]
Hi @XLRT - we cannot investigate this issue without your log files and application state. Please submit a bug report through the internal feedback system (top-right -> 3 dots -> Send Feedback -> Bug Report) and make sure you specify that you're posting in regards to issue #9671 and use the "Attach Special File" dropdown button to attach _all_ of the presented options.

Please try to also reproduce the mod rules screen issues you've noticed before submitting the bug report so that we can potentially capture that in the attachments you send us.

**Comment by XLRT** [comment]
Where can I find application state file? I can't send it through Vortex because of the 20MB file limit.

**Comment by IDCs** [comment]
@XLRT, in that case can you will have to generate it - go to settings -> workarounds -> Create Backup, host the file on your favourite cloud service and share a link to it, again through the internal feedback system.

![image](https://user-images.githubusercontent.com/8960252/126274281-42593fb1-7e27-41ef-a7c3-cfb38d99b6bf.png)

**Comment by IDCs** [comment]
Hey @XLRT - so I've been looking at the data you sent us and the deployment manifest you sent us specifies that you have 96883 files deployed from 1425 different mods - what's odd here is the fact that your profile (using the state backup you sent) only has 1326 mods enabled which suggests that you changed the mods configuration somewhat substantially since you sent us the deployment manifest.

Don't hate me - can you please send us your _current_ deployment manifest alongside your _current_ state backup, and make sure you hit the deploy button before you generate and send us any of them - I'm afraid that any investigation I'd be running with the data I currently have will not give us any reliable information as you've added 100 mods and removed 1 as well , potentially adding at least 61 file overrides which are not currently present in the deployment manifest (potentially some of the missing files that aren't being deployed but I can't be sure without a matching deployment manifest and state backup).

What I _can_ say reliably from your state backup is that you have 174 rules defined that reference mods you no longer have installed, which confirms my suspicion that you are indeed affected by the bug I mentioned in my previous post; which could also cause certain mods to not deploy at all. I'll probably add a method of detecting and clearing these automatically to newer versions of Vortex.

**Comment by XLRT** [comment]
The change you are seeing is because I've started migrating away from Vortex. I will send you current state backup and manifest as the files are still not deploying. One of the files affected by this is ruinsurn01.dds located in 1 Skyrim 2020 5.6-2347-5-6-1607018709 staging folder. Ruinsurn01_n.dds deploys fine.

**Comment by IDCs** [comment]
@XLRT, so I can see that a file override for ruinsurn01.dds exists on "Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1" and can confirm that the file (Textures/Clutter/ruinsurn01.dds) isn't deployed at all which should be impossible unless for whatever reason "Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1" no longer includes that file. 

The way the file override works is - if for whatever reason the mod that was overriding a certain file is gone, the "overriden" file should still be able to deploy. In this case, "Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1" should still have it.

The mod you mentioned "1 Skyrim 2020 5.6-2347-5-6-1607018709" does not come with that file (ruinsurn01.dds) included by default so I'm not sure how it ended up inside your staging folder in that directory. Can you please confirm that your Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1 mod has ruinsurn01.dds in there ?

Can you please try to remove the file override for Ruinsurn01_n.dds and see if the file gets deployed ?

**Comment by XLRT** [comment]
I've put some updated files in that staging folder. 

The file is not deployed at all.

So if a file overrides another file but it doesn't exist anymore it still prevents the overridden file from deploying? That makes no sense.

You're asking about Ruinsurn01_n.dds? The normal map gets deployed without problems.

**Comment by XLRT** [comment]
Indeed disabling Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1 lets the texture deploy normally. 
The way file override works is not how I would expect. This prevents people from editing mods (for example deleting large unused textures or leaving just the meshes in staging folder). Vortex should detect deleted file and delete the override rule automatically.

**Comment by IDCs** [comment]
> So if a file overrides another file but it doesn't exist anymore it still prevents the overridden file from deploying? That makes no sense.

No - if a file override exists on a specific mod - the file will not be deployed _unless_ no other mod manages to deploy it. The behaviour for "Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1" is correct - it thinks another mod is handling the file so it doesn't deploy it. But for some reason (I haven't been able to reproduce this on my end) the mod file which is meant to deploy the file never does.

> You're asking about Ruinsurn01_n.dds? The normal map gets deployed without problems.
Sorry that was bad copy pasta - I meant ruinsurn01.dds.

> Indeed disabling Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1 lets the texture deploy normally.
The way file override works is not how I would expect. This prevents people from editing mods (for example deleting large unused textures or leaving just the meshes in staging folder). Vortex should detect deleted file and delete the override rule automatically.

The fact that an override on a different mod affects  the "1 Skyrim 2020 5.6-2347-5-6-1607018709" runsurn01.dds file is unexpected - looking through the overrides and rules it _should_ deploy.

I'm afraid I'm going to have to attempt to replicate your environment, specifically the 200+ mods that have rules and file overrides that may affect "1 Skyrim 2020 5.6-2347-5-6-1607018709" - this may take a while..

**Comment by XLRT** [comment]
> Hold on - are you saying that "Ruins_Clutter_Improved_SE_NMM_v3-1-5870-3-1" does not have the ruinsurn01.dds file ?

Correct. And after some more testing I'm sure that if a file no longer exists it still prevents override loser to deploy resulting in missing file in Skyrim data folder. It happened with different files in other mods as well.

I hope you can reproduce it. 

Thank you for investigating my issue.

**Comment by IDCs** [comment]
> Correct. And after some more testing I'm sure that if a file no longer exists it still prevents conflict loser to deploy resulting in missing file in Skyrim data folder. It happened with different files in other mods as well.

Thanks for this - should increase my chances to reproduce - just to update you, I'm using your state backup to reproduce your mods environment (all ~1240 of them) I'm halfway through the download/installation process. Thankfully once that's done the rules will be applied automatically so I don't have to go through those 1 by 1. I'll update you once I'm done with my testing.

**Comment by IDCs** [comment]
Hi @XLRT - I did manage to fix this in the end - thank you for being patient and apologies for taking so long to fix it.

I've added a check on game startup which will scan all existing file overrides and ensure the files for those still exist - if they don't, they will be removed, ensuring that upon the next deployment event the application state will be fixed and allow the files to get deployed.

Additionally I've added some logic to detect when the user deletes a mod file from the staging folder and remove the defined file override (if there is one); unfortunately this happens during a deployment event as there's no other way for us to detect these changes so there's a chance that the fileOverride will still be in place during that specific deployment event and may require you to deploy your mods yet again - I realize this isn't ideal but if I were to force the deployment event to wait for the state change to occur it will prolong the entire deployment which is already quite time consuming when you have over 800 mods installed.

To be frank, you can avoid this entire scenario entirely by _not_ manually removing mod files from the staging folder (especially the ones that have overrides defined). Although I _think_ I understand why you opt to do this, please understand that Vortex was not designed to cater for this fringe use case, and although Vortex 1.4.16 and above will have these fixes included; I can't guarantee you won't encounter yet another problem down the line caused by direct staging folder manipulation.

If you're absolutely set on manipulating the files, please purge the mods first and close Vortex; you can then modify the staging folder in any way you wish before restarting it (which will guarantee that any redundant file overrides are removed on game activation, and thus you ensure that all files will get deployed correctly)

**Comment by XLRT** [comment]
Thank you very much for your help. I'm happy that this issue is sorted. And thanks for the tip about purging and exiting Vortex.
