### ISSUE TITLE
Change Unresolved File Conflicts - Vortex

### ISSUE THREAD

**Issue by LeiK34F** [Nexus-Mods/Vortex#9741]
Im currently working on the [Bayonetta Extension](https://www.nexusmods.com/site/mods/260) and Im a noob with coding or programing in general and I just don't know where to look for information in regard of how to change the Vortex function **Unresolved File conflicts** (I used this nexus-mods.github.io page to find something that could help me but I just couldnt find or comprehend what I needed). I this case Bayonetta doesnt have any type of mod load order so what I want the extension or Vortex to do is, if there are two mods with the same files I want the user to choose only one mod

![imagen](https://user-images.githubusercontent.com/87281131/127789209-8ec99e9d-137a-4440-9208-d0b0f14b4647.png)
It doesnt matter if all I got is just a vague instruction of what I need to do because is not my intention to make others do my work, but I seriously need help with this please.

Something else I would like to adress (I just don't know how many post or "issues" I can post per day so If this is against the rules Im sorry). Okay here it goes, for some reason Vortex or maybe is the extension just doesnt recognize subfolders for eg: 
![imagen](https://user-images.githubusercontent.com/87281131/127789554-63b708fd-21e0-4f39-a69b-a88cf0092a38.png)

the image above is how the Bayonetta data folder looks like if you want to mod it (the folders pl, wp, em, et, id were added so the game could recognize the modded models or weapons they arent there by default)

and Inside the id folder the subfolder jp and us are not being recognized by Vortex no matter how many times I change the mod installation patterns

![imagen](https://user-images.githubusercontent.com/87281131/127789732-9b17b160-d454-4068-af97-1b09895573d8.png)

**Comment by IDCs** [comment]
Hi there @LeiK34F

> I just don't know where to look for information in regard of how to change the Vortex function Unresolved File conflicts

We currently do not offer the ability for game extensions to change how the conflict resolution system works - any requested changes would have to be made to the mod dependencies extension which would apply to ALL Vortex supported games.

You can however define glob patterns in your game extension to tell the dependency manager to ignore conflicts for certain files using the details property when registering the game extension:
```
details: {
            steamAppId: 1086940,
            stopPatterns: STOP_PATTERNS.map(toWordExp),
            ignoreConflicts: [
                'info.json',
            ],
            ignoreDeploy: [
                'info.json',
            ],
        },
```

> I this case Bayonetta doesnt have any type of mod load order so what I want the extension or Vortex to do is, if there are two mods with the same files I want the user to choose only one mod

That is actually what the conflict editor allows the user to do - he can define the order in which the mods get deployed and thus if mod X is deployed after mod Y, mod X wins the conflict and is the instated mod - they can indeed do a file based conflict resolution as well if they want, but you could warn them against doing that in your extension's description (or through a notification of some sort).

I'm not sure what you mean by Vortex not recognising a set of directories - if you mean it did not create them on startup, that's because you did not add the code to the `prepareForModding` function to create those. Similar to what you do with the `return fs.ensureDirAsync(path.join(discovery.path, 'Bayonetta', 'data'));` you can create a promise chain to create all those directories for you. e.g.
```
const dataDir = path.join(discovery.path, 'Bayonetta', 'data');
return fs.ensureDirAsync(dataDir)
  .then(() => fs.ensureDirWritableAsync(path.join(dataDir, id, us)));
```

`fs.ensureDirWritableAsync` will create the directories recursively btw, which technically means we don't even need the ensureDirAsync call above it.

**Comment by IDCs** [comment]
@LeiK34F did my previous reply to this help at all ?

Can I close this issue ?

**Comment by LeiK34F** [comment]
Hey sorry I took so long to replay, yes it did help. Im actually learning more about js thanks to you. 

Thanks for helping me!

**Comment by IDCs** [comment]
No worries, glad I could help!
