### ISSUE TITLE
"SOSRACEMENU.ESP" is not a valid plugin

### ISSUE THREAD

**Issue by LegnadaryMage** [Nexus-Mods/Vortex#9848]
I've been trying to reinstall some mods and every mods worked fine but this one won't stop saying not a valid plugin. Even after reinstalling it wont work.  I'm wondering what the issue may be and if I can fix it.

Can anyone help me with this issue?

**Comment by IDCs** [comment]
@LegnadaryMage, this error is reported when LOOT fails to parse/read a plugin (it could be corrupted, or just a faulty mod). Given that you've confirmed that you've installed other mods successfully, it's safe for me to assume that the issue lies with the mod itself and this issue should be reported to the mod author - not Vortex support.
